// Code generated by internal/i18ngen from locales/. DO NOT EDIT.
// Source of truth: locales/<locale>/<namespace>.json (I18N_STANDARD.md).

/** Message keys per namespace. */
export const messageKeys = {
  errors: [
    "errors.conflict.detail",
    "errors.conflict.title",
    "errors.forbidden.detail",
    "errors.forbidden.title",
    "errors.internal.detail",
    "errors.internal.title",
    "errors.not_found.detail",
    "errors.not_found.title",
    "errors.rate_limited.detail",
    "errors.rate_limited.title",
    "errors.unauthorized.detail",
    "errors.unauthorized.title",
    "errors.validation.detail",
    "errors.validation.title",
  ] as const,
} as const;

/** Every message key across namespaces. */
export type MessageKey =
  | "errors.conflict.detail"
  | "errors.conflict.title"
  | "errors.forbidden.detail"
  | "errors.forbidden.title"
  | "errors.internal.detail"
  | "errors.internal.title"
  | "errors.not_found.detail"
  | "errors.not_found.title"
  | "errors.rate_limited.detail"
  | "errors.rate_limited.title"
  | "errors.unauthorized.detail"
  | "errors.unauthorized.title"
  | "errors.validation.detail"
  | "errors.validation.title"
;

/** Named placeholders per message key. */
export const messagePlaceholders: Readonly<Record<string, readonly string[]>> = Object.freeze({
  "errors.conflict.detail": [],
  "errors.conflict.title": [],
  "errors.forbidden.detail": [],
  "errors.forbidden.title": [],
  "errors.internal.detail": [],
  "errors.internal.title": [],
  "errors.not_found.detail": [],
  "errors.not_found.title": [],
  "errors.rate_limited.detail": [],
  "errors.rate_limited.title": [],
  "errors.unauthorized.detail": [],
  "errors.unauthorized.title": [],
  "errors.validation.detail": [],
  "errors.validation.title": [],
});

/** Localized messages per locale per key. */
export const messages: Readonly<Record<string, Readonly<Record<string, string>>>> = Object.freeze({
  "en-US": Object.freeze({
    "errors.conflict.detail": "The resource changed; reload and try again.",
    "errors.conflict.title": "The request conflicts with the current state",
    "errors.forbidden.detail": "This action is not available for your account.",
    "errors.forbidden.title": "You are not allowed to do this",
    "errors.internal.detail": "Something failed on our side. The team has been notified.",
    "errors.internal.title": "Internal error",
    "errors.not_found.detail": "The requested resource does not exist or was removed.",
    "errors.not_found.title": "Resource not found",
    "errors.rate_limited.detail": "Wait a moment before trying again.",
    "errors.rate_limited.title": "Too many requests",
    "errors.unauthorized.detail": "Sign in to your account to continue.",
    "errors.unauthorized.title": "Authentication is required",
    "errors.validation.detail": "Check the submitted data and try again.",
    "errors.validation.title": "The request is invalid",
  }),
  "pt-BR": Object.freeze({
    "errors.conflict.detail": "O recurso mudou; recarregue e tente novamente.",
    "errors.conflict.title": "A requisição conflita com o estado atual",
    "errors.forbidden.detail": "Esta ação não está disponível para a sua conta.",
    "errors.forbidden.title": "Você não tem permissão para fazer isso",
    "errors.internal.detail": "Algo falhou do nosso lado. A equipe já foi notificada.",
    "errors.internal.title": "Erro interno",
    "errors.not_found.detail": "O recurso solicitado não existe ou foi removido.",
    "errors.not_found.title": "Recurso não encontrado",
    "errors.rate_limited.detail": "Aguarde um momento antes de tentar novamente.",
    "errors.rate_limited.title": "Muitas requisições",
    "errors.unauthorized.detail": "Entre na sua conta para continuar.",
    "errors.unauthorized.title": "Autenticação é necessária",
    "errors.validation.detail": "Verifique os dados enviados e tente novamente.",
    "errors.validation.title": "A requisição é inválida",
  }),
});
