// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account_deletion.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeDeletedAccount = `-- name: AnonymizeDeletedAccount :execrows
UPDATE app.accounts
SET email = $1::text,
    status = 'deleted',
    email_verified_at = NULL,
    updated_at = $2::timestamptz
WHERE id = $3::uuid
`

type AnonymizeDeletedAccountParams struct {
	PlaceholderEmail string
	ExecutedAt       pgtype.Timestamptz
	AccountID        pgtype.UUID
}

// AnonymizeDeletedAccount replaces the account's private identity with the
// opaque placeholder: the stable identifier survives for referential
// integrity, the email stops being personal data, and the account moves to
// the terminal deleted state.
func (q *Queries) AnonymizeDeletedAccount(ctx context.Context, arg AnonymizeDeletedAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, anonymizeDeletedAccount, arg.PlaceholderEmail, arg.ExecutedAt, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelDeletionRequest = `-- name: CancelDeletionRequest :one
UPDATE app.account_deletion_requests
SET status = 'canceled',
    canceled_at = $1::timestamptz,
    cancel_reason = $2::text,
    updated_at = $1::timestamptz
WHERE account_id = $3::uuid
  AND status = 'requested'
RETURNING id, account_id, status, requested_at, executed_at, canceled_at
`

type CancelDeletionRequestParams struct {
	CanceledAt pgtype.Timestamptz
	Reason     string
	AccountID  pgtype.UUID
}

type CancelDeletionRequestRow struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Status      string
	RequestedAt pgtype.Timestamptz
	ExecutedAt  pgtype.Timestamptz
	CanceledAt  pgtype.Timestamptz
}

// CancelDeletionRequest cancels the active request inside its window; the
// status guard makes the transition once-only and terminal records
// immutable.
func (q *Queries) CancelDeletionRequest(ctx context.Context, arg CancelDeletionRequestParams) (CancelDeletionRequestRow, error) {
	row := q.db.QueryRow(ctx, cancelDeletionRequest, arg.CanceledAt, arg.Reason, arg.AccountID)
	var i CancelDeletionRequestRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.RequestedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
	)
	return i, err
}

const createDeletionRequest = `-- name: CreateDeletionRequest :one

INSERT INTO app.account_deletion_requests (account_id, status, requested_at, updated_at)
VALUES (
    $1::uuid,
    'requested',
    $2::timestamptz,
    $2::timestamptz
)
ON CONFLICT (account_id) WHERE status = 'requested' DO NOTHING
RETURNING id, account_id, status, requested_at, executed_at, canceled_at
`

type CreateDeletionRequestParams struct {
	AccountID   pgtype.UUID
	RequestedAt pgtype.Timestamptz
}

type CreateDeletionRequestRow struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Status      string
	RequestedAt pgtype.Timestamptz
	ExecutedAt  pgtype.Timestamptz
	CanceledAt  pgtype.Timestamptz
}

// Account deletion state machine (P14-T06, docs/PRIVACY.md §4/§5, BR §10).
// The record statements only ever touch the deletion table and the account
// row; the execution statements purge private rows and anonymize public
// authorship while the billing, ledger, pass, moderation and audit schemas
// stay untouched.
// CreateDeletionRequest creates a new active request. The partial unique
// index resolves concurrent requests: the loser inserts nothing and re-reads
// the winner, so the cooldown never restarts. A canceled record may be
// followed by a fresh one; the terminal history is retained.
func (q *Queries) CreateDeletionRequest(ctx context.Context, arg CreateDeletionRequestParams) (CreateDeletionRequestRow, error) {
	row := q.db.QueryRow(ctx, createDeletionRequest, arg.AccountID, arg.RequestedAt)
	var i CreateDeletionRequestRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.RequestedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
	)
	return i, err
}

const deleteDeletedAccountCommunicationPreferenceHistory = `-- name: DeleteDeletedAccountCommunicationPreferenceHistory :execrows
DELETE FROM app.communication_preference_history
WHERE account_id = $1::uuid
`

// DeleteDeletedAccountCommunicationPreferenceHistory removes the preference
// audit trail.
func (q *Queries) DeleteDeletedAccountCommunicationPreferenceHistory(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountCommunicationPreferenceHistory, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountCommunicationPreferences = `-- name: DeleteDeletedAccountCommunicationPreferences :execrows
DELETE FROM app.communication_preferences
WHERE account_id = $1::uuid
`

// DeleteDeletedAccountCommunicationPreferences removes the explicit opt-ins.
func (q *Queries) DeleteDeletedAccountCommunicationPreferences(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountCommunicationPreferences, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountCredentials = `-- name: DeleteDeletedAccountCredentials :execrows
DELETE FROM app.password_credentials
WHERE account_id = $1::uuid
`

// DeleteDeletedAccountCredentials removes the password credential, so no
// stored secret survives the deletion.
func (q *Queries) DeleteDeletedAccountCredentials(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountCredentials, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountDraftRelations = `-- name: DeleteDeletedAccountDraftRelations :execrows
DELETE FROM app.arena_relations
WHERE arena_id IN (
        SELECT id FROM app.arenas WHERE creator_id = $1::uuid AND status = 'draft'
    )
   OR related_arena_id IN (
        SELECT id FROM app.arenas WHERE creator_id = $1::uuid AND status = 'draft'
    )
`

// DeleteDeletedAccountDraftRelations removes linkage rows that reference the
// account's unpublished drafts: a relation is only meaningful while both
// Arenas exist, and drafts do not survive the deletion.
func (q *Queries) DeleteDeletedAccountDraftRelations(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountDraftRelations, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountDrafts = `-- name: DeleteDeletedAccountDrafts :execrows
DELETE FROM app.arenas
WHERE creator_id = $1::uuid
  AND status = 'draft'
`

// DeleteDeletedAccountDrafts removes the account's unpublished drafts:
// private content with no retention obligation. Published Arenas are
// untouched and keep their stable author id.
func (q *Queries) DeleteDeletedAccountDrafts(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountDrafts, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountProfile = `-- name: DeleteDeletedAccountProfile :execrows
DELETE FROM app.profiles
WHERE account_id = $1::uuid
`

// DeleteDeletedAccountProfile removes the profile so public authorship
// becomes unresolvable while published content keeps its stable author id.
func (q *Queries) DeleteDeletedAccountProfile(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountProfile, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountResetTokens = `-- name: DeleteDeletedAccountResetTokens :execrows
DELETE FROM app.password_reset_tokens
WHERE account_id = $1::uuid
`

// DeleteDeletedAccountResetTokens removes every password reset token of the
// account.
func (q *Queries) DeleteDeletedAccountResetTokens(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountResetTokens, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountSessions = `-- name: DeleteDeletedAccountSessions :execrows
DELETE FROM app.sessions
WHERE account_id = $1::uuid
`

// DeleteDeletedAccountSessions removes every session, so no credential of
// the deleted account can ever authenticate again.
func (q *Queries) DeleteDeletedAccountSessions(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountSessions, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountUsernameHistory = `-- name: DeleteDeletedAccountUsernameHistory :execrows
DELETE FROM app.username_history
WHERE account_id = $1::uuid
`

// DeleteDeletedAccountUsernameHistory removes the username audit trail.
func (q *Queries) DeleteDeletedAccountUsernameHistory(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountUsernameHistory, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeletedAccountVerificationTokens = `-- name: DeleteDeletedAccountVerificationTokens :execrows
DELETE FROM app.email_verification_tokens
WHERE account_id = $1::uuid
`

// DeleteDeletedAccountVerificationTokens removes every email verification
// token of the account.
func (q *Queries) DeleteDeletedAccountVerificationTokens(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeletedAccountVerificationTokens, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeletionRequestForAccount = `-- name: GetDeletionRequestForAccount :one
SELECT id, account_id, status, requested_at, executed_at, canceled_at
FROM app.account_deletion_requests
WHERE account_id = $1::uuid
ORDER BY (status = 'requested') DESC, requested_at DESC, id DESC
LIMIT 1
`

type GetDeletionRequestForAccountRow struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	Status      string
	RequestedAt pgtype.Timestamptz
	ExecutedAt  pgtype.Timestamptz
	CanceledAt  pgtype.Timestamptz
}

// GetDeletionRequestForAccount loads the owner-scoped deletion state: the
// active request when one exists, otherwise the most recent terminal record.
func (q *Queries) GetDeletionRequestForAccount(ctx context.Context, accountID pgtype.UUID) (GetDeletionRequestForAccountRow, error) {
	row := q.db.QueryRow(ctx, getDeletionRequestForAccount, accountID)
	var i GetDeletionRequestForAccountRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.RequestedAt,
		&i.ExecutedAt,
		&i.CanceledAt,
	)
	return i, err
}

const listDueDeletionRequests = `-- name: ListDueDeletionRequests :many
SELECT id, account_id, requested_at
FROM app.account_deletion_requests
WHERE status = 'requested'
  AND requested_at <= $1::timestamptz
ORDER BY requested_at, id
`

type ListDueDeletionRequestsRow struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	RequestedAt pgtype.Timestamptz
}

// ListDueDeletionRequests returns active requests whose cooldown elapsed,
// oldest first, so the workflow can execute them.
func (q *Queries) ListDueDeletionRequests(ctx context.Context, dueBefore pgtype.Timestamptz) ([]ListDueDeletionRequestsRow, error) {
	rows, err := q.db.Query(ctx, listDueDeletionRequests, dueBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueDeletionRequestsRow{}
	for rows.Next() {
		var i ListDueDeletionRequestsRow
		if err := rows.Scan(&i.ID, &i.AccountID, &i.RequestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeletionExecuted = `-- name: MarkDeletionExecuted :execrows
UPDATE app.account_deletion_requests
SET status = 'executed',
    executed_at = $1::timestamptz,
    updated_at = $1::timestamptz
WHERE account_id = $2::uuid
  AND status = 'requested'
  AND requested_at <= $3::timestamptz
`

type MarkDeletionExecutedParams struct {
	ExecutedAt pgtype.Timestamptz
	AccountID  pgtype.UUID
	DueBefore  pgtype.Timestamptz
}

// MarkDeletionExecuted records the terminal executed state on the active
// request. The cooldown is enforced in the statement itself (defense in
// depth): a request whose window has not elapsed can never execute early.
func (q *Queries) MarkDeletionExecuted(ctx context.Context, arg MarkDeletionExecutedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeletionExecuted, arg.ExecutedAt, arg.AccountID, arg.DueBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeDeletedAccountExports = `-- name: PurgeDeletedAccountExports :execrows
UPDATE app.data_exports
SET status = 'expired',
    document = NULL,
    document_sha256 = NULL,
    updated_at = $1::timestamptz
WHERE account_id = $2::uuid
  AND status IN ('requested', 'ready')
`

type PurgeDeletedAccountExportsParams struct {
	PurgedAt  pgtype.Timestamptz
	AccountID pgtype.UUID
}

// PurgeDeletedAccountExports expires the account's personal exports and
// drops their documents: the private data copy never outlives the account.
// The records survive as retention evidence, matching the export invariant.
func (q *Queries) PurgeDeletedAccountExports(ctx context.Context, arg PurgeDeletedAccountExportsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedAccountExports, arg.PurgedAt, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDeletedAccountAdminRoles = `-- name: RevokeDeletedAccountAdminRoles :execrows
UPDATE app.admin_roles
SET revoked_at = $1::timestamptz
WHERE account_id = $2::uuid
  AND revoked_at IS NULL
`

type RevokeDeletedAccountAdminRolesParams struct {
	RevokedAt pgtype.Timestamptz
	AccountID pgtype.UUID
}

// RevokeDeletedAccountAdminRoles revokes any active administrative role of
// the deleted account. The assignment row is retained as restricted audit
// evidence; marking it revoked removes the latent privilege.
func (q *Queries) RevokeDeletedAccountAdminRoles(ctx context.Context, arg RevokeDeletedAccountAdminRolesParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeletedAccountAdminRoles, arg.RevokedAt, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
