// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: arenas.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeArena = `-- name: CloseArena :one
UPDATE app.arenas
SET status = 'closed',
    version = version + 1
WHERE id = $1 AND creator_id = $2 AND status = 'published' AND version = $3
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type CloseArenaParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
	Version   int32
}

// CloseArena performs the published→closed transition requested by the
// creator under the optimistic version check. Reopening does not exist in
// the MVP (P08-T05).
func (q *Queries) CloseArena(ctx context.Context, arg CloseArenaParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, closeArena, arg.ID, arg.CreatorID, arg.Version)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const createArena = `-- name: CreateArena :one

INSERT INTO app.arenas (creator_id, statement, context, category, language)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type CreateArenaParams struct {
	CreatorID pgtype.UUID
	Statement string
	Context   pgtype.Text
	Category  string
	Language  string
}

// Arena draft queries for the PostgreSQL platform adapter.
//
// Drafts are private: every query is scoped by the creator and public
// projections never select a draft. Creating or editing a draft never
// touches the Arena Pass ledger (P08-T03).
func (q *Queries) CreateArena(ctx context.Context, arg CreateArenaParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, createArena,
		arg.CreatorID,
		arg.Statement,
		arg.Context,
		arg.Category,
		arg.Language,
	)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const deleteArenaDraft = `-- name: DeleteArenaDraft :execrows
DELETE FROM app.arenas
WHERE id = $1 AND creator_id = $2 AND status = 'draft'
`

type DeleteArenaDraftParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
}

func (q *Queries) DeleteArenaDraft(ctx context.Context, arg DeleteArenaDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArenaDraft, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArenaByID = `-- name: GetArenaByID :one
SELECT id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
FROM app.arenas
WHERE id = $1
`

func (q *Queries) GetArenaByID(ctx context.Context, id pgtype.UUID) (AppArena, error) {
	row := q.db.QueryRow(ctx, getArenaByID, id)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const getArenaForCreator = `-- name: GetArenaForCreator :one
SELECT id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
FROM app.arenas
WHERE id = $1 AND creator_id = $2
`

type GetArenaForCreatorParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
}

func (q *Queries) GetArenaForCreator(ctx context.Context, arg GetArenaForCreatorParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, getArenaForCreator, arg.ID, arg.CreatorID)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const getArenaStateByID = `-- name: GetArenaStateByID :one
SELECT status, version
FROM app.arenas
WHERE id = $1
`

type GetArenaStateByIDRow struct {
	Status  string
	Version int32
}

func (q *Queries) GetArenaStateByID(ctx context.Context, id pgtype.UUID) (GetArenaStateByIDRow, error) {
	row := q.db.QueryRow(ctx, getArenaStateByID, id)
	var i GetArenaStateByIDRow
	err := row.Scan(&i.Status, &i.Version)
	return i, err
}

const getArenaStateForCreator = `-- name: GetArenaStateForCreator :one
SELECT status, version
FROM app.arenas
WHERE id = $1 AND creator_id = $2
`

type GetArenaStateForCreatorParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
}

type GetArenaStateForCreatorRow struct {
	Status  string
	Version int32
}

// GetArenaStateForCreator diagnoses why a scoped draft write affected no
// row: missing or foreign arena, non-draft status, or stale version.
func (q *Queries) GetArenaStateForCreator(ctx context.Context, arg GetArenaStateForCreatorParams) (GetArenaStateForCreatorRow, error) {
	row := q.db.QueryRow(ctx, getArenaStateForCreator, arg.ID, arg.CreatorID)
	var i GetArenaStateForCreatorRow
	err := row.Scan(&i.Status, &i.Version)
	return i, err
}

const listArenaDraftsForCreator = `-- name: ListArenaDraftsForCreator :many
SELECT id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
FROM app.arenas
WHERE creator_id = $1 AND status = 'draft'
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListArenaDraftsForCreator(ctx context.Context, creatorID pgtype.UUID) ([]AppArena, error) {
	rows, err := q.db.Query(ctx, listArenaDraftsForCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppArena{}
	for rows.Next() {
		var i AppArena
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Slug,
			&i.Statement,
			&i.Context,
			&i.Category,
			&i.Language,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.ClosesAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicArenasPage = `-- name: ListPublicArenasPage :many
SELECT id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
FROM app.arenas
WHERE status IN ('published', 'closed', 'restricted')
  AND ($1::text IS NULL OR language = $1::text)
  AND ($2::text IS NULL OR category = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
  AND (
      $4::timestamptz IS NULL
      OR (published_at, id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY published_at DESC, id DESC
LIMIT $6
`

type ListPublicArenasPageParams struct {
	LanguageFilter   pgtype.Text
	CategoryFilter   pgtype.Text
	StatusFilter     pgtype.Text
	AfterPublishedAt pgtype.Timestamptz
	AfterID          pgtype.UUID
	PageLimit        int32
}

// ListPublicArenasPage returns one keyset page of the public feed, newest
// first, with optional language, category and status filters. Only publicly
// visible statuses are ever candidates: drafts and removed Arenas can never
// appear, and the (published_at, id) tuple comparison never duplicates or
// skips rows (P08-T06).
func (q *Queries) ListPublicArenasPage(ctx context.Context, arg ListPublicArenasPageParams) ([]AppArena, error) {
	rows, err := q.db.Query(ctx, listPublicArenasPage,
		arg.LanguageFilter,
		arg.CategoryFilter,
		arg.StatusFilter,
		arg.AfterPublishedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppArena{}
	for rows.Next() {
		var i AppArena
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Slug,
			&i.Statement,
			&i.Context,
			&i.Category,
			&i.Language,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.ClosesAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishArenaDraft = `-- name: PublishArenaDraft :one
UPDATE app.arenas
SET status = 'published',
    slug = $3,
    published_at = $4,
    version = version + 1
WHERE id = $1 AND creator_id = $2 AND status = 'draft' AND version = $5
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type PublishArenaDraftParams struct {
	ID          pgtype.UUID
	CreatorID   pgtype.UUID
	Slug        pgtype.Text
	PublishedAt pgtype.Timestamptz
	Version     int32
}

// PublishArenaDraft performs the draft→published transition under the
// optimistic version check inside the publication transaction, so the Arena
// row and the consumed Arena Pass commit together (P08-T04).
func (q *Queries) PublishArenaDraft(ctx context.Context, arg PublishArenaDraftParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, publishArenaDraft,
		arg.ID,
		arg.CreatorID,
		arg.Slug,
		arg.PublishedAt,
		arg.Version,
	)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const removeArena = `-- name: RemoveArena :one
UPDATE app.arenas
SET status = 'removed',
    version = version + 1
WHERE id = $1 AND status IN ('published', 'closed', 'restricted') AND version = $2
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type RemoveArenaParams struct {
	ID      pgtype.UUID
	Version int32
}

// RemoveArena applies the moderation removal to a published, closed or
// restricted Arena under the optimistic version check; removed is terminal.
func (q *Queries) RemoveArena(ctx context.Context, arg RemoveArenaParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, removeArena, arg.ID, arg.Version)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const restrictArena = `-- name: RestrictArena :one
UPDATE app.arenas
SET status = 'restricted',
    version = version + 1
WHERE id = $1 AND status IN ('published', 'closed') AND version = $2
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type RestrictArenaParams struct {
	ID      pgtype.UUID
	Version int32
}

// RestrictArena applies the moderation restriction to a published or closed
// Arena under the optimistic version check (P08-T05).
func (q *Queries) RestrictArena(ctx context.Context, arg RestrictArenaParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, restrictArena, arg.ID, arg.Version)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const updateArenaDraft = `-- name: UpdateArenaDraft :one
UPDATE app.arenas
SET statement = $3,
    context = $4,
    category = $5,
    language = $6,
    version = version + 1
WHERE id = $1 AND creator_id = $2 AND version = $7 AND status = 'draft'
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type UpdateArenaDraftParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
	Statement string
	Context   pgtype.Text
	Category  string
	Language  string
	Version   int32
}

// UpdateArenaDraft replaces the mutable draft fields under an optimistic
// version check: a stale expected version affects no row (P08-T03).
func (q *Queries) UpdateArenaDraft(ctx context.Context, arg UpdateArenaDraftParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, updateArenaDraft,
		arg.ID,
		arg.CreatorID,
		arg.Statement,
		arg.Context,
		arg.Category,
		arg.Language,
		arg.Version,
	)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}
