// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: arenas.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArena = `-- name: CreateArena :one

INSERT INTO app.arenas (creator_id, statement, context, category, language)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type CreateArenaParams struct {
	CreatorID pgtype.UUID
	Statement string
	Context   pgtype.Text
	Category  string
	Language  string
}

// Arena draft queries for the PostgreSQL platform adapter.
//
// Drafts are private: every query is scoped by the creator and public
// projections never select a draft. Creating or editing a draft never
// touches the Arena Pass ledger (P08-T03).
func (q *Queries) CreateArena(ctx context.Context, arg CreateArenaParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, createArena,
		arg.CreatorID,
		arg.Statement,
		arg.Context,
		arg.Category,
		arg.Language,
	)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const deleteArenaDraft = `-- name: DeleteArenaDraft :execrows
DELETE FROM app.arenas
WHERE id = $1 AND creator_id = $2 AND status = 'draft'
`

type DeleteArenaDraftParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
}

func (q *Queries) DeleteArenaDraft(ctx context.Context, arg DeleteArenaDraftParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArenaDraft, arg.ID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getArenaForCreator = `-- name: GetArenaForCreator :one
SELECT id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
FROM app.arenas
WHERE id = $1 AND creator_id = $2
`

type GetArenaForCreatorParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
}

func (q *Queries) GetArenaForCreator(ctx context.Context, arg GetArenaForCreatorParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, getArenaForCreator, arg.ID, arg.CreatorID)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const getArenaStateForCreator = `-- name: GetArenaStateForCreator :one
SELECT status, version
FROM app.arenas
WHERE id = $1 AND creator_id = $2
`

type GetArenaStateForCreatorParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
}

type GetArenaStateForCreatorRow struct {
	Status  string
	Version int32
}

// GetArenaStateForCreator diagnoses why a scoped draft write affected no
// row: missing or foreign arena, non-draft status, or stale version.
func (q *Queries) GetArenaStateForCreator(ctx context.Context, arg GetArenaStateForCreatorParams) (GetArenaStateForCreatorRow, error) {
	row := q.db.QueryRow(ctx, getArenaStateForCreator, arg.ID, arg.CreatorID)
	var i GetArenaStateForCreatorRow
	err := row.Scan(&i.Status, &i.Version)
	return i, err
}

const listArenaDraftsForCreator = `-- name: ListArenaDraftsForCreator :many
SELECT id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
FROM app.arenas
WHERE creator_id = $1 AND status = 'draft'
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListArenaDraftsForCreator(ctx context.Context, creatorID pgtype.UUID) ([]AppArena, error) {
	rows, err := q.db.Query(ctx, listArenaDraftsForCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppArena{}
	for rows.Next() {
		var i AppArena
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Slug,
			&i.Statement,
			&i.Context,
			&i.Category,
			&i.Language,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.ClosesAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishArenaDraft = `-- name: PublishArenaDraft :one
UPDATE app.arenas
SET status = 'published',
    slug = $3,
    published_at = $4,
    version = version + 1
WHERE id = $1 AND creator_id = $2 AND status = 'draft' AND version = $5
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type PublishArenaDraftParams struct {
	ID          pgtype.UUID
	CreatorID   pgtype.UUID
	Slug        pgtype.Text
	PublishedAt pgtype.Timestamptz
	Version     int32
}

// PublishArenaDraft performs the draft→published transition under the
// optimistic version check inside the publication transaction, so the Arena
// row and the consumed Arena Pass commit together (P08-T04).
func (q *Queries) PublishArenaDraft(ctx context.Context, arg PublishArenaDraftParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, publishArenaDraft,
		arg.ID,
		arg.CreatorID,
		arg.Slug,
		arg.PublishedAt,
		arg.Version,
	)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}

const updateArenaDraft = `-- name: UpdateArenaDraft :one
UPDATE app.arenas
SET statement = $3,
    context = $4,
    category = $5,
    language = $6,
    version = version + 1
WHERE id = $1 AND creator_id = $2 AND version = $7 AND status = 'draft'
RETURNING id, creator_id, slug, statement, context, category, language, status, version, created_at, published_at, closes_at
`

type UpdateArenaDraftParams struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
	Statement string
	Context   pgtype.Text
	Category  string
	Language  string
	Version   int32
}

// UpdateArenaDraft replaces the mutable draft fields under an optimistic
// version check: a stale expected version affects no row (P08-T03).
func (q *Queries) UpdateArenaDraft(ctx context.Context, arg UpdateArenaDraftParams) (AppArena, error) {
	row := q.db.QueryRow(ctx, updateArenaDraft,
		arg.ID,
		arg.CreatorID,
		arg.Statement,
		arg.Context,
		arg.Category,
		arg.Language,
		arg.Version,
	)
	var i AppArena
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Slug,
		&i.Statement,
		&i.Context,
		&i.Category,
		&i.Language,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.ClosesAt,
	)
	return i, err
}
