// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: arguments.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArgument = `-- name: CreateArgument :one
INSERT INTO app.arguments (
    arena_id, author_id, parent_id, relation, content, content_hash,
    grapheme_cost, idempotency_key, created_at, updated_at
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
    $5::text,
    $6::text,
    $7::integer,
    $8::text,
    $9::timestamptz,
    $9::timestamptz
)
ON CONFLICT (author_id, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, arena_id, author_id, parent_id, relation, content, content_hash, grapheme_cost, status, created_at, updated_at
`

type CreateArgumentParams struct {
	ArenaID        pgtype.UUID
	AuthorID       pgtype.UUID
	ParentID       pgtype.UUID
	Relation       string
	Content        string
	ContentHash    string
	GraphemeCost   int32
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
}

type CreateArgumentRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// CreateArgument inserts one argument under the author idempotency key. The
// partial unique index resolves concurrent attempts with the same key: the
// loser gets no row back and resolves the replay (P10-T04).
func (q *Queries) CreateArgument(ctx context.Context, arg CreateArgumentParams) (CreateArgumentRow, error) {
	row := q.db.QueryRow(ctx, createArgument,
		arg.ArenaID,
		arg.AuthorID,
		arg.ParentID,
		arg.Relation,
		arg.Content,
		arg.ContentHash,
		arg.GraphemeCost,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i CreateArgumentRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createArgumentSource = `-- name: CreateArgumentSource :one
INSERT INTO app.argument_sources (argument_id, url, description, created_at)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::timestamptz
)
RETURNING id
`

type CreateArgumentSourceParams struct {
	ArgumentID  pgtype.UUID
	Url         string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// CreateArgumentSource attaches one structured source to an argument.
func (q *Queries) CreateArgumentSource(ctx context.Context, arg CreateArgumentSourceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createArgumentSource,
		arg.ArgumentID,
		arg.Url,
		arg.Description,
		arg.CreatedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getArgumentByAuthorAndKey = `-- name: GetArgumentByAuthorAndKey :one
SELECT id, arena_id, author_id, parent_id, relation, content, content_hash, grapheme_cost, status, created_at, updated_at
FROM app.arguments
WHERE author_id = $1::uuid
  AND idempotency_key = $2::text
`

type GetArgumentByAuthorAndKeyParams struct {
	AuthorID       pgtype.UUID
	IdempotencyKey string
}

type GetArgumentByAuthorAndKeyRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// GetArgumentByAuthorAndKey resolves the argument recorded under one
// attempt key (P10-T04).
func (q *Queries) GetArgumentByAuthorAndKey(ctx context.Context, arg GetArgumentByAuthorAndKeyParams) (GetArgumentByAuthorAndKeyRow, error) {
	row := q.db.QueryRow(ctx, getArgumentByAuthorAndKey, arg.AuthorID, arg.IdempotencyKey)
	var i GetArgumentByAuthorAndKeyRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentArgument = `-- name: GetParentArgument :one
WITH RECURSIVE chain AS (
    SELECT id, parent_id, 0::integer AS depth
    FROM app.arguments
    WHERE id = $1::uuid
    UNION ALL
    SELECT parent.id, parent.parent_id, chain.depth + 1
    FROM app.arguments parent
    JOIN chain ON parent.id = chain.parent_id
    WHERE chain.depth < 1000
)
SELECT
    a.id, a.arena_id, a.author_id, a.parent_id, a.relation, a.content,
    a.content_hash, a.grapheme_cost, a.status, a.created_at, a.updated_at,
    (SELECT max(chain.depth) FROM chain)::integer AS depth
FROM app.arguments a
WHERE a.id = $1::uuid
`

type GetParentArgumentRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Depth        int32
}

// GetParentArgument returns one argument together with its derived depth
// (0 for a top-level argument). Replies walk the chain through the
// recursive CTE, so depth is never denormalized; the depth guard bounds a
// corrupted chain defensively (P10-T05).
func (q *Queries) GetParentArgument(ctx context.Context, argumentID pgtype.UUID) (GetParentArgumentRow, error) {
	row := q.db.QueryRow(ctx, getParentArgument, argumentID)
	var i GetParentArgumentRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Depth,
	)
	return i, err
}
