// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: arguments.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArgument = `-- name: CreateArgument :one
INSERT INTO app.arguments (
    arena_id, author_id, parent_id, relation, content, content_hash,
    grapheme_cost, idempotency_key, created_at, updated_at
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::text,
    $5::text,
    $6::text,
    $7::integer,
    $8::text,
    $9::timestamptz,
    $9::timestamptz
)
ON CONFLICT (author_id, idempotency_key) WHERE idempotency_key IS NOT NULL DO NOTHING
RETURNING id, arena_id, author_id, parent_id, relation, content, content_hash, grapheme_cost, status, created_at, updated_at, withdrawn_at
`

type CreateArgumentParams struct {
	ArenaID        pgtype.UUID
	AuthorID       pgtype.UUID
	ParentID       pgtype.UUID
	Relation       string
	Content        string
	ContentHash    string
	GraphemeCost   int32
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
}

type CreateArgumentRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
}

// CreateArgument inserts one argument under the author idempotency key. The
// partial unique index resolves concurrent attempts with the same key: the
// loser gets no row back and resolves the replay (P10-T04).
func (q *Queries) CreateArgument(ctx context.Context, arg CreateArgumentParams) (CreateArgumentRow, error) {
	row := q.db.QueryRow(ctx, createArgument,
		arg.ArenaID,
		arg.AuthorID,
		arg.ParentID,
		arg.Relation,
		arg.Content,
		arg.ContentHash,
		arg.GraphemeCost,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i CreateArgumentRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const createArgumentSource = `-- name: CreateArgumentSource :one
INSERT INTO app.argument_sources (argument_id, url, description, created_at)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::timestamptz
)
RETURNING id
`

type CreateArgumentSourceParams struct {
	ArgumentID  pgtype.UUID
	Url         string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

// CreateArgumentSource attaches one structured source to an argument.
func (q *Queries) CreateArgumentSource(ctx context.Context, arg CreateArgumentSourceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createArgumentSource,
		arg.ArgumentID,
		arg.Url,
		arg.Description,
		arg.CreatedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getArgumentByAuthorAndKey = `-- name: GetArgumentByAuthorAndKey :one
SELECT id, arena_id, author_id, parent_id, relation, content, content_hash, grapheme_cost, status, created_at, updated_at, withdrawn_at
FROM app.arguments
WHERE author_id = $1::uuid
  AND idempotency_key = $2::text
`

type GetArgumentByAuthorAndKeyParams struct {
	AuthorID       pgtype.UUID
	IdempotencyKey string
}

type GetArgumentByAuthorAndKeyRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
}

// GetArgumentByAuthorAndKey resolves the argument recorded under one
// attempt key (P10-T04).
func (q *Queries) GetArgumentByAuthorAndKey(ctx context.Context, arg GetArgumentByAuthorAndKeyParams) (GetArgumentByAuthorAndKeyRow, error) {
	row := q.db.QueryRow(ctx, getArgumentByAuthorAndKey, arg.AuthorID, arg.IdempotencyKey)
	var i GetArgumentByAuthorAndKeyRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const getArgumentForAuthor = `-- name: GetArgumentForAuthor :one
SELECT id, arena_id, author_id, parent_id, relation, content, content_hash, grapheme_cost, status, created_at, updated_at, withdrawn_at
FROM app.arguments
WHERE id = $1::uuid
  AND author_id = $2::uuid
`

type GetArgumentForAuthorParams struct {
	ArgumentID pgtype.UUID
	AuthorID   pgtype.UUID
}

type GetArgumentForAuthorRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
}

// GetArgumentForAuthor returns one argument scoped to its author. A foreign
// argument is deliberately indistinguishable from a missing one (P10-T06).
func (q *Queries) GetArgumentForAuthor(ctx context.Context, arg GetArgumentForAuthorParams) (GetArgumentForAuthorRow, error) {
	row := q.db.QueryRow(ctx, getArgumentForAuthor, arg.ArgumentID, arg.AuthorID)
	var i GetArgumentForAuthorRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const getParentArgument = `-- name: GetParentArgument :one
WITH RECURSIVE chain AS (
    SELECT id, parent_id, 0::integer AS depth
    FROM app.arguments
    WHERE id = $1::uuid
    UNION ALL
    SELECT parent.id, parent.parent_id, chain.depth + 1
    FROM app.arguments parent
    JOIN chain ON parent.id = chain.parent_id
    WHERE chain.depth < 1000
)
SELECT
    a.id, a.arena_id, a.author_id, a.parent_id, a.relation, a.content,
    a.content_hash, a.grapheme_cost, a.status, a.created_at, a.updated_at, a.withdrawn_at,
    (SELECT max(chain.depth) FROM chain)::integer AS depth
FROM app.arguments a
WHERE a.id = $1::uuid
`

type GetParentArgumentRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
	Depth        int32
}

// GetParentArgument returns one argument together with its derived depth
// (0 for a top-level argument). Replies walk the chain through the
// recursive CTE, so depth is never denormalized; the depth guard bounds a
// corrupted chain defensively (P10-T05).
func (q *Queries) GetParentArgument(ctx context.Context, argumentID pgtype.UUID) (GetParentArgumentRow, error) {
	row := q.db.QueryRow(ctx, getParentArgument, argumentID)
	var i GetParentArgumentRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
		&i.Depth,
	)
	return i, err
}

const getPublicArgument = `-- name: GetPublicArgument :one
SELECT
    a.id, a.arena_id, a.author_id, a.parent_id, a.relation, a.content,
    a.content_hash, a.grapheme_cost, a.status, a.created_at, a.updated_at, a.withdrawn_at,
    (SELECT count(*) FROM app.arguments reply WHERE reply.parent_id = a.id AND reply.status = 'published')::bigint AS reply_count
FROM app.arguments a
WHERE a.id = $1::uuid
  AND a.status IN ('published', 'withdrawn')
`

type GetPublicArgumentRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
	ReplyCount   int64
}

// GetPublicArgument resolves one argument for the public surface: published
// and withdrawn (retracted) arguments resolve; moderation-removed arguments
// are not found (P10-T07).
func (q *Queries) GetPublicArgument(ctx context.Context, argumentID pgtype.UUID) (GetPublicArgumentRow, error) {
	row := q.db.QueryRow(ctx, getPublicArgument, argumentID)
	var i GetPublicArgumentRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
		&i.ReplyCount,
	)
	return i, err
}

const listArenaArgumentsPage = `-- name: ListArenaArgumentsPage :many
SELECT
    a.id, a.arena_id, a.author_id, a.parent_id, a.relation, a.content,
    a.content_hash, a.grapheme_cost, a.status, a.created_at, a.updated_at, a.withdrawn_at,
    (SELECT count(*) FROM app.arguments reply WHERE reply.parent_id = a.id AND reply.status = 'published')::bigint AS reply_count
FROM app.arguments a
WHERE a.arena_id = $1::uuid
  AND a.relation = $2::text
  AND a.parent_id IS NULL
  AND a.status = 'published'
  AND (
      $3::timestamptz IS NULL
      OR (a.created_at, a.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY a.created_at DESC, a.id DESC
LIMIT $5
`

type ListArenaArgumentsPageParams struct {
	ArenaID        pgtype.UUID
	Relation       string
	AfterCreatedAt pgtype.Timestamptz
	AfterID        pgtype.UUID
	PageLimit      int32
}

type ListArenaArgumentsPageRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
	ReplyCount   int64
}

// ListArenaArgumentsPage returns one keyset page of published top-level
// arguments of one relation in one Arena, newest first, with the derived
// published-reply count computed in the same statement (no N+1). Withdrawn
// and removed arguments never appear in public lists (P10-T07).
func (q *Queries) ListArenaArgumentsPage(ctx context.Context, arg ListArenaArgumentsPageParams) ([]ListArenaArgumentsPageRow, error) {
	rows, err := q.db.Query(ctx, listArenaArgumentsPage,
		arg.ArenaID,
		arg.Relation,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenaArgumentsPageRow{}
	for rows.Next() {
		var i ListArenaArgumentsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ArenaID,
			&i.AuthorID,
			&i.ParentID,
			&i.Relation,
			&i.Content,
			&i.ContentHash,
			&i.GraphemeCost,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WithdrawnAt,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepliesPage = `-- name: ListRepliesPage :many
SELECT
    a.id, a.arena_id, a.author_id, a.parent_id, a.relation, a.content,
    a.content_hash, a.grapheme_cost, a.status, a.created_at, a.updated_at, a.withdrawn_at
FROM app.arguments a
WHERE a.parent_id = $1::uuid
  AND a.status = 'published'
  AND (
      $2::timestamptz IS NULL
      OR (a.created_at, a.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY a.created_at DESC, a.id DESC
LIMIT $4
`

type ListRepliesPageParams struct {
	ParentID       pgtype.UUID
	AfterCreatedAt pgtype.Timestamptz
	AfterID        pgtype.UUID
	PageLimit      int32
}

type ListRepliesPageRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
}

// ListRepliesPage returns one keyset page of published replies of one
// parent, newest first. Replies carry no derived reply count: the depth
// policy forbids grandchildren (P10-T05), so the count is always zero and
// the statement stays cheaper.
func (q *Queries) ListRepliesPage(ctx context.Context, arg ListRepliesPageParams) ([]ListRepliesPageRow, error) {
	rows, err := q.db.Query(ctx, listRepliesPage,
		arg.ParentID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepliesPageRow{}
	for rows.Next() {
		var i ListRepliesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ArenaID,
			&i.AuthorID,
			&i.ParentID,
			&i.Relation,
			&i.Content,
			&i.ContentHash,
			&i.GraphemeCost,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawArgument = `-- name: WithdrawArgument :one
UPDATE app.arguments
SET status = 'withdrawn',
    withdrawn_at = COALESCE(withdrawn_at, $1::timestamptz),
    updated_at = $1::timestamptz
WHERE id = $2::uuid
  AND author_id = $3::uuid
  AND status = 'published'
RETURNING id, arena_id, author_id, parent_id, relation, content, content_hash, grapheme_cost, status, created_at, updated_at, withdrawn_at
`

type WithdrawArgumentParams struct {
	WithdrawnAt pgtype.Timestamptz
	ArgumentID  pgtype.UUID
	AuthorID    pgtype.UUID
}

type WithdrawArgumentRow struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AuthorID     pgtype.UUID
	ParentID     pgtype.UUID
	Relation     string
	Content      string
	ContentHash  string
	GraphemeCost int32
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	WithdrawnAt  pgtype.Timestamptz
}

// WithdrawArgument moves a published argument out of the display under the
// author scope, recording the withdrawal instant once. Zero rows mean the
// status moved concurrently: the caller re-reads and resolves (P10-T06).
func (q *Queries) WithdrawArgument(ctx context.Context, arg WithdrawArgumentParams) (WithdrawArgumentRow, error) {
	row := q.db.QueryRow(ctx, withdrawArgument, arg.WithdrawnAt, arg.ArgumentID, arg.AuthorID)
	var i WithdrawArgumentRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AuthorID,
		&i.ParentID,
		&i.Relation,
		&i.Content,
		&i.ContentHash,
		&i.GraphemeCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WithdrawnAt,
	)
	return i, err
}
