// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditEventByIdempotencyKey = `-- name: GetAuditEventByIdempotencyKey :one
SELECT id, occurred_at, actor_id, action, target_type, target_id, reason_code, metadata, idempotency_key, correlation_id
FROM app.audit_events
WHERE idempotency_key = $1
`

func (q *Queries) GetAuditEventByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (AppAuditEvent, error) {
	row := q.db.QueryRow(ctx, getAuditEventByIdempotencyKey, idempotencyKey)
	var i AppAuditEvent
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.ReasonCode,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CorrelationID,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one

INSERT INTO app.audit_events (occurred_at, actor_id, action, target_type, target_id, reason_code, metadata, idempotency_key, correlation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, occurred_at, actor_id, action, target_type, target_id, reason_code, metadata, idempotency_key, correlation_id
`

type InsertAuditEventParams struct {
	OccurredAt     pgtype.Timestamptz
	ActorID        pgtype.UUID
	Action         string
	TargetType     string
	TargetID       string
	ReasonCode     string
	Metadata       []byte
	IdempotencyKey pgtype.Text
	CorrelationID  pgtype.Text
}

// Platform administrative audit trail (P14-T01). The runtime inserts facts
// and reads them back for support and auditors; updates and deletes are
// rejected by triggers for every role, so no query here mutates history.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AppAuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.OccurredAt,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.ReasonCode,
		arg.Metadata,
		arg.IdempotencyKey,
		arg.CorrelationID,
	)
	var i AppAuditEvent
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.ReasonCode,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CorrelationID,
	)
	return i, err
}

const listAuditEventsByTarget = `-- name: ListAuditEventsByTarget :many
SELECT id, occurred_at, actor_id, action, target_type, target_id, reason_code, metadata, idempotency_key, correlation_id
FROM app.audit_events
WHERE target_type = $1 AND target_id = $2
ORDER BY occurred_at ASC, id ASC
`

type ListAuditEventsByTargetParams struct {
	TargetType string
	TargetID   string
}

func (q *Queries) ListAuditEventsByTarget(ctx context.Context, arg ListAuditEventsByTargetParams) ([]AppAuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAuditEvent{}
	for rows.Next() {
		var i AppAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.ReasonCode,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
