// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeArenaPassLot = `-- name: ConsumeArenaPassLot :execrows
UPDATE app.arena_pass_lots
SET remaining_quantity = remaining_quantity - 1
WHERE id = $1 AND remaining_quantity > 0
`

// ConsumeArenaPassLot atomically decrements a lot that still has passes. The
// conditional predicate and the remaining_quantity CHECK together make
// over-consumption impossible, even under concurrent consumers (P07-T03).
func (q *Queries) ConsumeArenaPassLot(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeArenaPassLot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createArenaPassConsumption = `-- name: CreateArenaPassConsumption :one
INSERT INTO app.arena_pass_consumptions (lot_id, arena_id)
VALUES ($1, $2)
RETURNING id, lot_id, arena_id, consumed_at
`

type CreateArenaPassConsumptionParams struct {
	LotID   pgtype.UUID
	ArenaID pgtype.UUID
}

func (q *Queries) CreateArenaPassConsumption(ctx context.Context, arg CreateArenaPassConsumptionParams) (AppArenaPassConsumption, error) {
	row := q.db.QueryRow(ctx, createArenaPassConsumption, arg.LotID, arg.ArenaID)
	var i AppArenaPassConsumption
	err := row.Scan(
		&i.ID,
		&i.LotID,
		&i.ArenaID,
		&i.ConsumedAt,
	)
	return i, err
}

const createArenaPassLot = `-- name: CreateArenaPassLot :one

INSERT INTO app.arena_pass_lots (account_id, origin, quantity, remaining_quantity, expires_at, reference)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
`

type CreateArenaPassLotParams struct {
	AccountID         pgtype.UUID
	Origin            string
	Quantity          int32
	RemainingQuantity int32
	ExpiresAt         pgtype.Timestamptz
	Reference         string
}

// Arena Pass entitlement queries for the PostgreSQL platform adapter.
//
// Consumption is append-only: no query updates or deletes a consumption and
// no query mutates a lot's quantity or expiration. The runtime grants
// enforce the same boundary in the database (P07-T01).
func (q *Queries) CreateArenaPassLot(ctx context.Context, arg CreateArenaPassLotParams) (AppArenaPassLot, error) {
	row := q.db.QueryRow(ctx, createArenaPassLot,
		arg.AccountID,
		arg.Origin,
		arg.Quantity,
		arg.RemainingQuantity,
		arg.ExpiresAt,
		arg.Reference,
	)
	var i AppArenaPassLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Origin,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.ExpiresAt,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const createArenaPassLotIfAbsent = `-- name: CreateArenaPassLotIfAbsent :one
INSERT INTO app.arena_pass_lots (account_id, origin, quantity, remaining_quantity, expires_at, reference)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_id, origin, reference) DO NOTHING
RETURNING id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
`

type CreateArenaPassLotIfAbsentParams struct {
	AccountID         pgtype.UUID
	Origin            string
	Quantity          int32
	RemainingQuantity int32
	ExpiresAt         pgtype.Timestamptz
	Reference         string
}

// CreateArenaPassLotIfAbsent inserts the grant exactly once per
// (account, origin, reference). On a conflict it returns no row, which tells
// the adapter to resolve the original lot (P07-T02).
func (q *Queries) CreateArenaPassLotIfAbsent(ctx context.Context, arg CreateArenaPassLotIfAbsentParams) (AppArenaPassLot, error) {
	row := q.db.QueryRow(ctx, createArenaPassLotIfAbsent,
		arg.AccountID,
		arg.Origin,
		arg.Quantity,
		arg.RemainingQuantity,
		arg.ExpiresAt,
		arg.Reference,
	)
	var i AppArenaPassLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Origin,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.ExpiresAt,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const getArenaPassLot = `-- name: GetArenaPassLot :one
SELECT id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
FROM app.arena_pass_lots
WHERE id = $1
`

func (q *Queries) GetArenaPassLot(ctx context.Context, id pgtype.UUID) (AppArenaPassLot, error) {
	row := q.db.QueryRow(ctx, getArenaPassLot, id)
	var i AppArenaPassLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Origin,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.ExpiresAt,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const getArenaPassLotByGrant = `-- name: GetArenaPassLotByGrant :one
SELECT id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
FROM app.arena_pass_lots
WHERE account_id = $1 AND origin = $2 AND reference = $3
`

type GetArenaPassLotByGrantParams struct {
	AccountID pgtype.UUID
	Origin    string
	Reference string
}

func (q *Queries) GetArenaPassLotByGrant(ctx context.Context, arg GetArenaPassLotByGrantParams) (AppArenaPassLot, error) {
	row := q.db.QueryRow(ctx, getArenaPassLotByGrant, arg.AccountID, arg.Origin, arg.Reference)
	var i AppArenaPassLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Origin,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.ExpiresAt,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const listArenaPassConsumptionsByAccount = `-- name: ListArenaPassConsumptionsByAccount :many
SELECT c.id, c.lot_id, c.arena_id, c.consumed_at, l.origin, l.reference
FROM app.arena_pass_consumptions c
JOIN app.arena_pass_lots l ON l.id = c.lot_id
WHERE l.account_id = $1
ORDER BY c.consumed_at DESC, c.id DESC
`

type ListArenaPassConsumptionsByAccountRow struct {
	ID         pgtype.UUID
	LotID      pgtype.UUID
	ArenaID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
	Origin     string
	Reference  string
}

func (q *Queries) ListArenaPassConsumptionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]ListArenaPassConsumptionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listArenaPassConsumptionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenaPassConsumptionsByAccountRow{}
	for rows.Next() {
		var i ListArenaPassConsumptionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.LotID,
			&i.ArenaID,
			&i.ConsumedAt,
			&i.Origin,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArenaPassLotsByAccount = `-- name: ListArenaPassLotsByAccount :many
SELECT id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
FROM app.arena_pass_lots
WHERE account_id = $1
ORDER BY expires_at NULLS LAST, created_at
`

func (q *Queries) ListArenaPassLotsByAccount(ctx context.Context, accountID pgtype.UUID) ([]AppArenaPassLot, error) {
	rows, err := q.db.Query(ctx, listArenaPassLotsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppArenaPassLot{}
	for rows.Next() {
		var i AppArenaPassLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Origin,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.ExpiresAt,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
