// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeArenaPassLot = `-- name: ConsumeArenaPassLot :execrows
UPDATE app.arena_pass_lots
SET remaining_quantity = remaining_quantity - 1
WHERE id = $1 AND remaining_quantity > 0
`

// ConsumeArenaPassLot atomically decrements a lot that still has passes. The
// conditional predicate and the remaining_quantity CHECK together make
// over-consumption impossible, even under concurrent consumers (P07-T03).
func (q *Queries) ConsumeArenaPassLot(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeArenaPassLot, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createArenaPassConsumption = `-- name: CreateArenaPassConsumption :one
INSERT INTO app.arena_pass_consumptions (lot_id, arena_id)
VALUES ($1, $2)
RETURNING id, lot_id, arena_id, consumed_at
`

type CreateArenaPassConsumptionParams struct {
	LotID   pgtype.UUID
	ArenaID pgtype.UUID
}

func (q *Queries) CreateArenaPassConsumption(ctx context.Context, arg CreateArenaPassConsumptionParams) (AppArenaPassConsumption, error) {
	row := q.db.QueryRow(ctx, createArenaPassConsumption, arg.LotID, arg.ArenaID)
	var i AppArenaPassConsumption
	err := row.Scan(
		&i.ID,
		&i.LotID,
		&i.ArenaID,
		&i.ConsumedAt,
	)
	return i, err
}

const createArenaPassLot = `-- name: CreateArenaPassLot :one

INSERT INTO app.arena_pass_lots (account_id, origin, quantity, remaining_quantity, expires_at, reference)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
`

type CreateArenaPassLotParams struct {
	AccountID         pgtype.UUID
	Origin            string
	Quantity          int32
	RemainingQuantity int32
	ExpiresAt         pgtype.Timestamptz
	Reference         string
}

// Arena Pass entitlement queries for the PostgreSQL platform adapter.
//
// Consumption is append-only: no query updates or deletes a consumption and
// no query mutates a lot's quantity or expiration. The runtime grants
// enforce the same boundary in the database (P07-T01).
func (q *Queries) CreateArenaPassLot(ctx context.Context, arg CreateArenaPassLotParams) (AppArenaPassLot, error) {
	row := q.db.QueryRow(ctx, createArenaPassLot,
		arg.AccountID,
		arg.Origin,
		arg.Quantity,
		arg.RemainingQuantity,
		arg.ExpiresAt,
		arg.Reference,
	)
	var i AppArenaPassLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Origin,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.ExpiresAt,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const createArenaPassLotIfAbsent = `-- name: CreateArenaPassLotIfAbsent :one
INSERT INTO app.arena_pass_lots (account_id, origin, quantity, remaining_quantity, expires_at, reference)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_id, origin, reference) DO NOTHING
RETURNING id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
`

type CreateArenaPassLotIfAbsentParams struct {
	AccountID         pgtype.UUID
	Origin            string
	Quantity          int32
	RemainingQuantity int32
	ExpiresAt         pgtype.Timestamptz
	Reference         string
}

// CreateArenaPassLotIfAbsent inserts the grant exactly once per
// (account, origin, reference). On a conflict it returns no row, which tells
// the adapter to resolve the original lot (P07-T02).
func (q *Queries) CreateArenaPassLotIfAbsent(ctx context.Context, arg CreateArenaPassLotIfAbsentParams) (AppArenaPassLot, error) {
	row := q.db.QueryRow(ctx, createArenaPassLotIfAbsent,
		arg.AccountID,
		arg.Origin,
		arg.Quantity,
		arg.RemainingQuantity,
		arg.ExpiresAt,
		arg.Reference,
	)
	var i AppArenaPassLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Origin,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.ExpiresAt,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const createReconciliationRun = `-- name: CreateReconciliationRun :one

INSERT INTO app.billing_reconciliation_runs (livemode, window_start, window_end, status)
VALUES ($1, $2, $3, 'running')
RETURNING id, livemode, window_start, window_end, status, scanned_objects, findings_count, started_at, finished_at
`

type CreateReconciliationRunParams struct {
	Livemode    bool
	WindowStart pgtype.Timestamptz
	WindowEnd   pgtype.Timestamptz
}

// Reconciliation runs and findings (P12-T10). A run states the window it
// inspected with its counters; every divergence is an immutable finding
// resolved only by a human justification afterwards.
func (q *Queries) CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (AppBillingReconciliationRun, error) {
	row := q.db.QueryRow(ctx, createReconciliationRun, arg.Livemode, arg.WindowStart, arg.WindowEnd)
	var i AppBillingReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.Livemode,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Status,
		&i.ScannedObjects,
		&i.FindingsCount,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishReconciliationRun = `-- name: FinishReconciliationRun :one
UPDATE app.billing_reconciliation_runs
SET status = $2, scanned_objects = $3, findings_count = $4, finished_at = now()
WHERE id = $1
RETURNING id, livemode, window_start, window_end, status, scanned_objects, findings_count, started_at, finished_at
`

type FinishReconciliationRunParams struct {
	ID             pgtype.UUID
	Status         string
	ScannedObjects int32
	FindingsCount  int32
}

func (q *Queries) FinishReconciliationRun(ctx context.Context, arg FinishReconciliationRunParams) (AppBillingReconciliationRun, error) {
	row := q.db.QueryRow(ctx, finishReconciliationRun,
		arg.ID,
		arg.Status,
		arg.ScannedObjects,
		arg.FindingsCount,
	)
	var i AppBillingReconciliationRun
	err := row.Scan(
		&i.ID,
		&i.Livemode,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Status,
		&i.ScannedObjects,
		&i.FindingsCount,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAccountByStripeCustomerID = `-- name: GetAccountByStripeCustomerID :one
SELECT account_id, stripe_customer_id, livemode, created_at
FROM app.stripe_customers
WHERE stripe_customer_id = $1
`

type GetAccountByStripeCustomerIDRow struct {
	AccountID        pgtype.UUID
	StripeCustomerID string
	Livemode         bool
	CreatedAt        pgtype.Timestamptz
}

// Customer correlation lookup (P12-T08).
func (q *Queries) GetAccountByStripeCustomerID(ctx context.Context, stripeCustomerID string) (GetAccountByStripeCustomerIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByStripeCustomerID, stripeCustomerID)
	var i GetAccountByStripeCustomerIDRow
	err := row.Scan(
		&i.AccountID,
		&i.StripeCustomerID,
		&i.Livemode,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSubscriptionByAccount = `-- name: GetActiveSubscriptionByAccount :one
SELECT id, account_id, stripe_subscription_id, status, livemode,
    market, product_id, catalog_version, stripe_price_id,
    current_period_start, current_period_end, cancel_at_period_end, canceled_at,
    created_at, updated_at
FROM app.subscriptions
WHERE account_id = $1
  AND status IN ('active', 'trialing')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByAccount(ctx context.Context, accountID pgtype.UUID) (AppSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionByAccount, accountID)
	var i AppSubscription
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.Livemode,
		&i.Market,
		&i.ProductID,
		&i.CatalogVersion,
		&i.StripePriceID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArenaPassConsumptionByArena = `-- name: GetArenaPassConsumptionByArena :one
SELECT id, lot_id, arena_id, consumed_at
FROM app.arena_pass_consumptions
WHERE arena_id = $1
`

func (q *Queries) GetArenaPassConsumptionByArena(ctx context.Context, arenaID pgtype.UUID) (AppArenaPassConsumption, error) {
	row := q.db.QueryRow(ctx, getArenaPassConsumptionByArena, arenaID)
	var i AppArenaPassConsumption
	err := row.Scan(
		&i.ID,
		&i.LotID,
		&i.ArenaID,
		&i.ConsumedAt,
	)
	return i, err
}

const getArenaPassLot = `-- name: GetArenaPassLot :one
SELECT id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
FROM app.arena_pass_lots
WHERE id = $1
`

func (q *Queries) GetArenaPassLot(ctx context.Context, id pgtype.UUID) (AppArenaPassLot, error) {
	row := q.db.QueryRow(ctx, getArenaPassLot, id)
	var i AppArenaPassLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Origin,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.ExpiresAt,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const getArenaPassLotByGrant = `-- name: GetArenaPassLotByGrant :one
SELECT id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
FROM app.arena_pass_lots
WHERE account_id = $1 AND origin = $2 AND reference = $3
`

type GetArenaPassLotByGrantParams struct {
	AccountID pgtype.UUID
	Origin    string
	Reference string
}

func (q *Queries) GetArenaPassLotByGrant(ctx context.Context, arg GetArenaPassLotByGrantParams) (AppArenaPassLot, error) {
	row := q.db.QueryRow(ctx, getArenaPassLotByGrant, arg.AccountID, arg.Origin, arg.Reference)
	var i AppArenaPassLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Origin,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.ExpiresAt,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingRefundByProviderID = `-- name: GetBillingRefundByProviderID :one
SELECT id, account_id, checkout_intent_id, provider_refund_id, source, status,
    charged_amount_minor, refunded_amount_minor, ink_revoked, passes_revoked,
    needs_review, review_reason, created_at, resolved_at, resolution
FROM app.billing_refunds
WHERE provider_refund_id = $1
`

func (q *Queries) GetBillingRefundByProviderID(ctx context.Context, providerRefundID string) (AppBillingRefund, error) {
	row := q.db.QueryRow(ctx, getBillingRefundByProviderID, providerRefundID)
	var i AppBillingRefund
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CheckoutIntentID,
		&i.ProviderRefundID,
		&i.Source,
		&i.Status,
		&i.ChargedAmountMinor,
		&i.RefundedAmountMinor,
		&i.InkRevoked,
		&i.PassesRevoked,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.Resolution,
	)
	return i, err
}

const getCheckoutIntentBySession = `-- name: GetCheckoutIntentBySession :one
SELECT id, account_id, market, product_id, catalog_version, currency, amount_minor, livemode, status, stripe_checkout_session_id, created_at
FROM app.checkout_intents
WHERE stripe_checkout_session_id = $1
`

type GetCheckoutIntentBySessionRow struct {
	ID                      pgtype.UUID
	AccountID               pgtype.UUID
	Market                  string
	ProductID               string
	CatalogVersion          int32
	Currency                string
	AmountMinor             int64
	Livemode                bool
	Status                  string
	StripeCheckoutSessionID pgtype.Text
	CreatedAt               pgtype.Timestamptz
}

// GetCheckoutIntentBySession resolves the intent a provider session already
// stands for. The session identifier is unique by constraint, which is what
// makes a replay resolve the original intent instead of creating a second one.
func (q *Queries) GetCheckoutIntentBySession(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (GetCheckoutIntentBySessionRow, error) {
	row := q.db.QueryRow(ctx, getCheckoutIntentBySession, stripeCheckoutSessionID)
	var i GetCheckoutIntentBySessionRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Market,
		&i.ProductID,
		&i.CatalogVersion,
		&i.Currency,
		&i.AmountMinor,
		&i.Livemode,
		&i.Status,
		&i.StripeCheckoutSessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getStripeCustomer = `-- name: GetStripeCustomer :one
SELECT account_id, stripe_customer_id, livemode, created_at
FROM app.stripe_customers
WHERE account_id = $1
`

type GetStripeCustomerRow struct {
	AccountID        pgtype.UUID
	StripeCustomerID string
	Livemode         bool
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetStripeCustomer(ctx context.Context, accountID pgtype.UUID) (GetStripeCustomerRow, error) {
	row := q.db.QueryRow(ctx, getStripeCustomer, accountID)
	var i GetStripeCustomerRow
	err := row.Scan(
		&i.AccountID,
		&i.StripeCustomerID,
		&i.Livemode,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByStripeID = `-- name: GetSubscriptionByStripeID :one

SELECT id, account_id, stripe_subscription_id, status, livemode,
    market, product_id, catalog_version, stripe_price_id,
    current_period_start, current_period_end, cancel_at_period_end, canceled_at,
    created_at, updated_at
FROM app.subscriptions
WHERE stripe_subscription_id = $1
`

// Subscription lifecycle queries (P12-T08).
// The subscription mirror persists the provider state and anchors per-period
// Member entitlement grants (30,000 INK and 1 expiring Arena Pass).
func (q *Queries) GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID string) (AppSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeID, stripeSubscriptionID)
	var i AppSubscription
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.Livemode,
		&i.Market,
		&i.ProductID,
		&i.CatalogVersion,
		&i.StripePriceID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEventByEventID = `-- name: GetWebhookEventByEventID :one
SELECT id, stripe_event_id, event_type, livemode, stripe_created_at,
    payload_sha256, payload_bytes, status, attempts, last_error,
    received_at, processed_at
FROM app.stripe_events
WHERE stripe_event_id = $1
`

// GetWebhookEventByEventID resolves an existing event by its provider
// identifier. The event must exist: a conflict without a stored event is an
// integrity problem.
func (q *Queries) GetWebhookEventByEventID(ctx context.Context, stripeEventID string) (AppStripeEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByEventID, stripeEventID)
	var i AppStripeEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Livemode,
		&i.StripeCreatedAt,
		&i.PayloadSha256,
		&i.PayloadBytes,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const insertBillingRefundIfAbsent = `-- name: InsertBillingRefundIfAbsent :one

INSERT INTO app.billing_refunds (
    account_id, checkout_intent_id, provider_refund_id, source, status,
    charged_amount_minor, refunded_amount_minor, ink_revoked, passes_revoked,
    needs_review, review_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (provider_refund_id) DO NOTHING
RETURNING id, account_id, checkout_intent_id, provider_refund_id, source, status,
    charged_amount_minor, refunded_amount_minor, ink_revoked, passes_revoked,
    needs_review, review_reason, created_at, resolved_at, resolution
`

type InsertBillingRefundIfAbsentParams struct {
	AccountID           pgtype.UUID
	CheckoutIntentID    pgtype.UUID
	ProviderRefundID    string
	Source              string
	Status              string
	ChargedAmountMinor  int64
	RefundedAmountMinor int64
	InkRevoked          int64
	PassesRevoked       int32
	NeedsReview         bool
	ReviewReason        pgtype.Text
}

// Refund records (P12-T09). One row per provider refund/dispute object; the
// provider identifier is the idempotency anchor and the commercial facts are
// immutable once written. Only the human resolution may be appended later.
func (q *Queries) InsertBillingRefundIfAbsent(ctx context.Context, arg InsertBillingRefundIfAbsentParams) (AppBillingRefund, error) {
	row := q.db.QueryRow(ctx, insertBillingRefundIfAbsent,
		arg.AccountID,
		arg.CheckoutIntentID,
		arg.ProviderRefundID,
		arg.Source,
		arg.Status,
		arg.ChargedAmountMinor,
		arg.RefundedAmountMinor,
		arg.InkRevoked,
		arg.PassesRevoked,
		arg.NeedsReview,
		arg.ReviewReason,
	)
	var i AppBillingRefund
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CheckoutIntentID,
		&i.ProviderRefundID,
		&i.Source,
		&i.Status,
		&i.ChargedAmountMinor,
		&i.RefundedAmountMinor,
		&i.InkRevoked,
		&i.PassesRevoked,
		&i.NeedsReview,
		&i.ReviewReason,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.Resolution,
	)
	return i, err
}

const insertReconciliationFinding = `-- name: InsertReconciliationFinding :one
INSERT INTO app.billing_reconciliation_findings (run_id, account_id, kind, reference, details)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, account_id, kind, reference, details, observed_at, resolved_at, resolution
`

type InsertReconciliationFindingParams struct {
	RunID     pgtype.UUID
	AccountID pgtype.UUID
	Kind      string
	Reference string
	Details   pgtype.Text
}

func (q *Queries) InsertReconciliationFinding(ctx context.Context, arg InsertReconciliationFindingParams) (AppBillingReconciliationFinding, error) {
	row := q.db.QueryRow(ctx, insertReconciliationFinding,
		arg.RunID,
		arg.AccountID,
		arg.Kind,
		arg.Reference,
		arg.Details,
	)
	var i AppBillingReconciliationFinding
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.AccountID,
		&i.Kind,
		&i.Reference,
		&i.Details,
		&i.ObservedAt,
		&i.ResolvedAt,
		&i.Resolution,
	)
	return i, err
}

const insertWebhookEventIfAbsent = `-- name: InsertWebhookEventIfAbsent :one

INSERT INTO app.stripe_events (
    stripe_event_id, event_type, livemode, stripe_created_at,
    payload_sha256, payload_bytes
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (stripe_event_id) DO NOTHING
RETURNING id, stripe_event_id, event_type, livemode, stripe_created_at,
    payload_sha256, payload_bytes, status, attempts, last_error,
    received_at, processed_at
`

type InsertWebhookEventIfAbsentParams struct {
	StripeEventID   string
	EventType       string
	Livemode        bool
	StripeCreatedAt pgtype.Timestamptz
	PayloadSha256   string
	PayloadBytes    int32
}

// Webhook event queries (P12-T05). The provider's unique event ID is the
// idempotency anchor: a replay resolves the existing row and never creates a
// second one. The processing lifecycle is enforced by CHECK constraints and
// the transition table in the stripe_events_protect_processing trigger.
// InsertWebhookEventIfAbsent persists the verified inbound event exactly once
// per provider event ID. On conflict (the unique stripe_event_id), it returns
// no row, which tells the adapter to resolve the existing event.
func (q *Queries) InsertWebhookEventIfAbsent(ctx context.Context, arg InsertWebhookEventIfAbsentParams) (AppStripeEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEventIfAbsent,
		arg.StripeEventID,
		arg.EventType,
		arg.Livemode,
		arg.StripeCreatedAt,
		arg.PayloadSha256,
		arg.PayloadBytes,
	)
	var i AppStripeEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Livemode,
		&i.StripeCreatedAt,
		&i.PayloadSha256,
		&i.PayloadBytes,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const isAccountEligibleForPurchase = `-- name: IsAccountEligibleForPurchase :one

SELECT (status = 'active' AND email_verified_at IS NOT NULL) AS eligible
FROM app.accounts
WHERE id = $1
`

// Checkout queries (P12-T04). The commercial decision of an intent is
// resolved by the server from the versioned catalog and is immutable once
// written; these queries insert it and resolve replays, never recompute it.
// IsAccountEligibleForPurchase projects the single bit the checkout needs
// before it decides to charge anyone: the account exists, is active and has a
// verified email (docs/BUSINESS_RULES.md §7, REQ-AUTH-02). It reads no email,
// no credential and no payment identifier, so an ineligible or forged
// identifier can never be mistaken for a legitimate buyer. A missing row means
// the account does not exist at all.
func (q *Queries) IsAccountEligibleForPurchase(ctx context.Context, id pgtype.UUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isAccountEligibleForPurchase, id)
	var eligible pgtype.Bool
	err := row.Scan(&eligible)
	return eligible, err
}

const listArenaPassConsumptionsByAccount = `-- name: ListArenaPassConsumptionsByAccount :many
SELECT c.id, c.lot_id, c.arena_id, c.consumed_at, l.origin, l.reference
FROM app.arena_pass_consumptions c
JOIN app.arena_pass_lots l ON l.id = c.lot_id
WHERE l.account_id = $1
ORDER BY c.consumed_at DESC, c.id DESC
`

type ListArenaPassConsumptionsByAccountRow struct {
	ID         pgtype.UUID
	LotID      pgtype.UUID
	ArenaID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
	Origin     string
	Reference  string
}

func (q *Queries) ListArenaPassConsumptionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]ListArenaPassConsumptionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listArenaPassConsumptionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenaPassConsumptionsByAccountRow{}
	for rows.Next() {
		var i ListArenaPassConsumptionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.LotID,
			&i.ArenaID,
			&i.ConsumedAt,
			&i.Origin,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArenaPassConsumptionsPage = `-- name: ListArenaPassConsumptionsPage :many
SELECT c.id, c.lot_id, c.arena_id, c.consumed_at, l.origin, l.reference
FROM app.arena_pass_consumptions c
JOIN app.arena_pass_lots l ON l.id = c.lot_id
WHERE l.account_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (c.consumed_at, c.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY c.consumed_at DESC, c.id DESC
LIMIT $4
`

type ListArenaPassConsumptionsPageParams struct {
	AccountID       pgtype.UUID
	AfterConsumedAt pgtype.Timestamptz
	AfterID         pgtype.UUID
	PageLimit       int32
}

type ListArenaPassConsumptionsPageRow struct {
	ID         pgtype.UUID
	LotID      pgtype.UUID
	ArenaID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
	Origin     string
	Reference  string
}

// ListArenaPassConsumptionsPage returns one keyset-paginated page of the
// owner's consumption history, newest first. NULL after_* parameters select
// the first page; the (consumed_at, id) tuple comparison never duplicates or
// skips rows (P07-T06).
func (q *Queries) ListArenaPassConsumptionsPage(ctx context.Context, arg ListArenaPassConsumptionsPageParams) ([]ListArenaPassConsumptionsPageRow, error) {
	rows, err := q.db.Query(ctx, listArenaPassConsumptionsPage,
		arg.AccountID,
		arg.AfterConsumedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArenaPassConsumptionsPageRow{}
	for rows.Next() {
		var i ListArenaPassConsumptionsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.LotID,
			&i.ArenaID,
			&i.ConsumedAt,
			&i.Origin,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArenaPassLotsByAccount = `-- name: ListArenaPassLotsByAccount :many
SELECT id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
FROM app.arena_pass_lots
WHERE account_id = $1
ORDER BY expires_at NULLS LAST, created_at
`

func (q *Queries) ListArenaPassLotsByAccount(ctx context.Context, accountID pgtype.UUID) ([]AppArenaPassLot, error) {
	rows, err := q.db.Query(ctx, listArenaPassLotsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppArenaPassLot{}
	for rows.Next() {
		var i AppArenaPassLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Origin,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.ExpiresAt,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailablePassLotsForUpdate = `-- name: ListAvailablePassLotsForUpdate :many
SELECT id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
FROM app.arena_pass_lots
WHERE account_id = $1
  AND remaining_quantity > 0
  AND (expires_at IS NULL OR expires_at > $2::timestamptz)
ORDER BY expires_at ASC NULLS LAST, created_at ASC
FOR UPDATE
`

type ListAvailablePassLotsForUpdateParams struct {
	AccountID pgtype.UUID
	At        pgtype.Timestamptz
}

// ListAvailablePassLotsForUpdate locks the consumable lots of an account in
// consumption order: nearest expiration first, then lots that never expire.
// Expired lots are never candidates, so they can never be consumed (P07-T03).
func (q *Queries) ListAvailablePassLotsForUpdate(ctx context.Context, arg ListAvailablePassLotsForUpdateParams) ([]AppArenaPassLot, error) {
	rows, err := q.db.Query(ctx, listAvailablePassLotsForUpdate, arg.AccountID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppArenaPassLot{}
	for rows.Next() {
		var i AppArenaPassLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Origin,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.ExpiresAt,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingRefundsByIntent = `-- name: ListBillingRefundsByIntent :many
SELECT id, account_id, checkout_intent_id, provider_refund_id, source, status,
    charged_amount_minor, refunded_amount_minor, ink_revoked, passes_revoked,
    needs_review, review_reason, created_at, resolved_at, resolution
FROM app.billing_refunds
WHERE checkout_intent_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListBillingRefundsByIntent(ctx context.Context, checkoutIntentID pgtype.UUID) ([]AppBillingRefund, error) {
	rows, err := q.db.Query(ctx, listBillingRefundsByIntent, checkoutIntentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppBillingRefund{}
	for rows.Next() {
		var i AppBillingRefund
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CheckoutIntentID,
			&i.ProviderRefundID,
			&i.Source,
			&i.Status,
			&i.ChargedAmountMinor,
			&i.RefundedAmountMinor,
			&i.InkRevoked,
			&i.PassesRevoked,
			&i.NeedsReview,
			&i.ReviewReason,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.Resolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckoutIntentsForReconciliation = `-- name: ListCheckoutIntentsForReconciliation :many

SELECT id, account_id, market, product_id, catalog_version, currency, amount_minor, livemode, status, stripe_checkout_session_id, created_at
FROM app.checkout_intents
WHERE created_at >= $1 AND created_at < $2 AND livemode = $3
ORDER BY created_at ASC, id ASC
`

type ListCheckoutIntentsForReconciliationParams struct {
	CreatedAt   pgtype.Timestamptz
	CreatedAt_2 pgtype.Timestamptz
	Livemode    bool
}

type ListCheckoutIntentsForReconciliationRow struct {
	ID                      pgtype.UUID
	AccountID               pgtype.UUID
	Market                  string
	ProductID               string
	CatalogVersion          int32
	Currency                string
	AmountMinor             int64
	Livemode                bool
	Status                  string
	StripeCheckoutSessionID pgtype.Text
	CreatedAt               pgtype.Timestamptz
}

// Reconciliation window reads (P12-T10). The job compares the local mirrors
// created in the window against the provider and records findings without
// correcting anything: these selects are the only local input, ordered
// deterministically so runs are reproducible.
func (q *Queries) ListCheckoutIntentsForReconciliation(ctx context.Context, arg ListCheckoutIntentsForReconciliationParams) ([]ListCheckoutIntentsForReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listCheckoutIntentsForReconciliation, arg.CreatedAt, arg.CreatedAt_2, arg.Livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckoutIntentsForReconciliationRow{}
	for rows.Next() {
		var i ListCheckoutIntentsForReconciliationRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Market,
			&i.ProductID,
			&i.CatalogVersion,
			&i.Currency,
			&i.AmountMinor,
			&i.Livemode,
			&i.Status,
			&i.StripeCheckoutSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredArenaPassLots = `-- name: ListExpiredArenaPassLots :many
SELECT id, account_id, origin, quantity, remaining_quantity, expires_at, reference, created_at
FROM app.arena_pass_lots
WHERE expires_at IS NOT NULL
  AND expires_at <= $1::timestamptz
  AND remaining_quantity > 0
ORDER BY expires_at ASC, id ASC
LIMIT $2
`

type ListExpiredArenaPassLotsParams struct {
	At        pgtype.Timestamptz
	PageLimit int32
}

// ListExpiredArenaPassLots derives the expired lots that still hold passes.
// Expiration is never written back: the predicate is evaluated at read time,
// so the sweep is a pure derivation and repeated runs are identical (P07-T04).
func (q *Queries) ListExpiredArenaPassLots(ctx context.Context, arg ListExpiredArenaPassLotsParams) ([]AppArenaPassLot, error) {
	rows, err := q.db.Query(ctx, listExpiredArenaPassLots, arg.At, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppArenaPassLot{}
	for rows.Next() {
		var i AppArenaPassLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Origin,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.ExpiresAt,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationFindingsByRun = `-- name: ListReconciliationFindingsByRun :many
SELECT id, run_id, account_id, kind, reference, details, observed_at, resolved_at, resolution
FROM app.billing_reconciliation_findings
WHERE run_id = $1
ORDER BY observed_at ASC, id ASC
`

func (q *Queries) ListReconciliationFindingsByRun(ctx context.Context, runID pgtype.UUID) ([]AppBillingReconciliationFinding, error) {
	rows, err := q.db.Query(ctx, listReconciliationFindingsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppBillingReconciliationFinding{}
	for rows.Next() {
		var i AppBillingReconciliationFinding
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.AccountID,
			&i.Kind,
			&i.Reference,
			&i.Details,
			&i.ObservedAt,
			&i.ResolvedAt,
			&i.Resolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForReconciliation = `-- name: ListSubscriptionsForReconciliation :many
SELECT id, account_id, stripe_subscription_id, status, livemode,
    market, product_id, catalog_version, stripe_price_id,
    current_period_start, current_period_end, cancel_at_period_end, canceled_at,
    created_at, updated_at
FROM app.subscriptions
WHERE updated_at >= $1 AND updated_at < $2 AND livemode = $3
ORDER BY updated_at ASC, id ASC
`

type ListSubscriptionsForReconciliationParams struct {
	UpdatedAt   pgtype.Timestamptz
	UpdatedAt_2 pgtype.Timestamptz
	Livemode    bool
}

func (q *Queries) ListSubscriptionsForReconciliation(ctx context.Context, arg ListSubscriptionsForReconciliationParams) ([]AppSubscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForReconciliation, arg.UpdatedAt, arg.UpdatedAt_2, arg.Livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSubscription{}
	for rows.Next() {
		var i AppSubscription
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StripeSubscriptionID,
			&i.Status,
			&i.Livemode,
			&i.Market,
			&i.ProductID,
			&i.CatalogVersion,
			&i.StripePriceID,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtPeriodEnd,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedStripeEvents = `-- name: ListUnprocessedStripeEvents :many
SELECT id, stripe_event_id, event_type, livemode, stripe_created_at,
    payload_sha256, payload_bytes, status, attempts, last_error,
    received_at, processed_at
FROM app.stripe_events
WHERE stripe_created_at >= $1 AND stripe_created_at < $2 AND livemode = $3
  AND status IN ('received', 'processing', 'failed')
ORDER BY stripe_created_at ASC, id ASC
`

type ListUnprocessedStripeEventsParams struct {
	StripeCreatedAt   pgtype.Timestamptz
	StripeCreatedAt_2 pgtype.Timestamptz
	Livemode          bool
}

func (q *Queries) ListUnprocessedStripeEvents(ctx context.Context, arg ListUnprocessedStripeEventsParams) ([]AppStripeEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedStripeEvents, arg.StripeCreatedAt, arg.StripeCreatedAt_2, arg.Livemode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppStripeEvent{}
	for rows.Next() {
		var i AppStripeEvent
		if err := rows.Scan(
			&i.ID,
			&i.StripeEventID,
			&i.EventType,
			&i.Livemode,
			&i.StripeCreatedAt,
			&i.PayloadSha256,
			&i.PayloadBytes,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckoutIntentPaid = `-- name: MarkCheckoutIntentPaid :exec
UPDATE app.checkout_intents
SET status = 'paid', paid_at = now(), updated_at = now()
WHERE stripe_checkout_session_id = $1 AND status = 'open'
`

// MarkCheckoutIntentPaid transitions the intent to the paid terminal state
// and records the settlement instant. The CHECK constraint ensures that
// paid_at is non-null exactly when status is paid. The trigger allows
// open → paid only once.
func (q *Queries) MarkCheckoutIntentPaid(ctx context.Context, stripeCheckoutSessionID pgtype.Text) error {
	_, err := q.db.Exec(ctx, markCheckoutIntentPaid, stripeCheckoutSessionID)
	return err
}

const recordCheckoutIntentIfAbsent = `-- name: RecordCheckoutIntentIfAbsent :one
INSERT INTO app.checkout_intents (
    account_id, market, product_id, catalog_version, currency, amount_minor,
    livemode, status, stripe_checkout_session_id, closed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (stripe_checkout_session_id) DO NOTHING
RETURNING id, account_id, market, product_id, catalog_version, currency, amount_minor, livemode, status, stripe_checkout_session_id, created_at
`

type RecordCheckoutIntentIfAbsentParams struct {
	AccountID               pgtype.UUID
	Market                  string
	ProductID               string
	CatalogVersion          int32
	Currency                string
	AmountMinor             int64
	Livemode                bool
	Status                  string
	StripeCheckoutSessionID pgtype.Text
	ClosedAt                pgtype.Timestamptz
}

type RecordCheckoutIntentIfAbsentRow struct {
	ID                      pgtype.UUID
	AccountID               pgtype.UUID
	Market                  string
	ProductID               string
	CatalogVersion          int32
	Currency                string
	AmountMinor             int64
	Livemode                bool
	Status                  string
	StripeCheckoutSessionID pgtype.Text
	CreatedAt               pgtype.Timestamptz
}

// RecordCheckoutIntentIfAbsent inserts the commercial decision exactly once per
// provider session, so a replay of the same operation resolves the stored
// intent. The lifecycle CHECK is what keeps the recorded state honest: an open
// intent has a session, an expired one is closed at a known instant.
func (q *Queries) RecordCheckoutIntentIfAbsent(ctx context.Context, arg RecordCheckoutIntentIfAbsentParams) (RecordCheckoutIntentIfAbsentRow, error) {
	row := q.db.QueryRow(ctx, recordCheckoutIntentIfAbsent,
		arg.AccountID,
		arg.Market,
		arg.ProductID,
		arg.CatalogVersion,
		arg.Currency,
		arg.AmountMinor,
		arg.Livemode,
		arg.Status,
		arg.StripeCheckoutSessionID,
		arg.ClosedAt,
	)
	var i RecordCheckoutIntentIfAbsentRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Market,
		&i.ProductID,
		&i.CatalogVersion,
		&i.Currency,
		&i.AmountMinor,
		&i.Livemode,
		&i.Status,
		&i.StripeCheckoutSessionID,
		&i.CreatedAt,
	)
	return i, err
}

const recordStripeCustomerIfAbsent = `-- name: RecordStripeCustomerIfAbsent :one
INSERT INTO app.stripe_customers (account_id, stripe_customer_id, livemode)
VALUES ($1, $2, $3)
ON CONFLICT (account_id) DO NOTHING
RETURNING account_id, stripe_customer_id, livemode, created_at
`

type RecordStripeCustomerIfAbsentParams struct {
	AccountID        pgtype.UUID
	StripeCustomerID string
	Livemode         bool
}

type RecordStripeCustomerIfAbsentRow struct {
	AccountID        pgtype.UUID
	StripeCustomerID string
	Livemode         bool
	CreatedAt        pgtype.Timestamptz
}

// RecordStripeCustomerIfAbsent stores the account→customer correlation exactly
// once per account: a concurrent or retried insertion writes nothing and
// resolves the stored mapping, so the account is never charged through two
// different provider customers.
func (q *Queries) RecordStripeCustomerIfAbsent(ctx context.Context, arg RecordStripeCustomerIfAbsentParams) (RecordStripeCustomerIfAbsentRow, error) {
	row := q.db.QueryRow(ctx, recordStripeCustomerIfAbsent, arg.AccountID, arg.StripeCustomerID, arg.Livemode)
	var i RecordStripeCustomerIfAbsentRow
	err := row.Scan(
		&i.AccountID,
		&i.StripeCustomerID,
		&i.Livemode,
		&i.CreatedAt,
	)
	return i, err
}

const updateWebhookEventStatus = `-- name: UpdateWebhookEventStatus :one
UPDATE app.stripe_events
SET status = $2, attempts = attempts + 1
WHERE stripe_event_id = $1
RETURNING id, stripe_event_id, event_type, livemode, stripe_created_at,
    payload_sha256, payload_bytes, status, attempts, last_error,
    received_at, processed_at
`

type UpdateWebhookEventStatusParams struct {
	StripeEventID string
	Status        string
}

// UpdateWebhookEventStatus transitions the event to the requested status. The
// CHECK constraint stripe_events_status_transition enforces legal transitions,
// so an illegal transition is a database error.
func (q *Queries) UpdateWebhookEventStatus(ctx context.Context, arg UpdateWebhookEventStatusParams) (AppStripeEvent, error) {
	row := q.db.QueryRow(ctx, updateWebhookEventStatus, arg.StripeEventID, arg.Status)
	var i AppStripeEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Livemode,
		&i.StripeCreatedAt,
		&i.PayloadSha256,
		&i.PayloadBytes,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const updateWebhookEventStatusFailed = `-- name: UpdateWebhookEventStatusFailed :one
UPDATE app.stripe_events
SET status = $2, last_error = $3
WHERE stripe_event_id = $1
RETURNING id, stripe_event_id, event_type, livemode, stripe_created_at,
    payload_sha256, payload_bytes, status, attempts, last_error,
    received_at, processed_at
`

type UpdateWebhookEventStatusFailedParams struct {
	StripeEventID string
	Status        string
	LastError     pgtype.Text
}

// UpdateWebhookEventStatusFailed transitions the event to the failed state
// with a bounded error reason. The event may be retried later.
func (q *Queries) UpdateWebhookEventStatusFailed(ctx context.Context, arg UpdateWebhookEventStatusFailedParams) (AppStripeEvent, error) {
	row := q.db.QueryRow(ctx, updateWebhookEventStatusFailed, arg.StripeEventID, arg.Status, arg.LastError)
	var i AppStripeEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Livemode,
		&i.StripeCreatedAt,
		&i.PayloadSha256,
		&i.PayloadBytes,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const updateWebhookEventStatusIgnored = `-- name: UpdateWebhookEventStatusIgnored :one
UPDATE app.stripe_events
SET status = $2, processed_at = $3, last_error = NULL
WHERE stripe_event_id = $1
RETURNING id, stripe_event_id, event_type, livemode, stripe_created_at,
    payload_sha256, payload_bytes, status, attempts, last_error,
    received_at, processed_at
`

type UpdateWebhookEventStatusIgnoredParams struct {
	StripeEventID string
	Status        string
	ProcessedAt   pgtype.Timestamptz
}

// UpdateWebhookEventStatusIgnored transitions the event to the ignored
// terminal state for event types that are acknowledged but not handled.
func (q *Queries) UpdateWebhookEventStatusIgnored(ctx context.Context, arg UpdateWebhookEventStatusIgnoredParams) (AppStripeEvent, error) {
	row := q.db.QueryRow(ctx, updateWebhookEventStatusIgnored, arg.StripeEventID, arg.Status, arg.ProcessedAt)
	var i AppStripeEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Livemode,
		&i.StripeCreatedAt,
		&i.PayloadSha256,
		&i.PayloadBytes,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const updateWebhookEventStatusProcessed = `-- name: UpdateWebhookEventStatusProcessed :one
UPDATE app.stripe_events
SET status = $2, processed_at = $3, last_error = NULL
WHERE stripe_event_id = $1
RETURNING id, stripe_event_id, event_type, livemode, stripe_created_at,
    payload_sha256, payload_bytes, status, attempts, last_error,
    received_at, processed_at
`

type UpdateWebhookEventStatusProcessedParams struct {
	StripeEventID string
	Status        string
	ProcessedAt   pgtype.Timestamptz
}

// UpdateWebhookEventStatusProcessed transitions the event to the processed
// terminal state and records the processing completion time.
func (q *Queries) UpdateWebhookEventStatusProcessed(ctx context.Context, arg UpdateWebhookEventStatusProcessedParams) (AppStripeEvent, error) {
	row := q.db.QueryRow(ctx, updateWebhookEventStatusProcessed, arg.StripeEventID, arg.Status, arg.ProcessedAt)
	var i AppStripeEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Livemode,
		&i.StripeCreatedAt,
		&i.PayloadSha256,
		&i.PayloadBytes,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO app.subscriptions (
    account_id, stripe_subscription_id, status, livemode,
    market, product_id, catalog_version, stripe_price_id,
    current_period_start, current_period_end, cancel_at_period_end, canceled_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (stripe_subscription_id) DO UPDATE
SET status = EXCLUDED.status,
    market = EXCLUDED.market,
    product_id = EXCLUDED.product_id,
    catalog_version = EXCLUDED.catalog_version,
    stripe_price_id = EXCLUDED.stripe_price_id,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    canceled_at = EXCLUDED.canceled_at,
    updated_at = now()
RETURNING id, account_id, stripe_subscription_id, status, livemode,
    market, product_id, catalog_version, stripe_price_id,
    current_period_start, current_period_end, cancel_at_period_end, canceled_at,
    created_at, updated_at
`

type UpsertSubscriptionParams struct {
	AccountID            pgtype.UUID
	StripeSubscriptionID string
	Status               string
	Livemode             bool
	Market               string
	ProductID            string
	CatalogVersion       int32
	StripePriceID        string
	CurrentPeriodStart   pgtype.Timestamptz
	CurrentPeriodEnd     pgtype.Timestamptz
	CancelAtPeriodEnd    bool
	CanceledAt           pgtype.Timestamptz
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (AppSubscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.AccountID,
		arg.StripeSubscriptionID,
		arg.Status,
		arg.Livemode,
		arg.Market,
		arg.ProductID,
		arg.CatalogVersion,
		arg.StripePriceID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.CanceledAt,
	)
	var i AppSubscription
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.Livemode,
		&i.Market,
		&i.ProductID,
		&i.CatalogVersion,
		&i.StripePriceID,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const zeroPassLotRemaining = `-- name: ZeroPassLotRemaining :execrows
UPDATE app.arena_pass_lots
SET remaining_quantity = 0
WHERE id = $1 AND remaining_quantity > 0
`

// ZeroPassLotRemaining revokes every remaining pass of one lot without
// deleting history: consumption rows stay, only the remaining projection is
// zeroed. It reports how many rows were actually revoked.
func (q *Queries) ZeroPassLotRemaining(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, zeroPassLotRemaining, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
