// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: health.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHealthMetadata = `-- name: GetHealthMetadata :one

SELECT version_id, is_applied, tstamp
FROM app.schema_metadata
ORDER BY version_id DESC
LIMIT 1
`

type GetHealthMetadataRow struct {
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

// Health metadata and connectivity queries for the PostgreSQL platform adapter.
// GetHealthMetadata retrieves the latest applied migration metadata from app.schema_metadata.
func (q *Queries) GetHealthMetadata(ctx context.Context) (GetHealthMetadataRow, error) {
	row := q.db.QueryRow(ctx, getHealthMetadata)
	var i GetHealthMetadataRow
	err := row.Scan(&i.VersionID, &i.IsApplied, &i.Tstamp)
	return i, err
}

const pingHealth = `-- name: PingHealth :one
SELECT 1 AS ready
`

// PingHealth executes a trivial query (SELECT 1) to verify connection readiness.
func (q *Queries) PingHealth(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, pingHealth)
	var ready int32
	err := row.Scan(&ready)
	return ready, err
}
