// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identity.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO app.accounts (email, status)
VALUES ($1, $2)
RETURNING id, email, status, email_verified_at, created_at, updated_at
`

type CreateAccountParams struct {
	Email  string
	Status string
}

// Identity and authentication queries for the PostgreSQL platform adapter.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (AppAccount, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Email, arg.Status)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO app.email_verification_tokens (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (AppEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i AppEmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordCredential = `-- name: CreatePasswordCredential :exec
INSERT INTO app.password_credentials (account_id, password_hash, algorithm, version)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordCredentialParams struct {
	AccountID    pgtype.UUID
	PasswordHash string
	Algorithm    string
	Version      int32
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, createPasswordCredential,
		arg.AccountID,
		arg.PasswordHash,
		arg.Algorithm,
		arg.Version,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO app.password_reset_tokens (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (AppPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i AppPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO app.sessions (account_id, token_hash, expires_at, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, token_hash, created_at, expires_at, last_seen_at, revoked_at, ip_address, user_agent
`

type CreateSessionParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM app.sessions
WHERE expires_at < now() OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, status, email_verified_at, created_at, updated_at
FROM app.accounts
WHERE lower(email) = lower($1)
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (AppAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, status, email_verified_at, created_at, updated_at
FROM app.accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (AppAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountProfile = `-- name: GetAccountProfile :one
SELECT id, email, status, email_verified_at, created_at, updated_at
FROM app.accounts
WHERE id = $1
`

// GetAccountProfile retrieves account profile data without ever reading or exposing password credentials.
func (q *Queries) GetAccountProfile(ctx context.Context, id pgtype.UUID) (AppAccount, error) {
	row := q.db.QueryRow(ctx, getAccountProfile, id)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveEmailVerificationToken = `-- name: GetActiveEmailVerificationToken :one
SELECT id, account_id, token_hash, expires_at, used_at, created_at
FROM app.email_verification_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActiveEmailVerificationToken(ctx context.Context, tokenHash []byte) (AppEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getActiveEmailVerificationToken, tokenHash)
	var i AppEmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePasswordResetToken = `-- name: GetActivePasswordResetToken :one
SELECT id, account_id, token_hash, expires_at, used_at, created_at
FROM app.password_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActivePasswordResetToken(ctx context.Context, tokenHash []byte) (AppPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getActivePasswordResetToken, tokenHash)
	var i AppPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, account_id, token_hash, created_at, expires_at, last_seen_at, revoked_at, ip_address, user_agent
FROM app.sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (AppSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const getPasswordCredentialByAccountID = `-- name: GetPasswordCredentialByAccountID :one
SELECT account_id, password_hash, algorithm, version, created_at, updated_at
FROM app.password_credentials
WHERE account_id = $1
`

func (q *Queries) GetPasswordCredentialByAccountID(ctx context.Context, accountID pgtype.UUID) (AppPasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByAccountID, accountID)
	var i AppPasswordCredential
	err := row.Scan(
		&i.AccountID,
		&i.PasswordHash,
		&i.Algorithm,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :exec
UPDATE app.email_verification_tokens
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, id)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE app.password_reset_tokens
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	return err
}

const revokeAllAccountSessions = `-- name: RevokeAllAccountSessions :exec
UPDATE app.sessions
SET revoked_at = now()
WHERE account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAccountSessions(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAccountSessions, accountID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE app.sessions
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :one
UPDATE app.accounts
SET status = 'active', email_verified_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, email, status, email_verified_at, created_at, updated_at
`

func (q *Queries) SetEmailVerified(ctx context.Context, id pgtype.UUID) (AppAccount, error) {
	row := q.db.QueryRow(ctx, setEmailVerified, id)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE app.accounts
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, status, email_verified_at, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (AppAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordCredential = `-- name: UpdatePasswordCredential :exec
UPDATE app.password_credentials
SET password_hash = $2, algorithm = $3, version = $4, updated_at = now()
WHERE account_id = $1
`

type UpdatePasswordCredentialParams struct {
	AccountID    pgtype.UUID
	PasswordHash string
	Algorithm    string
	Version      int32
}

func (q *Queries) UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, updatePasswordCredential,
		arg.AccountID,
		arg.PasswordHash,
		arg.Algorithm,
		arg.Version,
	)
	return err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE app.sessions
SET last_seen_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}
