// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: identity.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO app.accounts (email, status)
VALUES ($1, $2)
RETURNING id, email, status, email_verified_at, created_at, updated_at
`

type CreateAccountParams struct {
	Email  string
	Status string
}

// Identity and authentication queries for the PostgreSQL platform adapter.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (AppAccount, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Email, arg.Status)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO app.email_verification_tokens (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (AppEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i AppEmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordCredential = `-- name: CreatePasswordCredential :exec
INSERT INTO app.password_credentials (account_id, password_hash, algorithm, version)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordCredentialParams struct {
	AccountID    pgtype.UUID
	PasswordHash string
	Algorithm    string
	Version      int32
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, createPasswordCredential,
		arg.AccountID,
		arg.PasswordHash,
		arg.Algorithm,
		arg.Version,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO app.password_reset_tokens (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (AppPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i AppPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO app.sessions (account_id, token_hash, expires_at, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, token_hash, created_at, expires_at, last_seen_at, revoked_at, ip_address, user_agent, mfa_verified_at
`

type CreateSessionParams struct {
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.MfaVerifiedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM app.sessions
WHERE expires_at < now() OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, status, email_verified_at, created_at, updated_at
FROM app.accounts
WHERE lower(email) = lower($1)
`

func (q *Queries) GetAccountByEmail(ctx context.Context, lower string) (AppAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, lower)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, status, email_verified_at, created_at, updated_at
FROM app.accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (AppAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountProfile = `-- name: GetAccountProfile :one
SELECT id, email, status, email_verified_at, created_at, updated_at
FROM app.accounts
WHERE id = $1
`

// GetAccountProfile retrieves account profile data without ever reading or exposing password credentials.
func (q *Queries) GetAccountProfile(ctx context.Context, id pgtype.UUID) (AppAccount, error) {
	row := q.db.QueryRow(ctx, getAccountProfile, id)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveEmailVerificationToken = `-- name: GetActiveEmailVerificationToken :one
SELECT id, account_id, token_hash, expires_at, used_at, created_at
FROM app.email_verification_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActiveEmailVerificationToken(ctx context.Context, tokenHash []byte) (AppEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getActiveEmailVerificationToken, tokenHash)
	var i AppEmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePasswordResetToken = `-- name: GetActivePasswordResetToken :one
SELECT id, account_id, token_hash, expires_at, used_at, created_at
FROM app.password_reset_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActivePasswordResetToken(ctx context.Context, tokenHash []byte) (AppPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getActivePasswordResetToken, tokenHash)
	var i AppPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, account_id, token_hash, created_at, expires_at, last_seen_at, revoked_at, ip_address, user_agent, mfa_verified_at
FROM app.sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (AppSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.MfaVerifiedAt,
	)
	return i, err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT id, account_id, token_hash, expires_at, used_at, created_at
FROM app.email_verification_tokens
WHERE token_hash = $1
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash []byte) (AppEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i AppEmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordCredentialByAccountID = `-- name: GetPasswordCredentialByAccountID :one
SELECT account_id, password_hash, algorithm, version, created_at, updated_at
FROM app.password_credentials
WHERE account_id = $1
`

func (q *Queries) GetPasswordCredentialByAccountID(ctx context.Context, accountID pgtype.UUID) (AppPasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByAccountID, accountID)
	var i AppPasswordCredential
	err := row.Scan(
		&i.AccountID,
		&i.PasswordHash,
		&i.Algorithm,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, account_id, token_hash, expires_at, used_at, created_at
FROM app.password_reset_tokens
WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (AppPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i AppPasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, account_id, token_hash, created_at, expires_at, last_seen_at, revoked_at, ip_address, user_agent, mfa_verified_at
FROM app.sessions
WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (AppSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.MfaVerifiedAt,
	)
	return i, err
}

const invalidateActiveEmailVerificationTokens = `-- name: InvalidateActiveEmailVerificationTokens :exec
UPDATE app.email_verification_tokens
SET used_at = now()
WHERE account_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateActiveEmailVerificationTokens(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateActiveEmailVerificationTokens, accountID)
	return err
}

const invalidateActivePasswordResetTokens = `-- name: InvalidateActivePasswordResetTokens :exec
UPDATE app.password_reset_tokens
SET used_at = now()
WHERE account_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidateActivePasswordResetTokens(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateActivePasswordResetTokens, accountID)
	return err
}

const listActiveAccountSessions = `-- name: ListActiveAccountSessions :many
SELECT id, created_at, last_seen_at, expires_at, ip_address, user_agent
FROM app.sessions
WHERE account_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
  AND last_seen_at > $3
  AND created_at > $4
ORDER BY last_seen_at DESC, id
LIMIT $5
`

type ListActiveAccountSessionsParams struct {
	AccountID  pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	Limit      int32
}

type ListActiveAccountSessionsRow struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	IpAddress  pgtype.Text
	UserAgent  pgtype.Text
}

// ListActiveAccountSessions returns the sessions of one account that are
// still usable (P16-T06), newest activity first.
//
// The three instants are the policy boundaries, not `now()`: the session
// policy lives in the domain, so the adapter states the same question the
// domain asks (`created_at + absolute`, `last_seen_at + idle`, the stored
// deadline) instead of re-deriving its own answer here. A row outside them is
// already refused by the evaluator, and listing it would show the owner a
// session that cannot accept a request.
func (q *Queries) ListActiveAccountSessions(ctx context.Context, arg ListActiveAccountSessionsParams) ([]ListActiveAccountSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAccountSessions,
		arg.AccountID,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAccountSessionsRow{}
	for rows.Next() {
		var i ListActiveAccountSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.IpAddress,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :execrows
UPDATE app.email_verification_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :execrows
UPDATE app.password_reset_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAccountSessionByID = `-- name: RevokeAccountSessionByID :execrows
UPDATE app.sessions
SET revoked_at = now()
WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL
`

type RevokeAccountSessionByIDParams struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
}

// RevokeAccountSessionByID ends one session of one account.
//
// The account is part of the key on purpose: a revoke addressed by session
// identifier alone would let a caller end a session it does not own, and the
// single statement is what makes two concurrent revokes of the same row agree
// (one reports a change, the other reports none) without a read-modify-write.
func (q *Queries) RevokeAccountSessionByID(ctx context.Context, arg RevokeAccountSessionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccountSessionByID, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllAccountSessions = `-- name: RevokeAllAccountSessions :exec
UPDATE app.sessions
SET revoked_at = now()
WHERE account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAccountSessions(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAccountSessions, accountID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE app.sessions
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const revokeSessionsPastDeadline = `-- name: RevokeSessionsPastDeadline :execrows
UPDATE app.sessions
SET revoked_at = now()
WHERE revoked_at IS NULL
  AND (expires_at <= $1 OR last_seen_at <= $2 OR created_at <= $3)
`

type RevokeSessionsPastDeadlineParams struct {
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// RevokeSessionsPastDeadline revokes every session that has passed its policy
// deadline (P16-T06).
//
// It revokes, it never deletes: the rows of terminal sessions are the retention
// pass's to remove, under its own window and its holds, so this statement
// cannot shorten a retention floor. Marking the row terminal makes the
// refusal a state instead of an arithmetic comparison, which is the same
// defense in depth the rest of the module uses.
func (q *Queries) RevokeSessionsPastDeadline(ctx context.Context, arg RevokeSessionsPastDeadlineParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsPastDeadline, arg.ExpiresAt, arg.LastSeenAt, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEmailVerified = `-- name: SetEmailVerified :one
UPDATE app.accounts
SET status = 'active', email_verified_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, email, status, email_verified_at, created_at, updated_at
`

func (q *Queries) SetEmailVerified(ctx context.Context, id pgtype.UUID) (AppAccount, error) {
	row := q.db.QueryRow(ctx, setEmailVerified, id)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE app.sessions
SET last_seen_at = $2, expires_at = $3
WHERE id = $1 AND revoked_at IS NULL
`

type TouchSessionParams struct {
	ID         pgtype.UUID
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastSeenAt, arg.ExpiresAt)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE app.accounts
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, status, email_verified_at, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (AppAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordCredential = `-- name: UpdatePasswordCredential :exec
UPDATE app.password_credentials
SET password_hash = $2, algorithm = $3, version = $4, updated_at = now()
WHERE account_id = $1
`

type UpdatePasswordCredentialParams struct {
	AccountID    pgtype.UUID
	PasswordHash string
	Algorithm    string
	Version      int32
}

func (q *Queries) UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, updatePasswordCredential,
		arg.AccountID,
		arg.PasswordHash,
		arg.Algorithm,
		arg.Version,
	)
	return err
}

const updateSessionLastSeen = `-- name: UpdateSessionLastSeen :exec
UPDATE app.sessions
SET last_seen_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionLastSeen, id)
	return err
}
