// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeJob = `-- name: CompleteJob :one
UPDATE app.jobs AS j
SET state = 'succeeded',
    lease_owner = NULL,
    leased_until = NULL,
    updated_at = $1::timestamptz
WHERE j.id = $2::uuid
  AND j.state = 'leased'
  AND j.lease_owner = $3::text
RETURNING j.id, j.type, j.version, j.parameters, j.idempotency_key, j.state,
          j.available_at, j.attempts, j.max_attempts, j.lease_owner,
          j.leased_until, j.last_error_code, j.last_error_detail,
          j.created_at, j.updated_at
`

type CompleteJobParams struct {
	Now        pgtype.Timestamptz
	ID         pgtype.UUID
	LeaseOwner string
}

// A lease holder finishes its job. A stale holder (lease already recovered
// and re-leased) matches nothing and cannot overwrite the new outcome.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (AppJob, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.Now, arg.ID, arg.LeaseOwner)
	var i AppJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.Parameters,
		&i.IdempotencyKey,
		&i.State,
		&i.AvailableAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeasedUntil,
		&i.LastErrorCode,
		&i.LastErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countJobsByState = `-- name: CountJobsByState :many
SELECT state, count(*)::bigint AS total
FROM app.jobs
GROUP BY state
ORDER BY state
`

type CountJobsByStateRow struct {
	State string
	Total int64
}

func (q *Queries) CountJobsByState(ctx context.Context) ([]CountJobsByStateRow, error) {
	rows, err := q.db.Query(ctx, countJobsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStateRow{}
	for rows.Next() {
		var i CountJobsByStateRow
		if err := rows.Scan(&i.State, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO app.jobs (
    type, version, parameters, idempotency_key, state, available_at, max_attempts, created_at, updated_at
)
VALUES (
    $1::text,
    $2::integer,
    $3,
    $4::text,
    'queued',
    $5::timestamptz,
    $6::integer,
    $7::timestamptz,
    $7::timestamptz
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, type, version, parameters, idempotency_key, state, available_at,
          attempts, max_attempts, lease_owner, leased_until,
          last_error_code, last_error_detail, created_at, updated_at
`

type EnqueueJobParams struct {
	Type           string
	Version        int32
	Parameters     []byte
	IdempotencyKey pgtype.Text
	AvailableAt    pgtype.Timestamptz
	MaxAttempts    int32
	CreatedAt      pgtype.Timestamptz
}

// Durable job queue (P15-T01). Enqueue is idempotent by caller-chosen key;
// claim is a single statement that locks one due row with SKIP LOCKED, so
// many workers never claim the same job; complete and fail are lease-guarded;
// release recovers leases whose holder died without reporting back.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (AppJob, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.Type,
		arg.Version,
		arg.Parameters,
		arg.IdempotencyKey,
		arg.AvailableAt,
		arg.MaxAttempts,
		arg.CreatedAt,
	)
	var i AppJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.Parameters,
		&i.IdempotencyKey,
		&i.State,
		&i.AvailableAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeasedUntil,
		&i.LastErrorCode,
		&i.LastErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :one
UPDATE app.jobs AS j
SET state = CASE WHEN j.attempts >= j.max_attempts THEN 'dead' ELSE 'queued' END,
    available_at = CASE
        WHEN j.attempts >= j.max_attempts THEN j.available_at
        ELSE $1::timestamptz
    END,
    lease_owner = NULL,
    leased_until = NULL,
    last_error_code = $2::text,
    last_error_detail = $3::text,
    updated_at = $4::timestamptz
WHERE j.id = $5::uuid
  AND j.state = 'leased'
  AND j.lease_owner = $6::text
RETURNING j.id, j.type, j.version, j.parameters, j.idempotency_key, j.state,
          j.available_at, j.attempts, j.max_attempts, j.lease_owner,
          j.leased_until, j.last_error_code, j.last_error_detail,
          j.created_at, j.updated_at
`

type FailJobParams struct {
	RetryAt     pgtype.Timestamptz
	ErrorCode   string
	ErrorDetail string
	Now         pgtype.Timestamptz
	ID          pgtype.UUID
	LeaseOwner  string
}

// Record a redacted failure. The attempt was consumed at lease time, so the
// budget check here decides between requeueing at retry_at and the terminal
// dead state: a poison job leaves the queue instead of blocking it.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (AppJob, error) {
	row := q.db.QueryRow(ctx, failJob,
		arg.RetryAt,
		arg.ErrorCode,
		arg.ErrorDetail,
		arg.Now,
		arg.ID,
		arg.LeaseOwner,
	)
	var i AppJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.Parameters,
		&i.IdempotencyKey,
		&i.State,
		&i.AvailableAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeasedUntil,
		&i.LastErrorCode,
		&i.LastErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, version, parameters, idempotency_key, state, available_at,
       attempts, max_attempts, lease_owner, leased_until,
       last_error_code, last_error_detail, created_at, updated_at
FROM app.jobs
WHERE id = $1::uuid
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (AppJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i AppJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.Parameters,
		&i.IdempotencyKey,
		&i.State,
		&i.AvailableAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeasedUntil,
		&i.LastErrorCode,
		&i.LastErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, type, version, parameters, idempotency_key, state, available_at,
       attempts, max_attempts, lease_owner, leased_until,
       last_error_code, last_error_detail, created_at, updated_at
FROM app.jobs
WHERE idempotency_key = $1::text
`

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, idempotencyKey string) (AppJob, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, idempotencyKey)
	var i AppJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.Parameters,
		&i.IdempotencyKey,
		&i.State,
		&i.AvailableAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeasedUntil,
		&i.LastErrorCode,
		&i.LastErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseJob = `-- name: LeaseJob :one
WITH claimable AS (
    SELECT id
    FROM app.jobs
    WHERE (state = 'queued' AND available_at <= $3::timestamptz)
       OR (state = 'leased' AND leased_until <= $3::timestamptz)
    ORDER BY available_at ASC, id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE app.jobs AS j
SET state = 'leased',
    lease_owner = $1::text,
    leased_until = $2::timestamptz,
    attempts = j.attempts + 1,
    updated_at = $3::timestamptz
FROM claimable
WHERE j.id = claimable.id
RETURNING j.id, j.type, j.version, j.parameters, j.idempotency_key, j.state,
          j.available_at, j.attempts, j.max_attempts, j.lease_owner,
          j.leased_until, j.last_error_code, j.last_error_detail,
          j.created_at, j.updated_at
`

type LeaseJobParams struct {
	LeaseOwner  string
	LeasedUntil pgtype.Timestamptz
	Now         pgtype.Timestamptz
}

// Claim exactly one job that is either queued and due or leased and expired.
// FOR UPDATE SKIP LOCKED lets concurrent workers take different rows without
// queueing behind each other and without ever taking the same row twice.
func (q *Queries) LeaseJob(ctx context.Context, arg LeaseJobParams) (AppJob, error) {
	row := q.db.QueryRow(ctx, leaseJob, arg.LeaseOwner, arg.LeasedUntil, arg.Now)
	var i AppJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Version,
		&i.Parameters,
		&i.IdempotencyKey,
		&i.State,
		&i.AvailableAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseOwner,
		&i.LeasedUntil,
		&i.LastErrorCode,
		&i.LastErrorDetail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseExpiredLeases = `-- name: ReleaseExpiredLeases :execrows
UPDATE app.jobs
SET state = 'queued',
    lease_owner = NULL,
    leased_until = NULL,
    updated_at = $1::timestamptz
WHERE state = 'leased'
  AND leased_until <= $1::timestamptz
`

// Recovery sweep: return every job whose lease expired to the queue. The
// count tells the scheduler how much work was reclaimed.
func (q *Queries) ReleaseExpiredLeases(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, releaseExpiredLeases, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
