// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mfa.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMFAVerifiedStep = `-- name: AdvanceMFAVerifiedStep :execrows
UPDATE app.account_mfa
SET last_accepted_step = $2,
    updated_at = now()
WHERE account_id = $1
  AND last_accepted_step < $2
`

type AdvanceMFAVerifiedStepParams struct {
	AccountID        pgtype.UUID
	LastAcceptedStep int64
}

func (q *Queries) AdvanceMFAVerifiedStep(ctx context.Context, arg AdvanceMFAVerifiedStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceMFAVerifiedStep, arg.AccountID, arg.LastAcceptedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmMFAEnrollment = `-- name: ConfirmMFAEnrollment :one
UPDATE app.account_mfa
SET confirmed_at = $2,
    last_accepted_step = $3,
    updated_at = now()
WHERE account_id = $1
  AND confirmed_at IS NULL
RETURNING confirmed_at
`

type ConfirmMFAEnrollmentParams struct {
	AccountID        pgtype.UUID
	ConfirmedAt      pgtype.Timestamptz
	LastAcceptedStep int64
}

func (q *Queries) ConfirmMFAEnrollment(ctx context.Context, arg ConfirmMFAEnrollmentParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, confirmMFAEnrollment, arg.AccountID, arg.ConfirmedAt, arg.LastAcceptedStep)
	var confirmed_at pgtype.Timestamptz
	err := row.Scan(&confirmed_at)
	return confirmed_at, err
}

const consumeMFABackupCode = `-- name: ConsumeMFABackupCode :execrows
UPDATE app.mfa_backup_codes
SET used_at = $2
WHERE id = $1
  AND used_at IS NULL
`

type ConsumeMFABackupCodeParams struct {
	ID     pgtype.UUID
	UsedAt pgtype.Timestamptz
}

func (q *Queries) ConsumeMFABackupCode(ctx context.Context, arg ConsumeMFABackupCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeMFABackupCode, arg.ID, arg.UsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMFABackupCodes = `-- name: DeleteMFABackupCodes :execrows
DELETE FROM app.mfa_backup_codes
WHERE account_id = $1
`

func (q *Queries) DeleteMFABackupCodes(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMFABackupCodes, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMFAEnrollment = `-- name: GetMFAEnrollment :one

SELECT account_id, secret_sealed, confirmed_at, last_accepted_step, created_at, updated_at
FROM app.account_mfa
WHERE account_id = $1
`

// MFA queries (P16-T05). The two statements that carry a security invariant
// are written as single statements on purpose:
//
//   - UpsertPendingMFAEnrollment refuses to overwrite a confirmed enrollment,
//     so "start enrollment" cannot become a way to reset somebody's second
//     factor;
//   - AdvanceMFAVerifiedStep only moves forward, so two requests presenting the
//     same code cannot both be accepted.
func (q *Queries) GetMFAEnrollment(ctx context.Context, accountID pgtype.UUID) (AppAccountMfa, error) {
	row := q.db.QueryRow(ctx, getMFAEnrollment, accountID)
	var i AppAccountMfa
	err := row.Scan(
		&i.AccountID,
		&i.SecretSealed,
		&i.ConfirmedAt,
		&i.LastAcceptedStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionMFAVerifiedAt = `-- name: GetSessionMFAVerifiedAt :one
SELECT mfa_verified_at
FROM app.sessions
WHERE id = $1
`

func (q *Queries) GetSessionMFAVerifiedAt(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getSessionMFAVerifiedAt, id)
	var mfa_verified_at pgtype.Timestamptz
	err := row.Scan(&mfa_verified_at)
	return mfa_verified_at, err
}

const insertMFABackupCode = `-- name: InsertMFABackupCode :exec
INSERT INTO app.mfa_backup_codes (account_id, code_hash)
VALUES ($1, $2)
`

type InsertMFABackupCodeParams struct {
	AccountID pgtype.UUID
	CodeHash  string
}

func (q *Queries) InsertMFABackupCode(ctx context.Context, arg InsertMFABackupCodeParams) error {
	_, err := q.db.Exec(ctx, insertMFABackupCode, arg.AccountID, arg.CodeHash)
	return err
}

const listUnusedMFABackupCodes = `-- name: ListUnusedMFABackupCodes :many
SELECT id, code_hash
FROM app.mfa_backup_codes
WHERE account_id = $1
  AND used_at IS NULL
ORDER BY created_at, id
`

type ListUnusedMFABackupCodesRow struct {
	ID       pgtype.UUID
	CodeHash string
}

func (q *Queries) ListUnusedMFABackupCodes(ctx context.Context, accountID pgtype.UUID) ([]ListUnusedMFABackupCodesRow, error) {
	rows, err := q.db.Query(ctx, listUnusedMFABackupCodes, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnusedMFABackupCodesRow{}
	for rows.Next() {
		var i ListUnusedMFABackupCodesRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionMFAVerified = `-- name: MarkSessionMFAVerified :execrows
UPDATE app.sessions
SET mfa_verified_at = $2
WHERE id = $1
  AND revoked_at IS NULL
`

type MarkSessionMFAVerifiedParams struct {
	ID            pgtype.UUID
	MfaVerifiedAt pgtype.Timestamptz
}

func (q *Queries) MarkSessionMFAVerified(ctx context.Context, arg MarkSessionMFAVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionMFAVerified, arg.ID, arg.MfaVerifiedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPendingMFAEnrollment = `-- name: UpsertPendingMFAEnrollment :one
INSERT INTO app.account_mfa (account_id, secret_sealed)
VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE
    SET secret_sealed = EXCLUDED.secret_sealed,
        last_accepted_step = -1,
        updated_at = now()
    WHERE app.account_mfa.confirmed_at IS NULL
RETURNING account_id, secret_sealed, confirmed_at, last_accepted_step, created_at, updated_at
`

type UpsertPendingMFAEnrollmentParams struct {
	AccountID    pgtype.UUID
	SecretSealed []byte
}

func (q *Queries) UpsertPendingMFAEnrollment(ctx context.Context, arg UpsertPendingMFAEnrollmentParams) (AppAccountMfa, error) {
	row := q.db.QueryRow(ctx, upsertPendingMFAEnrollment, arg.AccountID, arg.SecretSealed)
	var i AppAccountMfa
	err := row.Scan(
		&i.AccountID,
		&i.SecretSealed,
		&i.ConfirmedAt,
		&i.LastAcceptedStep,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
