// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// User account records and account status lifecycle
type AppAccount struct {
	ID pgtype.UUID
	// User email address; uniqueness enforced case-insensitively via lower(email)
	Email           string
	Status          string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Arena aggregation root: immutable published statement and fixed content language, mutable lifecycle status
type AppArena struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
	// Stable public address assigned at publication; never an identity substitute
	Slug      pgtype.Text
	Statement string
	Context   pgtype.Text
	Category  string
	// Immutable content language of the Arena (pt-BR or en-US); independent from the interface locale
	Language string
	Status   string
	// Optimistic concurrency version, incremented on every accepted mutation
	Version     int32
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	ClosesAt    pgtype.Timestamptz
}

// Append-only Arena Pass consumptions; one row per published Arena, never updated or deleted at runtime
type AppArenaPassConsumption struct {
	ID         pgtype.UUID
	LotID      pgtype.UUID
	ArenaID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

// Arena Pass lots: origin, granted quantity, optional immutable expiration and stable reference
type AppArenaPassLot struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Origin    string
	Quantity  int32
	// Consumable projection of the lot; over-consumption fails the CHECK constraint
	RemainingQuantity int32
	// Optional immutable expiration (NULL never expires); Member lots expire at their period end
	ExpiresAt pgtype.Timestamptz
	Reference string
	CreatedAt pgtype.Timestamptz
}

// Substitution/continuation notes linking one Arena to another (never to itself)
type AppArenaRelation struct {
	ID             pgtype.UUID
	ArenaID        pgtype.UUID
	RelatedArenaID pgtype.UUID
	Relation       string
	CreatedAt      pgtype.Timestamptz
}

// Editorial Arena categories; seeded by migrations, display names resolve through the versioned i18n catalogs
type AppCategory struct {
	Slug         string
	DisplayOrder int32
	CreatedAt    pgtype.Timestamptz
}

// Explicit communication opt-ins per account; marketing defaults to false and is never opted in implicitly
type AppCommunicationPreference struct {
	AccountID pgtype.UUID
	// Explicit marketing consent; false by default and only the account owner may change it
	MarketingOptIn bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Append-only audit trail of every explicit communication preference change
type AppCommunicationPreferenceHistory struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	MarketingOptIn bool
	ChangedAt      pgtype.Timestamptz
}

// Private projection of one account position in one Arena: immutable initial choice plus current choice and optimistic version
type AppDebatePosition struct {
	ArenaID   pgtype.UUID
	AccountID pgtype.UUID
	// Immutable first confirmed position; the history chain starts here at version 1
	InitialPosition string
	// Derived projection of the chain tip; must equal the last accepted change target
	CurrentPosition string
	// Optimistic concurrency version: 1 at confirmation, +1 per accepted change
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Single-use cryptographic token hashes for email verification
type AppEmailVerificationToken struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Hashed password credentials isolated from public account and profile data
type AppPasswordCredential struct {
	AccountID    pgtype.UUID
	PasswordHash string
	Algorithm    string
	Version      int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Single-use cryptographic token hashes for password recovery
type AppPasswordResetToken struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Append-only chain of accepted position changes; from_position and to_position always differ
type AppPositionChange struct {
	ID           pgtype.UUID
	ArenaID      pgtype.UUID
	AccountID    pgtype.UUID
	FromPosition string
	ToPosition   string
	// Resulting projection version after the change; the chain starts at 2
	Version int32
	// Instant of the accepted change; ordering authority is version
	ChangedAt pgtype.Timestamptz
}

// Account profiles: public username and interface locale, without email or payment identifiers
type AppProfile struct {
	AccountID pgtype.UUID
	Username  string
	// Canonical ASCII-lowercase username; sole uniqueness/authority key for lookups
	UsernameNormalized string
	InterfaceLocale    string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	// Optional IANA timezone preference of the account; NULL means not informed (UTC fallback)
	Timezone pgtype.Text
}

// goose forward-only migration history for the app schema (schema_metadata version table required by the master plan)
type AppSchemaMetadatum struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

// Opaque server-side session store with revocation and inactivity tracking
type AppSession struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	IpAddress  pgtype.Text
	UserAgent  pgtype.Text
}

// Audit trail of every username set or changed by an account (P05-T02 requires auditable history)
type AppUsernameHistory struct {
	ID                 pgtype.UUID
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
	ChangedAt          pgtype.Timestamptz
}

// Cached INK balance projection per account and bucket; the append-only transaction ledger is the source of truth
type AppWalletAccount struct {
	AccountID pgtype.UUID
	// FREE_INK balance (plan franchise, consumed before purchased INK); never negative
	BalanceFree int64
	// PURCHASED_INK balance (bought INK, consumed after the franchise); never negative
	BalancePurchased int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	// Monthly FREE_INK cycle anchor (activation instant); immutable and evaluated in UTC
	FreeCycleAnchorAt pgtype.Timestamptz
}

// Append-only idempotency registry of logical INK operations (credit, debit, expiry)
type AppWalletOperation struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	OperationType string
	// Globally unique retry key: the same key is accepted exactly once
	IdempotencyKey string
	// Stable identifier of the cause (argument, Stripe event, moderation case, billing period)
	Reference string
	CreatedAt pgtype.Timestamptz
	// Mandatory justification of administrative adjustments; optional for regular operations
	Reason pgtype.Text
	// Acting administrator account for administrative adjustments; never modified after insert
	ActorAccountID pgtype.UUID
}

// Append-only INK ledger: signed bucket deltas (positive credit, negative debit); never updated or deleted at runtime
type AppWalletTransaction struct {
	ID          pgtype.UUID
	OperationID pgtype.UUID
	Bucket      string
	// Signed INK delta in bigint: positive credits the bucket, negative debits it; zero is forbidden
	Amount    int64
	CreatedAt pgtype.Timestamptz
}
