// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// User account records and account status lifecycle
type AppAccount struct {
	ID pgtype.UUID
	// User email address; uniqueness enforced case-insensitively via lower(email)
	Email           string
	Status          string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Explicit communication opt-ins per account; marketing defaults to false and is never opted in implicitly
type AppCommunicationPreference struct {
	AccountID pgtype.UUID
	// Explicit marketing consent; false by default and only the account owner may change it
	MarketingOptIn bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Append-only audit trail of every explicit communication preference change
type AppCommunicationPreferenceHistory struct {
	ID             pgtype.UUID
	AccountID      pgtype.UUID
	MarketingOptIn bool
	ChangedAt      pgtype.Timestamptz
}

// Single-use cryptographic token hashes for email verification
type AppEmailVerificationToken struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Hashed password credentials isolated from public account and profile data
type AppPasswordCredential struct {
	AccountID    pgtype.UUID
	PasswordHash string
	Algorithm    string
	Version      int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// Single-use cryptographic token hashes for password recovery
type AppPasswordResetToken struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// Account profiles: public username and interface locale, without email or payment identifiers
type AppProfile struct {
	AccountID pgtype.UUID
	Username  string
	// Canonical ASCII-lowercase username; sole uniqueness/authority key for lookups
	UsernameNormalized string
	InterfaceLocale    string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// goose forward-only migration history for the app schema (schema_metadata version table required by the master plan)
type AppSchemaMetadatum struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    pgtype.Timestamp
}

// Opaque server-side session store with revocation and inactivity tracking
type AppSession struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	TokenHash  []byte
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	IpAddress  pgtype.Text
	UserAgent  pgtype.Text
}

// Audit trail of every username set or changed by an account (P05-T02 requires auditable history)
type AppUsernameHistory struct {
	ID                 pgtype.UUID
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
	ChangedAt          pgtype.Timestamptz
}
