// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: moderation.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminRoleByAccount = `-- name: GetAdminRoleByAccount :one

SELECT account_id, role, granted_by, granted_at, revoked_at
FROM app.admin_roles
WHERE account_id = $1
`

// Administrative assignment queries for the PostgreSQL platform adapter.
//
// Assignments key on account identifiers only: email, frontend flags,
// payment state and popularity never enter this surface, so authorization
// can never be influenced by who pays or who is popular (P13-T02).
func (q *Queries) GetAdminRoleByAccount(ctx context.Context, accountID pgtype.UUID) (AppAdminRole, error) {
	row := q.db.QueryRow(ctx, getAdminRoleByAccount, accountID)
	var i AppAdminRole
	err := row.Scan(
		&i.AccountID,
		&i.Role,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}
