// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: moderation.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimModerationAppeal = `-- name: ClaimModerationAppeal :one
UPDATE app.moderation_appeals
SET status = 'under_review'
WHERE id = $1 AND status = 'open'
RETURNING id, action_id, appellant_id, status, reviewer_id, decision_reason, created_at, decided_at
`

type ClaimModerationAppealRow struct {
	ID             pgtype.UUID
	ActionID       pgtype.UUID
	AppellantID    pgtype.UUID
	Status         string
	ReviewerID     pgtype.UUID
	DecisionReason pgtype.Text
	CreatedAt      pgtype.Timestamptz
	DecidedAt      pgtype.Timestamptz
}

func (q *Queries) ClaimModerationAppeal(ctx context.Context, id pgtype.UUID) (ClaimModerationAppealRow, error) {
	row := q.db.QueryRow(ctx, claimModerationAppeal, id)
	var i ClaimModerationAppealRow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.AppellantID,
		&i.Status,
		&i.ReviewerID,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const claimModerationCase = `-- name: ClaimModerationCase :one
UPDATE app.moderation_cases
SET status = 'under_review', claimed_by = $2, claimed_at = $3, lease_expires_at = $4, updated_at = now()
WHERE id = $1
  AND (
    (status = 'open' AND claimed_by IS NULL)
    OR (status = 'under_review' AND lease_expires_at IS NOT NULL AND lease_expires_at <= $5)
  )
RETURNING id, target_type, target_arena_id, target_argument_id, target_account_id,
    status, claimed_by, lease_expires_at
`

type ClaimModerationCaseParams struct {
	ID               pgtype.UUID
	ClaimedBy        pgtype.UUID
	ClaimedAt        pgtype.Timestamptz
	LeaseExpiresAt   pgtype.Timestamptz
	LeaseExpiresAt_2 pgtype.Timestamptz
}

type ClaimModerationCaseRow struct {
	ID               pgtype.UUID
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	Status           string
	ClaimedBy        pgtype.UUID
	LeaseExpiresAt   pgtype.Timestamptz
}

func (q *Queries) ClaimModerationCase(ctx context.Context, arg ClaimModerationCaseParams) (ClaimModerationCaseRow, error) {
	row := q.db.QueryRow(ctx, claimModerationCase,
		arg.ID,
		arg.ClaimedBy,
		arg.ClaimedAt,
		arg.LeaseExpiresAt,
		arg.LeaseExpiresAt_2,
	)
	var i ClaimModerationCaseRow
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetArenaID,
		&i.TargetArgumentID,
		&i.TargetAccountID,
		&i.Status,
		&i.ClaimedBy,
		&i.LeaseExpiresAt,
	)
	return i, err
}

const closeArenaForModeration = `-- name: CloseArenaForModeration :one

UPDATE app.arenas
SET status = 'closed',
    version = version + 1
WHERE id = $1 AND status = 'published'
RETURNING id, status, version
`

type CloseArenaForModerationRow struct {
	ID      pgtype.UUID
	Status  string
	Version int32
}

// Sanction effects applied in the same transaction as the audit event
// (P13-T05). Each statement is conditional: zero affected rows means the
// target left the sanctionable state concurrently, and the adapter rolls
// the whole decision back instead of recording a phantom sanction.
func (q *Queries) CloseArenaForModeration(ctx context.Context, id pgtype.UUID) (CloseArenaForModerationRow, error) {
	row := q.db.QueryRow(ctx, closeArenaForModeration, id)
	var i CloseArenaForModerationRow
	err := row.Scan(&i.ID, &i.Status, &i.Version)
	return i, err
}

const countRecentModerationReportsByReporter = `-- name: CountRecentModerationReportsByReporter :one
SELECT count(*)::bigint AS recent_reports
FROM app.moderation_reports
WHERE reporter_id = $1
  AND created_at >= $2
`

type CountRecentModerationReportsByReporterParams struct {
	ReporterID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CountRecentModerationReportsByReporter(ctx context.Context, arg CountRecentModerationReportsByReporterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentModerationReportsByReporter, arg.ReporterID, arg.CreatedAt)
	var recent_reports int64
	err := row.Scan(&recent_reports)
	return recent_reports, err
}

const createModerationAction = `-- name: CreateModerationAction :one
INSERT INTO app.moderation_actions (case_id, action_type, actor_id, rule_applied, justification, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, case_id, action_type, actor_id, rule_applied, justification, expires_at, created_at
`

type CreateModerationActionParams struct {
	CaseID        pgtype.UUID
	ActionType    string
	ActorID       pgtype.UUID
	RuleApplied   string
	Justification string
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) (AppModerationAction, error) {
	row := q.db.QueryRow(ctx, createModerationAction,
		arg.CaseID,
		arg.ActionType,
		arg.ActorID,
		arg.RuleApplied,
		arg.Justification,
		arg.ExpiresAt,
	)
	var i AppModerationAction
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ActionType,
		&i.ActorID,
		&i.RuleApplied,
		&i.Justification,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createModerationReport = `-- name: CreateModerationReport :one

INSERT INTO app.moderation_reports (reporter_id, target_type, target_arena_id, target_argument_id, target_account_id, reason, context)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, reporter_id, target_type, target_arena_id, target_argument_id, target_account_id, reason, context, created_at
`

type CreateModerationReportParams struct {
	ReporterID       pgtype.UUID
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	Reason           string
	Context          pgtype.Text
}

// Structured report queries for the PostgreSQL platform adapter (P13-T03).
//
// Reports are restricted evidence: inserts carry reporter, target, reason
// and bounded context; reads serve deduplication and the rate signal only.
// No query mutates a target: volume never removes content automatically.
func (q *Queries) CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (AppModerationReport, error) {
	row := q.db.QueryRow(ctx, createModerationReport,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetArenaID,
		arg.TargetArgumentID,
		arg.TargetAccountID,
		arg.Reason,
		arg.Context,
	)
	var i AppModerationReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetArenaID,
		&i.TargetArgumentID,
		&i.TargetAccountID,
		&i.Reason,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const decideModerationAppeal = `-- name: DecideModerationAppeal :one
UPDATE app.moderation_appeals
SET status = $2, reviewer_id = $3, decision_reason = $4, decided_at = $5
WHERE id = $1 AND status = 'under_review'
RETURNING id, action_id, appellant_id, status, reviewer_id, decision_reason, created_at, decided_at
`

type DecideModerationAppealParams struct {
	ID             pgtype.UUID
	Status         string
	ReviewerID     pgtype.UUID
	DecisionReason pgtype.Text
	DecidedAt      pgtype.Timestamptz
}

type DecideModerationAppealRow struct {
	ID             pgtype.UUID
	ActionID       pgtype.UUID
	AppellantID    pgtype.UUID
	Status         string
	ReviewerID     pgtype.UUID
	DecisionReason pgtype.Text
	CreatedAt      pgtype.Timestamptz
	DecidedAt      pgtype.Timestamptz
}

func (q *Queries) DecideModerationAppeal(ctx context.Context, arg DecideModerationAppealParams) (DecideModerationAppealRow, error) {
	row := q.db.QueryRow(ctx, decideModerationAppeal,
		arg.ID,
		arg.Status,
		arg.ReviewerID,
		arg.DecisionReason,
		arg.DecidedAt,
	)
	var i DecideModerationAppealRow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.AppellantID,
		&i.Status,
		&i.ReviewerID,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideModerationCase = `-- name: DecideModerationCase :one
UPDATE app.moderation_cases
SET status = 'decided', claimed_by = NULL, claimed_at = NULL, lease_expires_at = NULL, updated_at = now()
WHERE id = $1
  AND status = 'under_review'
  AND claimed_by = $2
  AND lease_expires_at IS NOT NULL AND lease_expires_at > $3
RETURNING id, target_type, target_arena_id, target_argument_id, target_account_id, status
`

type DecideModerationCaseParams struct {
	ID             pgtype.UUID
	ClaimedBy      pgtype.UUID
	LeaseExpiresAt pgtype.Timestamptz
}

type DecideModerationCaseRow struct {
	ID               pgtype.UUID
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	Status           string
}

func (q *Queries) DecideModerationCase(ctx context.Context, arg DecideModerationCaseParams) (DecideModerationCaseRow, error) {
	row := q.db.QueryRow(ctx, decideModerationCase, arg.ID, arg.ClaimedBy, arg.LeaseExpiresAt)
	var i DecideModerationCaseRow
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetArenaID,
		&i.TargetArgumentID,
		&i.TargetAccountID,
		&i.Status,
	)
	return i, err
}

const getAccountModerationTarget = `-- name: GetAccountModerationTarget :one
SELECT id, status
FROM app.accounts
WHERE id = $1
`

type GetAccountModerationTargetRow struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) GetAccountModerationTarget(ctx context.Context, id pgtype.UUID) (GetAccountModerationTargetRow, error) {
	row := q.db.QueryRow(ctx, getAccountModerationTarget, id)
	var i GetAccountModerationTargetRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getAdminRoleByAccount = `-- name: GetAdminRoleByAccount :one

SELECT account_id, role, granted_by, granted_at, revoked_at
FROM app.admin_roles
WHERE account_id = $1
`

// Administrative assignment queries for the PostgreSQL platform adapter.
//
// Assignments key on account identifiers only: email, frontend flags,
// payment state and popularity never enter this surface, so authorization
// can never be influenced by who pays or who is popular (P13-T02).
func (q *Queries) GetAdminRoleByAccount(ctx context.Context, accountID pgtype.UUID) (AppAdminRole, error) {
	row := q.db.QueryRow(ctx, getAdminRoleByAccount, accountID)
	var i AppAdminRole
	err := row.Scan(
		&i.AccountID,
		&i.Role,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getArenaModerationTarget = `-- name: GetArenaModerationTarget :one

SELECT id, creator_id, status
FROM app.arenas
WHERE id = $1
`

type GetArenaModerationTargetRow struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
	Status    string
}

// Target resolution for report filing (P13-T03). Each read returns the
// owner and the lifecycle needed to distinguish unknown targets from
// removed ones. Drafts stay reportable (self-report path); removed and
// withdrawn targets deny.
func (q *Queries) GetArenaModerationTarget(ctx context.Context, id pgtype.UUID) (GetArenaModerationTargetRow, error) {
	row := q.db.QueryRow(ctx, getArenaModerationTarget, id)
	var i GetArenaModerationTargetRow
	err := row.Scan(&i.ID, &i.CreatorID, &i.Status)
	return i, err
}

const getArgumentModerationTarget = `-- name: GetArgumentModerationTarget :one
SELECT id, author_id, status
FROM app.arguments
WHERE id = $1
`

type GetArgumentModerationTargetRow struct {
	ID       pgtype.UUID
	AuthorID pgtype.UUID
	Status   string
}

func (q *Queries) GetArgumentModerationTarget(ctx context.Context, id pgtype.UUID) (GetArgumentModerationTargetRow, error) {
	row := q.db.QueryRow(ctx, getArgumentModerationTarget, id)
	var i GetArgumentModerationTargetRow
	err := row.Scan(&i.ID, &i.AuthorID, &i.Status)
	return i, err
}

const getDuplicateModerationReport = `-- name: GetDuplicateModerationReport :one
SELECT id, reporter_id, target_type, target_arena_id, target_argument_id, target_account_id, reason, context, created_at
FROM app.moderation_reports
WHERE reporter_id = $1
  AND target_type = $2
  AND COALESCE(target_arena_id, '00000000-0000-0000-0000-000000000000'::uuid) = COALESCE($3, '00000000-0000-0000-0000-000000000000'::uuid)
  AND COALESCE(target_argument_id, '00000000-0000-0000-0000-000000000000'::uuid) = COALESCE($4, '00000000-0000-0000-0000-000000000000'::uuid)
  AND COALESCE(target_account_id, '00000000-0000-0000-0000-000000000000'::uuid) = COALESCE($5, '00000000-0000-0000-0000-000000000000'::uuid)
  AND reason = $6
  AND created_at >= $7
ORDER BY created_at ASC, id ASC
LIMIT 1
`

type GetDuplicateModerationReportParams struct {
	ReporterID       pgtype.UUID
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	Reason           string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetDuplicateModerationReport(ctx context.Context, arg GetDuplicateModerationReportParams) (AppModerationReport, error) {
	row := q.db.QueryRow(ctx, getDuplicateModerationReport,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetArenaID,
		arg.TargetArgumentID,
		arg.TargetAccountID,
		arg.Reason,
		arg.CreatedAt,
	)
	var i AppModerationReport
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetArenaID,
		&i.TargetArgumentID,
		&i.TargetAccountID,
		&i.Reason,
		&i.Context,
		&i.CreatedAt,
	)
	return i, err
}

const getModerationActionForAppeal = `-- name: GetModerationActionForAppeal :one

SELECT a.id, a.case_id, a.action_type, a.actor_id, a.rule_applied, a.created_at,
    c.target_type, c.target_arena_id, c.target_argument_id, c.target_account_id,
    COALESCE(ar.creator_id, ag.author_id, ac.id) AS target_owner_id
FROM app.moderation_actions a
JOIN app.moderation_cases c ON c.id = a.case_id
LEFT JOIN app.arenas ar ON ar.id = c.target_arena_id
LEFT JOIN app.arguments ag ON ag.id = c.target_argument_id
LEFT JOIN app.accounts ac ON ac.id = c.target_account_id
WHERE a.id = $1
`

type GetModerationActionForAppealRow struct {
	ID               pgtype.UUID
	CaseID           pgtype.UUID
	ActionType       string
	ActorID          pgtype.UUID
	RuleApplied      string
	CreatedAt        pgtype.Timestamptz
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	TargetOwnerID    pgtype.UUID
}

// Appeal reads and lifecycle (P13-T06). Exactly one appeal contests one
// action: the UNIQUE constraint refuses the second contest, and the
// adapter maps the violation to the duplicate sentinel instead of
// surfacing storage detail.
func (q *Queries) GetModerationActionForAppeal(ctx context.Context, id pgtype.UUID) (GetModerationActionForAppealRow, error) {
	row := q.db.QueryRow(ctx, getModerationActionForAppeal, id)
	var i GetModerationActionForAppealRow
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ActionType,
		&i.ActorID,
		&i.RuleApplied,
		&i.CreatedAt,
		&i.TargetType,
		&i.TargetArenaID,
		&i.TargetArgumentID,
		&i.TargetAccountID,
		&i.TargetOwnerID,
	)
	return i, err
}

const getModerationAppealByAction = `-- name: GetModerationAppealByAction :one
SELECT id, action_id, appellant_id, status, reviewer_id, decision_reason, created_at, decided_at
FROM app.moderation_appeals
WHERE action_id = $1
`

type GetModerationAppealByActionRow struct {
	ID             pgtype.UUID
	ActionID       pgtype.UUID
	AppellantID    pgtype.UUID
	Status         string
	ReviewerID     pgtype.UUID
	DecisionReason pgtype.Text
	CreatedAt      pgtype.Timestamptz
	DecidedAt      pgtype.Timestamptz
}

func (q *Queries) GetModerationAppealByAction(ctx context.Context, actionID pgtype.UUID) (GetModerationAppealByActionRow, error) {
	row := q.db.QueryRow(ctx, getModerationAppealByAction, actionID)
	var i GetModerationAppealByActionRow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.AppellantID,
		&i.Status,
		&i.ReviewerID,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getModerationAppealByID = `-- name: GetModerationAppealByID :one
SELECT id, action_id, appellant_id, status, reviewer_id, decision_reason, created_at, decided_at
FROM app.moderation_appeals
WHERE id = $1
`

type GetModerationAppealByIDRow struct {
	ID             pgtype.UUID
	ActionID       pgtype.UUID
	AppellantID    pgtype.UUID
	Status         string
	ReviewerID     pgtype.UUID
	DecisionReason pgtype.Text
	CreatedAt      pgtype.Timestamptz
	DecidedAt      pgtype.Timestamptz
}

func (q *Queries) GetModerationAppealByID(ctx context.Context, id pgtype.UUID) (GetModerationAppealByIDRow, error) {
	row := q.db.QueryRow(ctx, getModerationAppealByID, id)
	var i GetModerationAppealByIDRow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.AppellantID,
		&i.Status,
		&i.ReviewerID,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getModerationCaseByID = `-- name: GetModerationCaseByID :one

SELECT c.id, c.target_type, c.target_arena_id, c.target_argument_id, c.target_account_id,
    c.status, c.claimed_by, c.lease_expires_at,
    COALESCE(ar.creator_id, ag.author_id, ac.id) AS target_owner_id
FROM app.moderation_cases c
LEFT JOIN app.arenas ar ON ar.id = c.target_arena_id
LEFT JOIN app.arguments ag ON ag.id = c.target_argument_id
LEFT JOIN app.accounts ac ON ac.id = c.target_account_id
WHERE c.id = $1
`

type GetModerationCaseByIDRow struct {
	ID               pgtype.UUID
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	Status           string
	ClaimedBy        pgtype.UUID
	LeaseExpiresAt   pgtype.Timestamptz
	TargetOwnerID    pgtype.UUID
}

// Review claim and decision queries (P13-T04). Claims serialize on the
// row: one conditional update moves open (or expired-lease) cases under
// the claimant with a fresh lease. Decisions record one immutable action
// and move the case to decided while clearing the claim, atomically in
// the adapter transaction.
func (q *Queries) GetModerationCaseByID(ctx context.Context, id pgtype.UUID) (GetModerationCaseByIDRow, error) {
	row := q.db.QueryRow(ctx, getModerationCaseByID, id)
	var i GetModerationCaseByIDRow
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetArenaID,
		&i.TargetArgumentID,
		&i.TargetAccountID,
		&i.Status,
		&i.ClaimedBy,
		&i.LeaseExpiresAt,
		&i.TargetOwnerID,
	)
	return i, err
}

const getSessionCreatedAt = `-- name: GetSessionCreatedAt :one

SELECT created_at
FROM app.sessions
WHERE id = $1
`

// Session freshness for step-up evaluation (P13-T07). The age counts from
// session creation as of the caller's instant; unknown sessions deny
// distinctly instead of being treated as fresh.
func (q *Queries) GetSessionCreatedAt(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getSessionCreatedAt, id)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertModerationAppeal = `-- name: InsertModerationAppeal :one
INSERT INTO app.moderation_appeals (action_id, appellant_id, context)
VALUES ($1, $2, $3)
RETURNING id, action_id, appellant_id, status, reviewer_id, decision_reason, created_at, decided_at
`

type InsertModerationAppealParams struct {
	ActionID    pgtype.UUID
	AppellantID pgtype.UUID
	Context     string
}

type InsertModerationAppealRow struct {
	ID             pgtype.UUID
	ActionID       pgtype.UUID
	AppellantID    pgtype.UUID
	Status         string
	ReviewerID     pgtype.UUID
	DecisionReason pgtype.Text
	CreatedAt      pgtype.Timestamptz
	DecidedAt      pgtype.Timestamptz
}

func (q *Queries) InsertModerationAppeal(ctx context.Context, arg InsertModerationAppealParams) (InsertModerationAppealRow, error) {
	row := q.db.QueryRow(ctx, insertModerationAppeal, arg.ActionID, arg.AppellantID, arg.Context)
	var i InsertModerationAppealRow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.AppellantID,
		&i.Status,
		&i.ReviewerID,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const invalidateArgumentAttributions = `-- name: InvalidateArgumentAttributions :execrows
UPDATE app.persuasion_attributions
SET status = 'invalid',
    invalidated_at = now(),
    moderation_reason = $2,
    moderated_by = $3,
    moderated_at = now()
WHERE argument_id = $1 AND status = 'valid'
`

type InvalidateArgumentAttributionsParams struct {
	ArgumentID       pgtype.UUID
	ModerationReason pgtype.Text
	ModeratedBy      pgtype.UUID
}

func (q *Queries) InvalidateArgumentAttributions(ctx context.Context, arg InvalidateArgumentAttributionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateArgumentAttributions, arg.ArgumentID, arg.ModerationReason, arg.ModeratedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listModerationCasesPage = `-- name: ListModerationCasesPage :many

SELECT id, target_type, target_arena_id, target_argument_id, target_account_id,
    status, priority, created_at, claimed_by
FROM app.moderation_cases
WHERE ($1::text = '' OR status = $1::text)
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListModerationCasesPageParams struct {
	Status         string
	AfterCreatedAt pgtype.Timestamptz
	AfterID        pgtype.UUID
	PageLimit      int32
}

type ListModerationCasesPageRow struct {
	ID               pgtype.UUID
	TargetType       string
	TargetArenaID    pgtype.UUID
	TargetArgumentID pgtype.UUID
	TargetAccountID  pgtype.UUID
	Status           string
	Priority         string
	CreatedAt        pgtype.Timestamptz
	ClaimedBy        pgtype.UUID
}

// Triage queue reads (P13-T07). One keyset-paginated page of case routing,
// newest first: target, lifecycle, priority, claim holder and instants.
// Restricted evidence (reporter context, justifications, appeal contexts)
// is never selected here. NULL after_* parameters select the first page;
// the (created_at, id) tuple comparison never duplicates or skips rows. An
// empty status filter lists every lifecycle.
func (q *Queries) ListModerationCasesPage(ctx context.Context, arg ListModerationCasesPageParams) ([]ListModerationCasesPageRow, error) {
	rows, err := q.db.Query(ctx, listModerationCasesPage,
		arg.Status,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModerationCasesPageRow{}
	for rows.Next() {
		var i ListModerationCasesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetArenaID,
			&i.TargetArgumentID,
			&i.TargetAccountID,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.ClaimedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateAccountForAppeal = `-- name: ReactivateAccountForAppeal :one
UPDATE app.accounts
SET status = 'active',
    updated_at = now()
WHERE id = $1 AND status = 'suspended'
RETURNING id, status
`

type ReactivateAccountForAppealRow struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) ReactivateAccountForAppeal(ctx context.Context, id pgtype.UUID) (ReactivateAccountForAppealRow, error) {
	row := q.db.QueryRow(ctx, reactivateAccountForAppeal, id)
	var i ReactivateAccountForAppealRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const removeArgumentForModeration = `-- name: RemoveArgumentForModeration :one
UPDATE app.arguments
SET status = 'removed',
    updated_at = now()
WHERE id = $1 AND status IN ('published', 'withdrawn')
RETURNING id, status
`

type RemoveArgumentForModerationRow struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) RemoveArgumentForModeration(ctx context.Context, id pgtype.UUID) (RemoveArgumentForModerationRow, error) {
	row := q.db.QueryRow(ctx, removeArgumentForModeration, id)
	var i RemoveArgumentForModerationRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const reopenArenaForAppeal = `-- name: ReopenArenaForAppeal :one

UPDATE app.arenas
SET status = 'published',
    version = version + 1
WHERE id = $1 AND status = 'closed'
RETURNING id, status, version
`

type ReopenArenaForAppealRow struct {
	ID      pgtype.UUID
	Status  string
	Version int32
}

// Reversal effects restoring sanctioned projections from the original
// action record (P13-T06). Each statement is conditional: zero affected
// rows aborts the whole outcome instead of recording a phantom restore.
// The original action row is never edited or deleted.
func (q *Queries) ReopenArenaForAppeal(ctx context.Context, id pgtype.UUID) (ReopenArenaForAppealRow, error) {
	row := q.db.QueryRow(ctx, reopenArenaForAppeal, id)
	var i ReopenArenaForAppealRow
	err := row.Scan(&i.ID, &i.Status, &i.Version)
	return i, err
}

const restoreArgumentAttributions = `-- name: RestoreArgumentAttributions :execrows
UPDATE app.persuasion_attributions
SET status = 'valid',
    moderation_reason = $2,
    moderated_by = $3,
    moderated_at = now()
WHERE argument_id = $1 AND status = 'invalid'
`

type RestoreArgumentAttributionsParams struct {
	ArgumentID       pgtype.UUID
	ModerationReason pgtype.Text
	ModeratedBy      pgtype.UUID
}

func (q *Queries) RestoreArgumentAttributions(ctx context.Context, arg RestoreArgumentAttributionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreArgumentAttributions, arg.ArgumentID, arg.ModerationReason, arg.ModeratedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreArgumentForAppeal = `-- name: RestoreArgumentForAppeal :one
UPDATE app.arguments
SET status = 'published',
    updated_at = now()
WHERE id = $1 AND status = 'removed'
RETURNING id, status
`

type RestoreArgumentForAppealRow struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) RestoreArgumentForAppeal(ctx context.Context, id pgtype.UUID) (RestoreArgumentForAppealRow, error) {
	row := q.db.QueryRow(ctx, restoreArgumentForAppeal, id)
	var i RestoreArgumentForAppealRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const suspendAccountForModeration = `-- name: SuspendAccountForModeration :one
UPDATE app.accounts
SET status = 'suspended',
    updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, status
`

type SuspendAccountForModerationRow struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) SuspendAccountForModeration(ctx context.Context, id pgtype.UUID) (SuspendAccountForModerationRow, error) {
	row := q.db.QueryRow(ctx, suspendAccountForModeration, id)
	var i SuspendAccountForModerationRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}
