// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: personal_exports.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePersonalExportDownload = `-- name: ConsumePersonalExportDownload :one
UPDATE app.data_exports
SET download_count = download_count + 1,
    last_downloaded_at = $1::timestamptz,
    updated_at = $1::timestamptz
WHERE id = $2::uuid
  AND account_id = $3::uuid
  AND status = 'ready'
  AND download_token_hash = $4::bytea
  AND expires_at > $1::timestamptz
  AND download_count < max_downloads
RETURNING document, document_sha256
`

type ConsumePersonalExportDownloadParams struct {
	ConsumedAt        pgtype.Timestamptz
	ExportID          pgtype.UUID
	AccountID         pgtype.UUID
	DownloadTokenHash []byte
}

type ConsumePersonalExportDownloadRow struct {
	Document       pgtype.Text
	DocumentSha256 pgtype.Text
}

// ConsumePersonalExportDownload serves one download and consumes one unit of
// the budget atomically: the token must match, the record must be ready, the
// link must be unexpired and the budget unexhausted. Zero rows answer an
// unavailable link, so a replay can never serve the document twice.
func (q *Queries) ConsumePersonalExportDownload(ctx context.Context, arg ConsumePersonalExportDownloadParams) (ConsumePersonalExportDownloadRow, error) {
	row := q.db.QueryRow(ctx, consumePersonalExportDownload,
		arg.ConsumedAt,
		arg.ExportID,
		arg.AccountID,
		arg.DownloadTokenHash,
	)
	var i ConsumePersonalExportDownloadRow
	err := row.Scan(&i.Document, &i.DocumentSha256)
	return i, err
}

const expirePersonalExports = `-- name: ExpirePersonalExports :execrows

UPDATE app.data_exports
SET status = 'expired',
    updated_at = $1::timestamptz
WHERE account_id = $2::uuid
  AND status = 'ready'
  AND expires_at <= $1::timestamptz
`

type ExpirePersonalExportsParams struct {
	Now       pgtype.Timestamptz
	AccountID pgtype.UUID
}

// Personal data export records and projections (P14-T05, docs/PRIVACY.md
// §4/§6, REQ-PRIV-01). The record statements only ever touch token hashes;
// the data projections are approved read-only reads over the account's own
// rows across the identity, profiles, positions, arenas, arguments, wallet,
// pass and billing schemas. Payment provider identifiers, webhook payloads,
// moderation evidence and antifraud signals are never selected.
// ExpirePersonalExports moves the account's ready records past their window
// to expired. It runs before a new request so a stale link can never block
// or revive a fresh one; the partial unique index only covers active
// records. Expiring is idempotent: repeated runs match nothing.
func (q *Queries) ExpirePersonalExports(ctx context.Context, arg ExpirePersonalExportsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expirePersonalExports, arg.Now, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPersonalExportAccount = `-- name: GetPersonalExportAccount :one
SELECT
    a.id, a.email, a.status, a.email_verified_at, a.created_at,
    p.username, p.interface_locale, p.timezone,
    p.created_at AS profile_created_at, p.updated_at AS profile_updated_at,
    cp.marketing_opt_in, cp.updated_at AS preferences_updated_at
FROM app.accounts a
LEFT JOIN app.profiles p ON p.account_id = a.id
LEFT JOIN app.communication_preferences cp ON cp.account_id = a.id
WHERE a.id = $1::uuid
`

type GetPersonalExportAccountRow struct {
	ID                   pgtype.UUID
	Email                string
	Status               string
	EmailVerifiedAt      pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	Username             pgtype.Text
	InterfaceLocale      pgtype.Text
	Timezone             pgtype.Text
	ProfileCreatedAt     pgtype.Timestamptz
	ProfileUpdatedAt     pgtype.Timestamptz
	MarketingOptIn       pgtype.Bool
	PreferencesUpdatedAt pgtype.Timestamptz
}

// GetPersonalExportAccount loads the account identity plus the optional
// profile and communication preferences. Email belongs to the private
// export and never to a public projection.
func (q *Queries) GetPersonalExportAccount(ctx context.Context, accountID pgtype.UUID) (GetPersonalExportAccountRow, error) {
	row := q.db.QueryRow(ctx, getPersonalExportAccount, accountID)
	var i GetPersonalExportAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.Username,
		&i.InterfaceLocale,
		&i.Timezone,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
		&i.MarketingOptIn,
		&i.PreferencesUpdatedAt,
	)
	return i, err
}

const getPersonalExportDownloadGuard = `-- name: GetPersonalExportDownloadGuard :one
SELECT id, account_id, status, expires_at, download_count, max_downloads, download_token_hash
FROM app.data_exports
WHERE id = $1::uuid
  AND account_id = $2::uuid
`

type GetPersonalExportDownloadGuardParams struct {
	ExportID  pgtype.UUID
	AccountID pgtype.UUID
}

type GetPersonalExportDownloadGuardRow struct {
	ID                pgtype.UUID
	AccountID         pgtype.UUID
	Status            string
	ExpiresAt         pgtype.Timestamptz
	DownloadCount     int32
	MaxDownloads      int32
	DownloadTokenHash []byte
}

// GetPersonalExportDownloadGuard loads the owner-scoped download state so
// the application can classify unknown/foreign records apart from invalid
// tokens and unavailable links without ever reflecting whether a foreign
// export exists.
func (q *Queries) GetPersonalExportDownloadGuard(ctx context.Context, arg GetPersonalExportDownloadGuardParams) (GetPersonalExportDownloadGuardRow, error) {
	row := q.db.QueryRow(ctx, getPersonalExportDownloadGuard, arg.ExportID, arg.AccountID)
	var i GetPersonalExportDownloadGuardRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.ExpiresAt,
		&i.DownloadCount,
		&i.MaxDownloads,
		&i.DownloadTokenHash,
	)
	return i, err
}

const getPersonalExportForGeneration = `-- name: GetPersonalExportForGeneration :one
SELECT id, account_id, status, requested_at, generated_at, expires_at, download_count, max_downloads
FROM app.data_exports
WHERE id = $1::uuid
`

type GetPersonalExportForGenerationRow struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	Status        string
	RequestedAt   pgtype.Timestamptz
	GeneratedAt   pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	DownloadCount int32
	MaxDownloads  int32
}

// GetPersonalExportForGeneration loads one export record for the generation
// job. The token hash is deliberately not returned: generation never needs
// the capability.
func (q *Queries) GetPersonalExportForGeneration(ctx context.Context, exportID pgtype.UUID) (GetPersonalExportForGenerationRow, error) {
	row := q.db.QueryRow(ctx, getPersonalExportForGeneration, exportID)
	var i GetPersonalExportForGenerationRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.RequestedAt,
		&i.GeneratedAt,
		&i.ExpiresAt,
		&i.DownloadCount,
		&i.MaxDownloads,
	)
	return i, err
}

const getPersonalExportWallet = `-- name: GetPersonalExportWallet :one
SELECT balance_free, balance_purchased
FROM app.wallet_accounts
WHERE account_id = $1::uuid
`

type GetPersonalExportWalletRow struct {
	BalanceFree      int64
	BalancePurchased int64
}

// GetPersonalExportWallet returns the account's derived INK balances. An
// account that never used the wallet has no row; the application reports
// zeroed balances.
func (q *Queries) GetPersonalExportWallet(ctx context.Context, accountID pgtype.UUID) (GetPersonalExportWalletRow, error) {
	row := q.db.QueryRow(ctx, getPersonalExportWallet, accountID)
	var i GetPersonalExportWalletRow
	err := row.Scan(&i.BalanceFree, &i.BalancePurchased)
	return i, err
}

const listPersonalExportArenaDrafts = `-- name: ListPersonalExportArenaDrafts :many
SELECT id, statement, context, category, language, version, created_at
FROM app.arenas
WHERE creator_id = $1::uuid
  AND status = 'draft'
ORDER BY created_at, id
`

type ListPersonalExportArenaDraftsRow struct {
	ID        pgtype.UUID
	Statement string
	Context   pgtype.Text
	Category  string
	Language  string
	Version   int32
	CreatedAt pgtype.Timestamptz
}

// ListPersonalExportArenaDrafts returns the account's unpublished drafts:
// private data that only exists in the personal export.
func (q *Queries) ListPersonalExportArenaDrafts(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportArenaDraftsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportArenaDrafts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportArenaDraftsRow{}
	for rows.Next() {
		var i ListPersonalExportArenaDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.Statement,
			&i.Context,
			&i.Category,
			&i.Language,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportArgumentSources = `-- name: ListPersonalExportArgumentSources :many
SELECT argument_id, url, description
FROM app.argument_sources
WHERE argument_id = ANY($1::uuid[])
ORDER BY created_at, id
`

type ListPersonalExportArgumentSourcesRow struct {
	ArgumentID  pgtype.UUID
	Url         string
	Description pgtype.Text
}

// ListPersonalExportArgumentSources returns the sources of the given
// arguments in deterministic order.
func (q *Queries) ListPersonalExportArgumentSources(ctx context.Context, argumentIds []pgtype.UUID) ([]ListPersonalExportArgumentSourcesRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportArgumentSources, argumentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportArgumentSourcesRow{}
	for rows.Next() {
		var i ListPersonalExportArgumentSourcesRow
		if err := rows.Scan(&i.ArgumentID, &i.Url, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportArguments = `-- name: ListPersonalExportArguments :many
SELECT id, arena_id, parent_id, relation, content, status, created_at, withdrawn_at
FROM app.arguments
WHERE author_id = $1::uuid
  AND status IN ('published', 'withdrawn')
ORDER BY created_at, id
`

type ListPersonalExportArgumentsRow struct {
	ID          pgtype.UUID
	ArenaID     pgtype.UUID
	ParentID    pgtype.UUID
	Relation    string
	Content     string
	Status      string
	CreatedAt   pgtype.Timestamptz
	WithdrawnAt pgtype.Timestamptz
}

// ListPersonalExportArguments returns the account's own arguments and
// replies, published and withdrawn. Moderation-removed content is restricted
// evidence and stays out; the placeholder status is not part of the personal
// export either.
func (q *Queries) ListPersonalExportArguments(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportArgumentsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportArguments, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportArgumentsRow{}
	for rows.Next() {
		var i ListPersonalExportArgumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArenaID,
			&i.ParentID,
			&i.Relation,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportCheckoutIntents = `-- name: ListPersonalExportCheckoutIntents :many
SELECT product_id, market, currency, amount_minor, status, created_at, paid_at
FROM app.checkout_intents
WHERE account_id = $1::uuid
ORDER BY created_at, id
`

type ListPersonalExportCheckoutIntentsRow struct {
	ProductID   string
	Market      string
	Currency    string
	AmountMinor int64
	Status      string
	CreatedAt   pgtype.Timestamptz
	PaidAt      pgtype.Timestamptz
}

// ListPersonalExportCheckoutIntents returns the account's local purchase
// history: product, market, amount and status only. Provider session and
// payment identifiers stay out of every export.
func (q *Queries) ListPersonalExportCheckoutIntents(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportCheckoutIntentsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportCheckoutIntents, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportCheckoutIntentsRow{}
	for rows.Next() {
		var i ListPersonalExportCheckoutIntentsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Market,
			&i.Currency,
			&i.AmountMinor,
			&i.Status,
			&i.CreatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportPassConsumptions = `-- name: ListPersonalExportPassConsumptions :many
SELECT c.arena_id, c.consumed_at
FROM app.arena_pass_consumptions c
JOIN app.arena_pass_lots l ON l.id = c.lot_id
WHERE l.account_id = $1::uuid
ORDER BY c.consumed_at, c.id
`

type ListPersonalExportPassConsumptionsRow struct {
	ArenaID    pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

// ListPersonalExportPassConsumptions returns the account's pass
// consumptions, oldest first.
func (q *Queries) ListPersonalExportPassConsumptions(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportPassConsumptionsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportPassConsumptions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportPassConsumptionsRow{}
	for rows.Next() {
		var i ListPersonalExportPassConsumptionsRow
		if err := rows.Scan(&i.ArenaID, &i.ConsumedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportPassLots = `-- name: ListPersonalExportPassLots :many
SELECT origin, quantity, remaining_quantity, expires_at, created_at
FROM app.arena_pass_lots
WHERE account_id = $1::uuid
ORDER BY created_at, id
`

type ListPersonalExportPassLotsRow struct {
	Origin            string
	Quantity          int32
	RemainingQuantity int32
	ExpiresAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

// ListPersonalExportPassLots returns the account's Arena Pass lots without
// the grant reference, which may embed provider or subscription
// identifiers.
func (q *Queries) ListPersonalExportPassLots(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportPassLotsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportPassLots, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportPassLotsRow{}
	for rows.Next() {
		var i ListPersonalExportPassLotsRow
		if err := rows.Scan(
			&i.Origin,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportPositionChanges = `-- name: ListPersonalExportPositionChanges :many
SELECT arena_id, from_position, to_position, version, changed_at
FROM app.position_changes
WHERE account_id = $1::uuid
ORDER BY changed_at, id
`

type ListPersonalExportPositionChangesRow struct {
	ArenaID      pgtype.UUID
	FromPosition string
	ToPosition   string
	Version      int32
	ChangedAt    pgtype.Timestamptz
}

// ListPersonalExportPositionChanges returns the account's individual change
// history, oldest first.
func (q *Queries) ListPersonalExportPositionChanges(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportPositionChangesRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportPositionChanges, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportPositionChangesRow{}
	for rows.Next() {
		var i ListPersonalExportPositionChangesRow
		if err := rows.Scan(
			&i.ArenaID,
			&i.FromPosition,
			&i.ToPosition,
			&i.Version,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportPositions = `-- name: ListPersonalExportPositions :many
SELECT
    dp.arena_id, ar.slug, ar.statement,
    dp.initial_position, dp.current_position, dp.version,
    dp.created_at, dp.updated_at
FROM app.debate_positions dp
JOIN app.arenas ar ON ar.id = dp.arena_id
WHERE dp.account_id = $1::uuid
ORDER BY dp.created_at, dp.arena_id
`

type ListPersonalExportPositionsRow struct {
	ArenaID         pgtype.UUID
	Slug            pgtype.Text
	Statement       string
	InitialPosition string
	CurrentPosition string
	Version         int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// ListPersonalExportPositions returns the account's individual positions,
// with the Arena identity as context needed to understand them.
func (q *Queries) ListPersonalExportPositions(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportPositionsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportPositions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportPositionsRow{}
	for rows.Next() {
		var i ListPersonalExportPositionsRow
		if err := rows.Scan(
			&i.ArenaID,
			&i.Slug,
			&i.Statement,
			&i.InitialPosition,
			&i.CurrentPosition,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportSessions = `-- name: ListPersonalExportSessions :many
SELECT id, created_at, expires_at, revoked_at
FROM app.sessions
WHERE account_id = $1::uuid
ORDER BY created_at, id
`

type ListPersonalExportSessionsRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

// ListPersonalExportSessions returns the account's own sessions without
// device signals: the IP address and user agent are restricted security
// data and never enter the export.
func (q *Queries) ListPersonalExportSessions(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportSessionsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportSessionsRow{}
	for rows.Next() {
		var i ListPersonalExportSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportSubscriptions = `-- name: ListPersonalExportSubscriptions :many
SELECT product_id, status, current_period_start, current_period_end,
       cancel_at_period_end, created_at, updated_at
FROM app.subscriptions
WHERE account_id = $1::uuid
ORDER BY created_at, id
`

type ListPersonalExportSubscriptionsRow struct {
	ProductID          string
	Status             string
	CurrentPeriodStart pgtype.Timestamptz
	CurrentPeriodEnd   pgtype.Timestamptz
	CancelAtPeriodEnd  bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// ListPersonalExportSubscriptions returns the account's subscriptions with
// periods and cancellation state, never provider or price identifiers.
func (q *Queries) ListPersonalExportSubscriptions(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportSubscriptions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportSubscriptionsRow{}
	for rows.Next() {
		var i ListPersonalExportSubscriptionsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelAtPeriodEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportUsernameHistory = `-- name: ListPersonalExportUsernameHistory :many
SELECT username, changed_at
FROM app.username_history
WHERE account_id = $1::uuid
ORDER BY changed_at, id
`

type ListPersonalExportUsernameHistoryRow struct {
	Username  string
	ChangedAt pgtype.Timestamptz
}

// ListPersonalExportUsernameHistory returns every username the account ever
// held, oldest first.
func (q *Queries) ListPersonalExportUsernameHistory(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportUsernameHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportUsernameHistory, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportUsernameHistoryRow{}
	for rows.Next() {
		var i ListPersonalExportUsernameHistoryRow
		if err := rows.Scan(&i.Username, &i.ChangedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalExportWalletTransactions = `-- name: ListPersonalExportWalletTransactions :many
SELECT o.operation_type, t.bucket, t.amount, t.created_at
FROM app.wallet_transactions t
JOIN app.wallet_operations o ON o.id = t.operation_id
WHERE o.account_id = $1::uuid
ORDER BY t.created_at, t.id
`

type ListPersonalExportWalletTransactionsRow struct {
	OperationType string
	Bucket        string
	Amount        int64
	CreatedAt     pgtype.Timestamptz
}

// ListPersonalExportWalletTransactions returns the account's INK ledger:
// signed bucket deltas only. The operation reference (which may embed
// provider identifiers) is never selected.
func (q *Queries) ListPersonalExportWalletTransactions(ctx context.Context, accountID pgtype.UUID) ([]ListPersonalExportWalletTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listPersonalExportWalletTransactions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalExportWalletTransactionsRow{}
	for rows.Next() {
		var i ListPersonalExportWalletTransactionsRow
		if err := rows.Scan(
			&i.OperationType,
			&i.Bucket,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPersonalExportReady = `-- name: MarkPersonalExportReady :execrows
UPDATE app.data_exports
SET status = 'ready',
    generated_at = $1::timestamptz,
    expires_at = $2::timestamptz,
    document = $3::text,
    document_sha256 = $4::text,
    updated_at = $1::timestamptz
WHERE id = $5::uuid
  AND status = 'requested'
`

type MarkPersonalExportReadyParams struct {
	GeneratedAt    pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	Document       string
	DocumentSha256 string
	ExportID       pgtype.UUID
}

// MarkPersonalExportReady attaches the generated document once. The status
// guard resolves concurrent generations: only the first writer wins and the
// loser resolves the recorded replay.
func (q *Queries) MarkPersonalExportReady(ctx context.Context, arg MarkPersonalExportReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPersonalExportReady,
		arg.GeneratedAt,
		arg.ExpiresAt,
		arg.Document,
		arg.DocumentSha256,
		arg.ExportID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestPersonalExport = `-- name: RequestPersonalExport :one
INSERT INTO app.data_exports (
    account_id, status, download_token_hash, download_count, max_downloads,
    requested_at, updated_at
)
VALUES (
    $1::uuid,
    'requested',
    $2::bytea,
    0,
    $3::integer,
    $4::timestamptz,
    $4::timestamptz
)
ON CONFLICT (account_id) WHERE status IN ('requested', 'ready')
DO UPDATE SET
    download_token_hash = EXCLUDED.download_token_hash,
    download_count = 0,
    last_downloaded_at = NULL,
    updated_at = EXCLUDED.updated_at
RETURNING id, account_id, status, requested_at, generated_at, expires_at, download_count, max_downloads
`

type RequestPersonalExportParams struct {
	AccountID         pgtype.UUID
	DownloadTokenHash []byte
	MaxDownloads      int32
	RequestedAt       pgtype.Timestamptz
}

type RequestPersonalExportRow struct {
	ID            pgtype.UUID
	AccountID     pgtype.UUID
	Status        string
	RequestedAt   pgtype.Timestamptz
	GeneratedAt   pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	DownloadCount int32
	MaxDownloads  int32
}

// RequestPersonalExport creates the account's active export or rotates the
// token of the existing one. The partial unique index resolves concurrent
// re-requests: the winner keeps one active record and every caller receives
// it.
func (q *Queries) RequestPersonalExport(ctx context.Context, arg RequestPersonalExportParams) (RequestPersonalExportRow, error) {
	row := q.db.QueryRow(ctx, requestPersonalExport,
		arg.AccountID,
		arg.DownloadTokenHash,
		arg.MaxDownloads,
		arg.RequestedAt,
	)
	var i RequestPersonalExportRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.RequestedAt,
		&i.GeneratedAt,
		&i.ExpiresAt,
		&i.DownloadCount,
		&i.MaxDownloads,
	)
	return i, err
}
