// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: persuasion.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttribution = `-- name: CreateAttribution :one
INSERT INTO app.persuasion_attributions (position_change_id, attributor_id, argument_id)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid
)
ON CONFLICT (position_change_id, argument_id) DO NOTHING
RETURNING id
`

type CreateAttributionParams struct {
	ChangeID     pgtype.UUID
	AttributorID pgtype.UUID
	ArgumentID   pgtype.UUID
}

// CreateAttribution records one attribution under the unique
// (change, argument) pair: a retry inserts nothing and resolves the replay
// (P11-T03).
func (q *Queries) CreateAttribution(ctx context.Context, arg CreateAttributionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAttribution, arg.ChangeID, arg.AttributorID, arg.ArgumentID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getArgumentAttributionMetrics = `-- name: GetArgumentAttributionMetrics :one
SELECT
    count(pa.argument_id)::bigint AS valid_attributions,
    count(DISTINCT pa.attributor_id)::bigint AS distinct_people
FROM app.arguments a
LEFT JOIN app.persuasion_attributions pa
    ON pa.argument_id = a.id
   AND pa.status = 'valid'
   AND EXISTS (
       SELECT 1
       FROM app.accounts attributor
       WHERE attributor.id = pa.attributor_id
         AND attributor.status = 'active'
         AND attributor.email_verified_at IS NOT NULL
   )
WHERE a.id = $1::uuid
GROUP BY a.id
`

type GetArgumentAttributionMetricsRow struct {
	ValidAttributions int64
	DistinctPeople    int64
}

// GetArgumentAttributionMetrics derives the public count facts of one
// argument (P11-T06; BR §5.1, §6, §7): the valid attribution events it
// received and the eligible people who credited it, each person counted
// once per argument. Rules encoded here:
//  1. Only valid attributions count, exactly as the reputation projection
//     (BR §6): an invalidated attribution never integrates a valid total.
//  2. Eligible attributor means an active account with a verified email
//     (BR §7), the same predicate the professional aggregates use.
//  3. The LEFT JOIN keeps an argument with no eligible attribution
//     representable (zeros) while a missing argument still returns no row,
//     so the adapter can distinguish "no counts" from "no argument".
//  4. Counts are facts, not state: withdrawing or removing the argument
//     does not rewrite them (BR §10).
//
// The result carries counts only — attributor identities never leave the
// database.
func (q *Queries) GetArgumentAttributionMetrics(ctx context.Context, argumentID pgtype.UUID) (GetArgumentAttributionMetricsRow, error) {
	row := q.db.QueryRow(ctx, getArgumentAttributionMetrics, argumentID)
	var i GetArgumentAttributionMetricsRow
	err := row.Scan(&i.ValidAttributions, &i.DistinctPeople)
	return i, err
}

const getAttributionForModeration = `-- name: GetAttributionForModeration :one
SELECT id, position_change_id, attributor_id, argument_id, status, created_at,
       moderation_reason, moderated_by, moderated_at
FROM app.persuasion_attributions
WHERE id = $1::uuid
FOR UPDATE
`

type GetAttributionForModerationRow struct {
	ID               pgtype.UUID
	PositionChangeID pgtype.UUID
	AttributorID     pgtype.UUID
	ArgumentID       pgtype.UUID
	Status           string
	CreatedAt        pgtype.Timestamptz
	ModerationReason pgtype.Text
	ModeratedBy      pgtype.UUID
	ModeratedAt      pgtype.Timestamptz
}

// GetAttributionForModeration loads one attribution with its current
// validity and its latest moderation decision and locks it FOR UPDATE, so
// concurrent decisions on the same row serialize instead of overwriting
// each other (P11-T04). It is the moderation read projection: a consumer
// reads validity from the retained row that the schema keeps coherent with
// the decision record, so no projection can observe an unrecorded
// invalidation.
func (q *Queries) GetAttributionForModeration(ctx context.Context, attributionID pgtype.UUID) (GetAttributionForModerationRow, error) {
	row := q.db.QueryRow(ctx, getAttributionForModeration, attributionID)
	var i GetAttributionForModerationRow
	err := row.Scan(
		&i.ID,
		&i.PositionChangeID,
		&i.AttributorID,
		&i.ArgumentID,
		&i.Status,
		&i.CreatedAt,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const getPositionChangeForAttributor = `-- name: GetPositionChangeForAttributor :one
SELECT id, arena_id, account_id, changed_at
FROM app.position_changes
WHERE id = $1::uuid
  AND account_id = $2::uuid
FOR UPDATE
`

type GetPositionChangeForAttributorParams struct {
	ChangeID     pgtype.UUID
	AttributorID pgtype.UUID
}

type GetPositionChangeForAttributorRow struct {
	ID        pgtype.UUID
	ArenaID   pgtype.UUID
	AccountID pgtype.UUID
	ChangedAt pgtype.Timestamptz
}

// GetPositionChangeForAttributor loads one position change scoped to its
// account and locks it FOR UPDATE: attribution recording serializes per
// change, so the cumulative three-argument limit cannot be bypassed by
// concurrent requests (P11-T03). Reading the change row is the approved
// read-only projection over the positions schema.
func (q *Queries) GetPositionChangeForAttributor(ctx context.Context, arg GetPositionChangeForAttributorParams) (GetPositionChangeForAttributorRow, error) {
	row := q.db.QueryRow(ctx, getPositionChangeForAttributor, arg.ChangeID, arg.AttributorID)
	var i GetPositionChangeForAttributorRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AccountID,
		&i.ChangedAt,
	)
	return i, err
}

const invalidateAttribution = `-- name: InvalidateAttribution :one
UPDATE app.persuasion_attributions
SET status = 'invalid',
    invalidated_at = $1::timestamptz,
    moderation_reason = $2::text,
    moderated_by = $3::uuid,
    moderated_at = $1::timestamptz
WHERE id = $4::uuid
  AND status = 'valid'
RETURNING id, position_change_id, attributor_id, argument_id, status, created_at,
          moderation_reason, moderated_by, moderated_at
`

type InvalidateAttributionParams struct {
	DecidedAt     pgtype.Timestamptz
	Reason        string
	ModeratorID   pgtype.UUID
	AttributionID pgtype.UUID
}

type InvalidateAttributionRow struct {
	ID               pgtype.UUID
	PositionChangeID pgtype.UUID
	AttributorID     pgtype.UUID
	ArgumentID       pgtype.UUID
	Status           string
	CreatedAt        pgtype.Timestamptz
	ModerationReason pgtype.Text
	ModeratedBy      pgtype.UUID
	ModeratedAt      pgtype.Timestamptz
}

// InvalidateAttribution moves a valid attribution to invalid, recording the
// actor, the mandatory reason and the instant on the retained row; nothing
// is deleted. The status guard loses the race instead of overwriting a
// concurrent decision.
func (q *Queries) InvalidateAttribution(ctx context.Context, arg InvalidateAttributionParams) (InvalidateAttributionRow, error) {
	row := q.db.QueryRow(ctx, invalidateAttribution,
		arg.DecidedAt,
		arg.Reason,
		arg.ModeratorID,
		arg.AttributionID,
	)
	var i InvalidateAttributionRow
	err := row.Scan(
		&i.ID,
		&i.PositionChangeID,
		&i.AttributorID,
		&i.ArgumentID,
		&i.Status,
		&i.CreatedAt,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}

const listAttributionArgumentIDs = `-- name: ListAttributionArgumentIDs :many
SELECT argument_id
FROM app.persuasion_attributions
WHERE position_change_id = $1::uuid
ORDER BY created_at, argument_id
`

// ListAttributionArgumentIDs returns the argument identifiers already
// credited by one change (P11-T03).
func (q *Queries) ListAttributionArgumentIDs(ctx context.Context, changeID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAttributionArgumentIDs, changeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var argument_id pgtype.UUID
		if err := rows.Scan(&argument_id); err != nil {
			return nil, err
		}
		items = append(items, argument_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributionCandidates = `-- name: ListAttributionCandidates :many
SELECT id, arena_id, author_id, created_at, status
FROM app.arguments
WHERE id = ANY($1::uuid[])
`

type ListAttributionCandidatesRow struct {
	ID        pgtype.UUID
	ArenaID   pgtype.UUID
	AuthorID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Status    string
}

// ListAttributionCandidates loads the eligibility inputs of the proposed
// arguments: arena, author, creation instant and status. Relation is
// deliberately not read: it never restricts eligibility (P11-T02).
func (q *Queries) ListAttributionCandidates(ctx context.Context, argumentIds []pgtype.UUID) ([]ListAttributionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAttributionCandidates, argumentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttributionCandidatesRow{}
	for rows.Next() {
		var i ListAttributionCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ArenaID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorArenaReputation = `-- name: ListAuthorArenaReputation :many
SELECT
    ar.id AS arena_id,
    ar.category,
    ar.language,
    count(DISTINCT pa.attributor_id)::bigint AS distinct_people,
    count(*)::bigint AS valid_attributions
FROM app.persuasion_attributions pa
JOIN app.arguments a ON a.id = pa.argument_id
JOIN app.arenas ar ON ar.id = a.arena_id
JOIN app.accounts attributor ON attributor.id = pa.attributor_id
    AND attributor.status = 'active'
    AND attributor.email_verified_at IS NOT NULL
WHERE a.author_id = $1::uuid
  AND pa.status = 'valid'
GROUP BY ar.id, ar.category, ar.language
ORDER BY ar.id
`

type ListAuthorArenaReputationRow struct {
	ArenaID           pgtype.UUID
	Category          string
	Language          string
	DistinctPeople    int64
	ValidAttributions int64
}

// ListAuthorArenaReputation derives the reputation projection of one
// author (P11-T05; BR §5.1, §6, §7): one row per Arena where the author
// received at least one valid attribution, with the eligible people the
// author influenced there and the valid attribution events received there.
//
// Rules encoded here:
//  1. Only valid attributions count: invalidated ones never integrate the
//     valid totals (BR §6) and the row is retained for the administrative
//     trail (P11-T04).
//  2. DistinctPeople counts eligible attributors once per author and
//     Arena (BR §6), so repeated attributions by the same person never
//     inflate the headline.
//  3. Eligible attributor means an active account with a verified email
//     (BR §7), the same predicate the professional aggregates use.
//  4. Attribution events are facts: withdrawing or removing an argument
//     does not rewrite historical counts (BR §10); the attribution itself
//     is the exclusion unit.
//
// The result carries counts only — attributor identifiers never leave the
// database.
func (q *Queries) ListAuthorArenaReputation(ctx context.Context, authorID pgtype.UUID) ([]ListAuthorArenaReputationRow, error) {
	rows, err := q.db.Query(ctx, listAuthorArenaReputation, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorArenaReputationRow{}
	for rows.Next() {
		var i ListAuthorArenaReputationRow
		if err := rows.Scan(
			&i.ArenaID,
			&i.Category,
			&i.Language,
			&i.DistinctPeople,
			&i.ValidAttributions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAuthorByUsername = `-- name: ResolveAuthorByUsername :one
SELECT account_id, username
FROM app.profiles
WHERE username_normalized = lower($1::text)
`

type ResolveAuthorByUsernameRow struct {
	AccountID pgtype.UUID
	Username  string
}

// ResolveAuthorByUsername resolves a public username to the author identity
// used by the reputation projection (P11-T06). Resolution is read-only over
// the profiles projection and matches the canonical normalized username,
// the only authority key of profile lookups (P05-T01): no profile field
// crosses the port, only the resolved identity does. A username that owns no
// profile returns no rows, which the adapter reports as ErrProfileNotFound.
func (q *Queries) ResolveAuthorByUsername(ctx context.Context, username string) (ResolveAuthorByUsernameRow, error) {
	row := q.db.QueryRow(ctx, resolveAuthorByUsername, username)
	var i ResolveAuthorByUsernameRow
	err := row.Scan(&i.AccountID, &i.Username)
	return i, err
}

const restoreAttribution = `-- name: RestoreAttribution :one
UPDATE app.persuasion_attributions
SET status = 'valid',
    invalidated_at = NULL,
    moderation_reason = $1::text,
    moderated_by = $2::uuid,
    moderated_at = $3::timestamptz
WHERE id = $4::uuid
  AND status = 'invalid'
RETURNING id, position_change_id, attributor_id, argument_id, status, created_at,
          moderation_reason, moderated_by, moderated_at
`

type RestoreAttributionParams struct {
	Reason        string
	ModeratorID   pgtype.UUID
	DecidedAt     pgtype.Timestamptz
	AttributionID pgtype.UUID
}

type RestoreAttributionRow struct {
	ID               pgtype.UUID
	PositionChangeID pgtype.UUID
	AttributorID     pgtype.UUID
	ArgumentID       pgtype.UUID
	Status           string
	CreatedAt        pgtype.Timestamptz
	ModerationReason pgtype.Text
	ModeratedBy      pgtype.UUID
	ModeratedAt      pgtype.Timestamptz
}

// RestoreAttribution reverses one invalidation on the same retained row,
// recording the restore decision: the row moves back to valid and the
// decision record is replaced by the newest one, never erased.
func (q *Queries) RestoreAttribution(ctx context.Context, arg RestoreAttributionParams) (RestoreAttributionRow, error) {
	row := q.db.QueryRow(ctx, restoreAttribution,
		arg.Reason,
		arg.ModeratorID,
		arg.DecidedAt,
		arg.AttributionID,
	)
	var i RestoreAttributionRow
	err := row.Scan(
		&i.ID,
		&i.PositionChangeID,
		&i.AttributorID,
		&i.ArgumentID,
		&i.Status,
		&i.CreatedAt,
		&i.ModerationReason,
		&i.ModeratedBy,
		&i.ModeratedAt,
	)
	return i, err
}
