// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: persuasion.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttribution = `-- name: CreateAttribution :one
INSERT INTO app.persuasion_attributions (position_change_id, attributor_id, argument_id)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid
)
ON CONFLICT (position_change_id, argument_id) DO NOTHING
RETURNING id
`

type CreateAttributionParams struct {
	ChangeID     pgtype.UUID
	AttributorID pgtype.UUID
	ArgumentID   pgtype.UUID
}

// CreateAttribution records one attribution under the unique
// (change, argument) pair: a retry inserts nothing and resolves the replay
// (P11-T03).
func (q *Queries) CreateAttribution(ctx context.Context, arg CreateAttributionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAttribution, arg.ChangeID, arg.AttributorID, arg.ArgumentID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPositionChangeForAttributor = `-- name: GetPositionChangeForAttributor :one
SELECT id, arena_id, account_id, changed_at
FROM app.position_changes
WHERE id = $1::uuid
  AND account_id = $2::uuid
FOR UPDATE
`

type GetPositionChangeForAttributorParams struct {
	ChangeID     pgtype.UUID
	AttributorID pgtype.UUID
}

type GetPositionChangeForAttributorRow struct {
	ID        pgtype.UUID
	ArenaID   pgtype.UUID
	AccountID pgtype.UUID
	ChangedAt pgtype.Timestamptz
}

// GetPositionChangeForAttributor loads one position change scoped to its
// account and locks it FOR UPDATE: attribution recording serializes per
// change, so the cumulative three-argument limit cannot be bypassed by
// concurrent requests (P11-T03). Reading the change row is the approved
// read-only projection over the positions schema.
func (q *Queries) GetPositionChangeForAttributor(ctx context.Context, arg GetPositionChangeForAttributorParams) (GetPositionChangeForAttributorRow, error) {
	row := q.db.QueryRow(ctx, getPositionChangeForAttributor, arg.ChangeID, arg.AttributorID)
	var i GetPositionChangeForAttributorRow
	err := row.Scan(
		&i.ID,
		&i.ArenaID,
		&i.AccountID,
		&i.ChangedAt,
	)
	return i, err
}

const listAttributionArgumentIDs = `-- name: ListAttributionArgumentIDs :many
SELECT argument_id
FROM app.persuasion_attributions
WHERE position_change_id = $1::uuid
ORDER BY created_at, argument_id
`

// ListAttributionArgumentIDs returns the argument identifiers already
// credited by one change (P11-T03).
func (q *Queries) ListAttributionArgumentIDs(ctx context.Context, changeID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAttributionArgumentIDs, changeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var argument_id pgtype.UUID
		if err := rows.Scan(&argument_id); err != nil {
			return nil, err
		}
		items = append(items, argument_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributionCandidates = `-- name: ListAttributionCandidates :many
SELECT id, arena_id, author_id, created_at, status
FROM app.arguments
WHERE id = ANY($1::uuid[])
`

type ListAttributionCandidatesRow struct {
	ID        pgtype.UUID
	ArenaID   pgtype.UUID
	AuthorID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Status    string
}

// ListAttributionCandidates loads the eligibility inputs of the proposed
// arguments: arena, author, creation instant and status. Relation is
// deliberately not read: it never restricts eligibility (P11-T02).
func (q *Queries) ListAttributionCandidates(ctx context.Context, argumentIds []pgtype.UUID) ([]ListAttributionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAttributionCandidates, argumentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttributionCandidatesRow{}
	for rows.Next() {
		var i ListAttributionCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ArenaID,
			&i.AuthorID,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
