// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: positions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmInitialPosition = `-- name: ConfirmInitialPosition :one
INSERT INTO app.debate_positions (arena_id, account_id, initial_position, current_position, created_at, updated_at)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $3::text,
    $4::timestamptz,
    $4::timestamptz
)
ON CONFLICT (arena_id, account_id) DO NOTHING
RETURNING arena_id, account_id, initial_position, current_position, version, created_at, updated_at
`

type ConfirmInitialPositionParams struct {
	ArenaID   pgtype.UUID
	AccountID pgtype.UUID
	Position  string
	At        pgtype.Timestamptz
}

// ConfirmInitialPosition inserts the initial projection of one account in
// one Arena. The primary key (arena_id, account_id) resolves concurrent
// confirmations: the loser inserts nothing and re-reads the winner (P09-T03).
func (q *Queries) ConfirmInitialPosition(ctx context.Context, arg ConfirmInitialPositionParams) (AppDebatePosition, error) {
	row := q.db.QueryRow(ctx, confirmInitialPosition,
		arg.ArenaID,
		arg.AccountID,
		arg.Position,
		arg.At,
	)
	var i AppDebatePosition
	err := row.Scan(
		&i.ArenaID,
		&i.AccountID,
		&i.InitialPosition,
		&i.CurrentPosition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countEligiblePositionsByArena = `-- name: CountEligiblePositionsByArena :one
SELECT
    count(*)::bigint AS total,
    count(*) FILTER (WHERE dp.initial_position = 'agree')::bigint AS initial_agree,
    count(*) FILTER (WHERE dp.initial_position = 'disagree')::bigint AS initial_disagree,
    count(*) FILTER (WHERE dp.initial_position = 'undecided')::bigint AS initial_undecided,
    count(*) FILTER (WHERE dp.current_position = 'agree')::bigint AS current_agree,
    count(*) FILTER (WHERE dp.current_position = 'disagree')::bigint AS current_disagree,
    count(*) FILTER (WHERE dp.current_position = 'undecided')::bigint AS current_undecided
FROM app.debate_positions dp
JOIN app.accounts a ON a.id = dp.account_id AND a.status = 'active'
WHERE dp.arena_id = $1::uuid
`

type CountEligiblePositionsByArenaRow struct {
	Total            int64
	InitialAgree     int64
	InitialDisagree  int64
	InitialUndecided int64
	CurrentAgree     int64
	CurrentDisagree  int64
	CurrentUndecided int64
}

// CountEligiblePositionsByArena derives the public aggregate of one Arena:
// the initial and current distributions over eligible participants plus the
// eligible total. This is the explicitly approved read-only projection of
// ARCHITECTURE.md §4 and it follows docs/BUSINESS_RULES.md §7: only active
// accounts count, so suspended, pending and deleted accounts (and any future
// review invalidation) stay out of the official totals. The result carries
// counts only — account identifiers never leave the database (P09-T05).
func (q *Queries) CountEligiblePositionsByArena(ctx context.Context, arenaID pgtype.UUID) (CountEligiblePositionsByArenaRow, error) {
	row := q.db.QueryRow(ctx, countEligiblePositionsByArena, arenaID)
	var i CountEligiblePositionsByArenaRow
	err := row.Scan(
		&i.Total,
		&i.InitialAgree,
		&i.InitialDisagree,
		&i.InitialUndecided,
		&i.CurrentAgree,
		&i.CurrentDisagree,
		&i.CurrentUndecided,
	)
	return i, err
}

const createPositionChange = `-- name: CreatePositionChange :one
INSERT INTO app.position_changes (arena_id, account_id, from_position, to_position, version, changed_at)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text,
    $5::integer,
    $6::timestamptz
)
RETURNING id
`

type CreatePositionChangeParams struct {
	ArenaID      pgtype.UUID
	AccountID    pgtype.UUID
	FromPosition string
	ToPosition   string
	Version      int32
	ChangedAt    pgtype.Timestamptz
}

// CreatePositionChange appends one change to the immutable history chain.
// The unique (arena_id, account_id, version) constraint resolves concurrent
// changes: only the chain tip advances (P09-T04).
func (q *Queries) CreatePositionChange(ctx context.Context, arg CreatePositionChangeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPositionChange,
		arg.ArenaID,
		arg.AccountID,
		arg.FromPosition,
		arg.ToPosition,
		arg.Version,
		arg.ChangedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getDebatePosition = `-- name: GetDebatePosition :one
SELECT arena_id, account_id, initial_position, current_position, version, created_at, updated_at
FROM app.debate_positions
WHERE arena_id = $1 AND account_id = $2
`

type GetDebatePositionParams struct {
	ArenaID   pgtype.UUID
	AccountID pgtype.UUID
}

// GetDebatePosition returns the private projection of one account in one
// Arena.
func (q *Queries) GetDebatePosition(ctx context.Context, arg GetDebatePositionParams) (AppDebatePosition, error) {
	row := q.db.QueryRow(ctx, getDebatePosition, arg.ArenaID, arg.AccountID)
	var i AppDebatePosition
	err := row.Scan(
		&i.ArenaID,
		&i.AccountID,
		&i.InitialPosition,
		&i.CurrentPosition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPositionChanges = `-- name: ListPositionChanges :many
SELECT id, arena_id, account_id, from_position, to_position, version, changed_at
FROM app.position_changes
WHERE arena_id = $1::uuid
  AND account_id = $2::uuid
ORDER BY version DESC
`

type ListPositionChangesParams struct {
	ArenaID   pgtype.UUID
	AccountID pgtype.UUID
}

// ListPositionChanges returns the private change history of one account in
// one Arena, newest first; the chain order is the version (P09-T06).
func (q *Queries) ListPositionChanges(ctx context.Context, arg ListPositionChangesParams) ([]AppPositionChange, error) {
	rows, err := q.db.Query(ctx, listPositionChanges, arg.ArenaID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPositionChange{}
	for rows.Next() {
		var i AppPositionChange
		if err := rows.Scan(
			&i.ID,
			&i.ArenaID,
			&i.AccountID,
			&i.FromPosition,
			&i.ToPosition,
			&i.Version,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrentPosition = `-- name: UpdateCurrentPosition :execrows
UPDATE app.debate_positions
SET current_position = $1::text,
    version = $2::integer,
    updated_at = $3::timestamptz
WHERE arena_id = $4::uuid
  AND account_id = $5::uuid
  AND version = $6::integer
`

type UpdateCurrentPositionParams struct {
	CurrentPosition string
	Version         int32
	At              pgtype.Timestamptz
	ArenaID         pgtype.UUID
	AccountID       pgtype.UUID
	ExpectedVersion int32
}

// UpdateCurrentPosition moves the projection to the change target under the
// optimistic version check: zero rows mean the chain moved since it was read
// and the whole change transaction must roll back (P09-T04).
func (q *Queries) UpdateCurrentPosition(ctx context.Context, arg UpdateCurrentPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCurrentPosition,
		arg.CurrentPosition,
		arg.Version,
		arg.At,
		arg.ArenaID,
		arg.AccountID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
