// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profiles.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommunicationPreferenceHistoryEntry = `-- name: CreateCommunicationPreferenceHistoryEntry :exec
INSERT INTO app.communication_preference_history (account_id, marketing_opt_in, changed_at)
VALUES ($1, $2, $3)
`

type CreateCommunicationPreferenceHistoryEntryParams struct {
	AccountID      pgtype.UUID
	MarketingOptIn bool
	ChangedAt      pgtype.Timestamptz
}

func (q *Queries) CreateCommunicationPreferenceHistoryEntry(ctx context.Context, arg CreateCommunicationPreferenceHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, createCommunicationPreferenceHistoryEntry, arg.AccountID, arg.MarketingOptIn, arg.ChangedAt)
	return err
}

const createProfile = `-- name: CreateProfile :one

INSERT INTO app.profiles (account_id, username, username_normalized, interface_locale)
VALUES ($1, $2, $3, $4)
RETURNING account_id, username, username_normalized, interface_locale, created_at, updated_at, timezone
`

type CreateProfileParams struct {
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
	InterfaceLocale    string
}

// Profile, username history and interface-locale queries for the PostgreSQL
// platform adapter.
//
// Privacy contract (docs/PRIVACY.md): profile queries never select or return
// email, credentials or payment-provider identifiers. Email stays in
// app.accounts; payment identifiers belong to the billing module.
// Public lookups only ever read from app.profiles by username_normalized.
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.AccountID,
		arg.Username,
		arg.UsernameNormalized,
		arg.InterfaceLocale,
	)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const createUsernameHistoryEntry = `-- name: CreateUsernameHistoryEntry :exec
INSERT INTO app.username_history (account_id, username, username_normalized, changed_at)
VALUES ($1, $2, $3, $4)
`

type CreateUsernameHistoryEntryParams struct {
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
	ChangedAt          pgtype.Timestamptz
}

func (q *Queries) CreateUsernameHistoryEntry(ctx context.Context, arg CreateUsernameHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, createUsernameHistoryEntry,
		arg.AccountID,
		arg.Username,
		arg.UsernameNormalized,
		arg.ChangedAt,
	)
	return err
}

const getCommunicationPreferencesByAccountID = `-- name: GetCommunicationPreferencesByAccountID :one
SELECT p.account_id,
       p.interface_locale,
       COALESCE(cp.marketing_opt_in, false)::boolean AS marketing_opt_in
FROM app.profiles p
LEFT JOIN app.communication_preferences cp ON cp.account_id = p.account_id
WHERE p.account_id = $1
`

type GetCommunicationPreferencesByAccountIDRow struct {
	AccountID       pgtype.UUID
	InterfaceLocale string
	MarketingOptIn  bool
}

// GetCommunicationPreferencesByAccountID joins the interface locale owned by
// app.profiles with the explicit opt-ins. A missing preferences row resolves
// to the conservative default (marketing opt-in false), never to an implicit
// opt-in.
func (q *Queries) GetCommunicationPreferencesByAccountID(ctx context.Context, accountID pgtype.UUID) (GetCommunicationPreferencesByAccountIDRow, error) {
	row := q.db.QueryRow(ctx, getCommunicationPreferencesByAccountID, accountID)
	var i GetCommunicationPreferencesByAccountIDRow
	err := row.Scan(&i.AccountID, &i.InterfaceLocale, &i.MarketingOptIn)
	return i, err
}

const getLastUsernameChangeAt = `-- name: GetLastUsernameChangeAt :one
SELECT max(changed_at)::timestamptz AS changed_at
FROM app.username_history
WHERE account_id = $1
`

// GetLastUsernameChangeAt returns the most recent username audit instant for
// the account, or NULL when the account has no history yet.
func (q *Queries) GetLastUsernameChangeAt(ctx context.Context, accountID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastUsernameChangeAt, accountID)
	var changed_at pgtype.Timestamptz
	err := row.Scan(&changed_at)
	return changed_at, err
}

const getProfileByAccountID = `-- name: GetProfileByAccountID :one
SELECT account_id, username, username_normalized, interface_locale, created_at, updated_at, timezone
FROM app.profiles
WHERE account_id = $1
`

func (q *Queries) GetProfileByAccountID(ctx context.Context, accountID pgtype.UUID) (AppProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByAccountID, accountID)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const getPublicProfileByUsername = `-- name: GetPublicProfileByUsername :one
SELECT username, interface_locale, created_at
FROM app.profiles
WHERE username_normalized = $1
`

type GetPublicProfileByUsernameRow struct {
	Username        string
	InterfaceLocale string
	CreatedAt       pgtype.Timestamptz
}

// GetPublicProfileByUsername returns only the publicly allowed profile fields.
// It never selects email, credentials, internal financial identifiers or
// administrative flags, and deliberately omits account_id.
func (q *Queries) GetPublicProfileByUsername(ctx context.Context, usernameNormalized string) (GetPublicProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfileByUsername, usernameNormalized)
	var i GetPublicProfileByUsernameRow
	err := row.Scan(&i.Username, &i.InterfaceLocale, &i.CreatedAt)
	return i, err
}

const isAccountEligibleForProfile = `-- name: IsAccountEligibleForProfile :one
SELECT (status = 'active' AND email_verified_at IS NOT NULL) AS eligible
FROM app.accounts
WHERE id = $1
`

// IsAccountEligibleForProfile projects the single bit the profiles module
// needs for negative authorization: the account exists, is active and has a
// verified email. It never reads email, credentials or payment identifiers.
func (q *Queries) IsAccountEligibleForProfile(ctx context.Context, id pgtype.UUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isAccountEligibleForProfile, id)
	var eligible pgtype.Bool
	err := row.Scan(&eligible)
	return eligible, err
}

const listCommunicationPreferenceHistoryByAccountID = `-- name: ListCommunicationPreferenceHistoryByAccountID :many
SELECT id, account_id, marketing_opt_in, changed_at
FROM app.communication_preference_history
WHERE account_id = $1
ORDER BY changed_at DESC, id DESC
`

func (q *Queries) ListCommunicationPreferenceHistoryByAccountID(ctx context.Context, accountID pgtype.UUID) ([]AppCommunicationPreferenceHistory, error) {
	rows, err := q.db.Query(ctx, listCommunicationPreferenceHistoryByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppCommunicationPreferenceHistory{}
	for rows.Next() {
		var i AppCommunicationPreferenceHistory
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.MarketingOptIn,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsernameHistoryByAccountID = `-- name: ListUsernameHistoryByAccountID :many
SELECT id, account_id, username, username_normalized, changed_at
FROM app.username_history
WHERE account_id = $1
ORDER BY changed_at DESC, id DESC
`

func (q *Queries) ListUsernameHistoryByAccountID(ctx context.Context, accountID pgtype.UUID) ([]AppUsernameHistory, error) {
	rows, err := q.db.Query(ctx, listUsernameHistoryByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUsernameHistory{}
	for rows.Next() {
		var i AppUsernameHistory
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Username,
			&i.UsernameNormalized,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileLocale = `-- name: UpdateProfileLocale :one
UPDATE app.profiles
SET interface_locale = $2, updated_at = now()
WHERE account_id = $1
RETURNING account_id, username, username_normalized, interface_locale, created_at, updated_at, timezone
`

type UpdateProfileLocaleParams struct {
	AccountID       pgtype.UUID
	InterfaceLocale string
}

func (q *Queries) UpdateProfileLocale(ctx context.Context, arg UpdateProfileLocaleParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, updateProfileLocale, arg.AccountID, arg.InterfaceLocale)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const updateProfileTimezone = `-- name: UpdateProfileTimezone :one
UPDATE app.profiles
SET timezone = $2, updated_at = now()
WHERE account_id = $1
RETURNING account_id, username, username_normalized, interface_locale, created_at, updated_at, timezone
`

type UpdateProfileTimezoneParams struct {
	AccountID pgtype.UUID
	Timezone  pgtype.Text
}

func (q *Queries) UpdateProfileTimezone(ctx context.Context, arg UpdateProfileTimezoneParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, updateProfileTimezone, arg.AccountID, arg.Timezone)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const updateProfileUsername = `-- name: UpdateProfileUsername :one
UPDATE app.profiles
SET username = $2, username_normalized = $3, updated_at = now()
WHERE account_id = $1
RETURNING account_id, username, username_normalized, interface_locale, created_at, updated_at, timezone
`

type UpdateProfileUsernameParams struct {
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
}

func (q *Queries) UpdateProfileUsername(ctx context.Context, arg UpdateProfileUsernameParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, updateProfileUsername, arg.AccountID, arg.Username, arg.UsernameNormalized)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const upsertCommunicationPreferences = `-- name: UpsertCommunicationPreferences :one
INSERT INTO app.communication_preferences (account_id, marketing_opt_in, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (account_id) DO UPDATE
SET marketing_opt_in = EXCLUDED.marketing_opt_in,
    updated_at = now()
RETURNING account_id, marketing_opt_in, created_at, updated_at
`

type UpsertCommunicationPreferencesParams struct {
	AccountID      pgtype.UUID
	MarketingOptIn bool
}

func (q *Queries) UpsertCommunicationPreferences(ctx context.Context, arg UpsertCommunicationPreferencesParams) (AppCommunicationPreference, error) {
	row := q.db.QueryRow(ctx, upsertCommunicationPreferences, arg.AccountID, arg.MarketingOptIn)
	var i AppCommunicationPreference
	err := row.Scan(
		&i.AccountID,
		&i.MarketingOptIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
