// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profiles.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one

INSERT INTO app.profiles (account_id, username, username_normalized, interface_locale)
VALUES ($1, $2, $3, $4)
RETURNING account_id, username, username_normalized, interface_locale, created_at, updated_at
`

type CreateProfileParams struct {
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
	InterfaceLocale    string
}

// Profile, username history and interface-locale queries for the PostgreSQL
// platform adapter.
//
// Privacy contract (docs/PRIVACY.md): profile queries never select or return
// email, credentials or payment-provider identifiers. Email stays in
// app.accounts; payment identifiers belong to the billing module.
// Public lookups only ever read from app.profiles by username_normalized.
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.AccountID,
		arg.Username,
		arg.UsernameNormalized,
		arg.InterfaceLocale,
	)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUsernameHistoryEntry = `-- name: CreateUsernameHistoryEntry :exec
INSERT INTO app.username_history (account_id, username, username_normalized)
VALUES ($1, $2, $3)
`

type CreateUsernameHistoryEntryParams struct {
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
}

func (q *Queries) CreateUsernameHistoryEntry(ctx context.Context, arg CreateUsernameHistoryEntryParams) error {
	_, err := q.db.Exec(ctx, createUsernameHistoryEntry, arg.AccountID, arg.Username, arg.UsernameNormalized)
	return err
}

const getProfileByAccountID = `-- name: GetProfileByAccountID :one
SELECT account_id, username, username_normalized, interface_locale, created_at, updated_at
FROM app.profiles
WHERE account_id = $1
`

func (q *Queries) GetProfileByAccountID(ctx context.Context, accountID pgtype.UUID) (AppProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByAccountID, accountID)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicProfileByUsername = `-- name: GetPublicProfileByUsername :one
SELECT username, interface_locale, created_at
FROM app.profiles
WHERE username_normalized = $1
`

type GetPublicProfileByUsernameRow struct {
	Username        string
	InterfaceLocale string
	CreatedAt       pgtype.Timestamptz
}

// GetPublicProfileByUsername returns only the publicly allowed profile fields.
// It never selects email, credentials, internal financial identifiers or
// administrative flags, and deliberately omits account_id.
func (q *Queries) GetPublicProfileByUsername(ctx context.Context, usernameNormalized string) (GetPublicProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfileByUsername, usernameNormalized)
	var i GetPublicProfileByUsernameRow
	err := row.Scan(&i.Username, &i.InterfaceLocale, &i.CreatedAt)
	return i, err
}

const listUsernameHistoryByAccountID = `-- name: ListUsernameHistoryByAccountID :many
SELECT id, account_id, username, username_normalized, changed_at
FROM app.username_history
WHERE account_id = $1
ORDER BY changed_at DESC, id DESC
`

func (q *Queries) ListUsernameHistoryByAccountID(ctx context.Context, accountID pgtype.UUID) ([]AppUsernameHistory, error) {
	rows, err := q.db.Query(ctx, listUsernameHistoryByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUsernameHistory{}
	for rows.Next() {
		var i AppUsernameHistory
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Username,
			&i.UsernameNormalized,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfileLocale = `-- name: UpdateProfileLocale :one
UPDATE app.profiles
SET interface_locale = $2, updated_at = now()
WHERE account_id = $1
RETURNING account_id, username, username_normalized, interface_locale, created_at, updated_at
`

type UpdateProfileLocaleParams struct {
	AccountID       pgtype.UUID
	InterfaceLocale string
}

func (q *Queries) UpdateProfileLocale(ctx context.Context, arg UpdateProfileLocaleParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, updateProfileLocale, arg.AccountID, arg.InterfaceLocale)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfileUsername = `-- name: UpdateProfileUsername :one
UPDATE app.profiles
SET username = $2, username_normalized = $3, updated_at = now()
WHERE account_id = $1
RETURNING account_id, username, username_normalized, interface_locale, created_at, updated_at
`

type UpdateProfileUsernameParams struct {
	AccountID          pgtype.UUID
	Username           string
	UsernameNormalized string
}

func (q *Queries) UpdateProfileUsername(ctx context.Context, arg UpdateProfileUsernameParams) (AppProfile, error) {
	row := q.db.QueryRow(ctx, updateProfileUsername, arg.AccountID, arg.Username, arg.UsernameNormalized)
	var i AppProfile
	err := row.Scan(
		&i.AccountID,
		&i.Username,
		&i.UsernameNormalized,
		&i.InterfaceLocale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
