// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Identity and authentication queries for the PostgreSQL platform adapter.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (AppAccount, error)
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (AppEmailVerificationToken, error)
	CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (AppPasswordResetToken, error)
	// Profile, username history and interface-locale queries for the PostgreSQL
	// platform adapter.
	//
	// Privacy contract (docs/PRIVACY.md): profile queries never select or return
	// email, credentials or payment-provider identifiers. Email stays in
	// app.accounts; payment identifiers belong to the billing module.
	// Public lookups only ever read from app.profiles by username_normalized.
	CreateProfile(ctx context.Context, arg CreateProfileParams) (AppProfile, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AppSession, error)
	CreateUsernameHistoryEntry(ctx context.Context, arg CreateUsernameHistoryEntryParams) error
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	GetAccountByEmail(ctx context.Context, lower string) (AppAccount, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (AppAccount, error)
	// GetAccountProfile retrieves account profile data without ever reading or exposing password credentials.
	GetAccountProfile(ctx context.Context, id pgtype.UUID) (AppAccount, error)
	GetActiveEmailVerificationToken(ctx context.Context, tokenHash []byte) (AppEmailVerificationToken, error)
	GetActivePasswordResetToken(ctx context.Context, tokenHash []byte) (AppPasswordResetToken, error)
	GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (AppSession, error)
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash []byte) (AppEmailVerificationToken, error)
	// Health metadata and connectivity queries for the PostgreSQL platform adapter.
	// GetHealthMetadata retrieves the latest applied migration metadata from app.schema_metadata.
	GetHealthMetadata(ctx context.Context) (GetHealthMetadataRow, error)
	// GetLastUsernameChangeAt returns the most recent username audit instant for
	// the account, or NULL when the account has no history yet.
	GetLastUsernameChangeAt(ctx context.Context, accountID pgtype.UUID) (pgtype.Timestamptz, error)
	GetPasswordCredentialByAccountID(ctx context.Context, accountID pgtype.UUID) (AppPasswordCredential, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (AppPasswordResetToken, error)
	GetProfileByAccountID(ctx context.Context, accountID pgtype.UUID) (AppProfile, error)
	// GetPublicProfileByUsername returns only the publicly allowed profile fields.
	// It never selects email, credentials, internal financial identifiers or
	// administrative flags, and deliberately omits account_id.
	GetPublicProfileByUsername(ctx context.Context, usernameNormalized string) (GetPublicProfileByUsernameRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (AppSession, error)
	InvalidateActiveEmailVerificationTokens(ctx context.Context, accountID pgtype.UUID) error
	InvalidateActivePasswordResetTokens(ctx context.Context, accountID pgtype.UUID) error
	// IsAccountEligibleForProfile projects the single bit the profiles module
	// needs for negative authorization: the account exists, is active and has a
	// verified email. It never reads email, credentials or payment identifiers.
	IsAccountEligibleForProfile(ctx context.Context, id pgtype.UUID) (pgtype.Bool, error)
	ListUsernameHistoryByAccountID(ctx context.Context, accountID pgtype.UUID) ([]AppUsernameHistory, error)
	MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id pgtype.UUID) (int64, error)
	// PingHealth executes a trivial query (SELECT 1) to verify connection readiness.
	PingHealth(ctx context.Context) (int32, error)
	RevokeAllAccountSessions(ctx context.Context, accountID pgtype.UUID) error
	RevokeSession(ctx context.Context, tokenHash []byte) error
	SetEmailVerified(ctx context.Context, id pgtype.UUID) (AppAccount, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (AppAccount, error)
	UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) error
	UpdateProfileLocale(ctx context.Context, arg UpdateProfileLocaleParams) (AppProfile, error)
	UpdateProfileUsername(ctx context.Context, arg UpdateProfileUsernameParams) (AppProfile, error)
	UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
