// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ApplyFreeBalanceDelta applies a signed net delta to the FREE_INK balance:
	// the monthly renewal expires the remaining franchise and grants the next
	// one in a single statement. The CHECK (balance_free >= 0) still guards the
	// invariant.
	ApplyFreeBalanceDelta(ctx context.Context, arg ApplyFreeBalanceDeltaParams) (AppWalletAccount, error)
	// ApplyWalletDebit subtracts the planned bucket consumptions in a single
	// statement; the CHECK (balance >= 0) guards the invariant even if a caller
	// gets the plan wrong.
	ApplyWalletDebit(ctx context.Context, arg ApplyWalletDebitParams) (AppWalletAccount, error)
	ClaimModerationCase(ctx context.Context, arg ClaimModerationCaseParams) (ClaimModerationCaseRow, error)
	// CloseArena performs the published→closed transition requested by the
	// creator under the optimistic version check. Reopening does not exist in
	// the MVP (P08-T05).
	CloseArena(ctx context.Context, arg CloseArenaParams) (AppArena, error)
	// ConfirmInitialPosition inserts the initial projection of one account in
	// one Arena. The primary key (arena_id, account_id) resolves concurrent
	// confirmations: the loser inserts nothing and re-reads the winner (P09-T03).
	ConfirmInitialPosition(ctx context.Context, arg ConfirmInitialPositionParams) (AppDebatePosition, error)
	// ConsumeArenaPassLot atomically decrements a lot that still has passes. The
	// conditional predicate and the remaining_quantity CHECK together make
	// over-consumption impossible, even under concurrent consumers (P07-T03).
	ConsumeArenaPassLot(ctx context.Context, id pgtype.UUID) (int64, error)
	// CountEligiblePositionsByArena derives the public aggregate of one Arena:
	// the initial and current distributions over eligible participants plus the
	// eligible total. This is the explicitly approved read-only projection of
	// ARCHITECTURE.md §4 and it follows docs/BUSINESS_RULES.md §7: only active
	// accounts count, so suspended, pending and deleted accounts (and any future
	// review invalidation) stay out of the official totals. The result carries
	// counts only — account identifiers never leave the database (P09-T05).
	CountEligiblePositionsByArena(ctx context.Context, arenaID pgtype.UUID) (CountEligiblePositionsByArenaRow, error)
	CountRecentModerationReportsByReporter(ctx context.Context, arg CountRecentModerationReportsByReporterParams) (int64, error)
	// Identity and authentication queries for the PostgreSQL platform adapter.
	CreateAccount(ctx context.Context, arg CreateAccountParams) (AppAccount, error)
	// Arena draft queries for the PostgreSQL platform adapter.
	//
	// Drafts are private: every query is scoped by the creator and public
	// projections never select a draft. Creating or editing a draft never
	// touches the Arena Pass ledger (P08-T03).
	CreateArena(ctx context.Context, arg CreateArenaParams) (AppArena, error)
	CreateArenaPassConsumption(ctx context.Context, arg CreateArenaPassConsumptionParams) (AppArenaPassConsumption, error)
	// Arena Pass entitlement queries for the PostgreSQL platform adapter.
	//
	// Consumption is append-only: no query updates or deletes a consumption and
	// no query mutates a lot's quantity or expiration. The runtime grants
	// enforce the same boundary in the database (P07-T01).
	CreateArenaPassLot(ctx context.Context, arg CreateArenaPassLotParams) (AppArenaPassLot, error)
	// CreateArenaPassLotIfAbsent inserts the grant exactly once per
	// (account, origin, reference). On a conflict it returns no row, which tells
	// the adapter to resolve the original lot (P07-T02).
	CreateArenaPassLotIfAbsent(ctx context.Context, arg CreateArenaPassLotIfAbsentParams) (AppArenaPassLot, error)
	// CreateArgument inserts one argument under the author idempotency key. The
	// partial unique index resolves concurrent attempts with the same key: the
	// loser gets no row back and resolves the replay (P10-T04).
	CreateArgument(ctx context.Context, arg CreateArgumentParams) (CreateArgumentRow, error)
	// CreateArgumentSource attaches one structured source to an argument.
	CreateArgumentSource(ctx context.Context, arg CreateArgumentSourceParams) (pgtype.UUID, error)
	// CreateAttribution records one attribution under the unique
	// (change, argument) pair: a retry inserts nothing and resolves the replay
	// (P11-T03).
	CreateAttribution(ctx context.Context, arg CreateAttributionParams) (pgtype.UUID, error)
	CreateCommunicationPreferenceHistoryEntry(ctx context.Context, arg CreateCommunicationPreferenceHistoryEntryParams) error
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (AppEmailVerificationToken, error)
	CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) (AppModerationAction, error)
	// Structured report queries for the PostgreSQL platform adapter (P13-T03).
	//
	// Reports are restricted evidence: inserts carry reporter, target, reason
	// and bounded context; reads serve deduplication and the rate signal only.
	// No query mutates a target: volume never removes content automatically.
	CreateModerationReport(ctx context.Context, arg CreateModerationReportParams) (AppModerationReport, error)
	CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (AppPasswordResetToken, error)
	// CreatePositionChange appends one change to the immutable history chain.
	// The unique (arena_id, account_id, version) constraint resolves concurrent
	// changes: only the chain tip advances (P09-T04).
	CreatePositionChange(ctx context.Context, arg CreatePositionChangeParams) (pgtype.UUID, error)
	// Profile, username history and interface-locale queries for the PostgreSQL
	// platform adapter.
	//
	// Privacy contract (docs/PRIVACY.md): profile queries never select or return
	// email, credentials or payment-provider identifiers. Email stays in
	// app.accounts; payment identifiers belong to the billing module.
	// Public lookups only ever read from app.profiles by username_normalized.
	CreateProfile(ctx context.Context, arg CreateProfileParams) (AppProfile, error)
	// Reconciliation runs and findings (P12-T10). A run states the window it
	// inspected with its counters; every divergence is an immutable finding
	// resolved only by a human justification afterwards.
	CreateReconciliationRun(ctx context.Context, arg CreateReconciliationRunParams) (AppBillingReconciliationRun, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AppSession, error)
	CreateUsernameHistoryEntry(ctx context.Context, arg CreateUsernameHistoryEntryParams) error
	// Wallet ledger queries for the PostgreSQL platform adapter.
	//
	// The ledger is append-only: these queries only create wallet rows, insert
	// operations/transactions and read them back. No query updates or deletes a
	// transaction, and the runtime grants enforce the same boundary in the
	// database (THR-WAL-02).
	CreateWalletAccount(ctx context.Context, accountID pgtype.UUID) (AppWalletAccount, error)
	CreateWalletOperation(ctx context.Context, arg CreateWalletOperationParams) (AppWalletOperation, error)
	// CreateWalletOperationIfAbsent inserts the operation exactly once per
	// idempotency key. On a conflict it returns no row, which tells the adapter
	// to replay the original operation (P06-T03).
	CreateWalletOperationIfAbsent(ctx context.Context, arg CreateWalletOperationIfAbsentParams) (AppWalletOperation, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (AppWalletTransaction, error)
	// CreditFreeBalance adds the delta to the FREE_INK balance projection. The
	// CHECK (balance_free >= 0) guards the invariant even here.
	CreditFreeBalance(ctx context.Context, arg CreditFreeBalanceParams) (AppWalletAccount, error)
	CreditPurchasedBalance(ctx context.Context, arg CreditPurchasedBalanceParams) (AppWalletAccount, error)
	DecideModerationCase(ctx context.Context, arg DecideModerationCaseParams) (DecideModerationCaseRow, error)
	DeleteArenaDraft(ctx context.Context, arg DeleteArenaDraftParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	// EnsureWalletAccount materializes the balance projection row for an
	// account; a pre-existing row is left untouched, including its balances.
	EnsureWalletAccount(ctx context.Context, accountID pgtype.UUID) error
	FinishReconciliationRun(ctx context.Context, arg FinishReconciliationRunParams) (AppBillingReconciliationRun, error)
	GetAccountByEmail(ctx context.Context, lower string) (AppAccount, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (AppAccount, error)
	// Customer correlation lookup (P12-T08).
	GetAccountByStripeCustomerID(ctx context.Context, stripeCustomerID string) (GetAccountByStripeCustomerIDRow, error)
	GetAccountModerationTarget(ctx context.Context, id pgtype.UUID) (GetAccountModerationTargetRow, error)
	// GetAccountProfile retrieves account profile data without ever reading or exposing password credentials.
	GetAccountProfile(ctx context.Context, id pgtype.UUID) (AppAccount, error)
	GetActiveEmailVerificationToken(ctx context.Context, tokenHash []byte) (AppEmailVerificationToken, error)
	GetActivePasswordResetToken(ctx context.Context, tokenHash []byte) (AppPasswordResetToken, error)
	GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (AppSession, error)
	GetActiveSubscriptionByAccount(ctx context.Context, accountID pgtype.UUID) (AppSubscription, error)
	// Administrative assignment queries for the PostgreSQL platform adapter.
	//
	// Assignments key on account identifiers only: email, frontend flags,
	// payment state and popularity never enter this surface, so authorization
	// can never be influenced by who pays or who is popular (P13-T02).
	GetAdminRoleByAccount(ctx context.Context, accountID pgtype.UUID) (AppAdminRole, error)
	GetArenaByID(ctx context.Context, id pgtype.UUID) (AppArena, error)
	GetArenaForCreator(ctx context.Context, arg GetArenaForCreatorParams) (AppArena, error)
	// Target resolution for report filing (P13-T03). Each read returns the
	// owner and the lifecycle needed to distinguish unknown targets from
	// removed ones. Drafts stay reportable (self-report path); removed and
	// withdrawn targets deny.
	GetArenaModerationTarget(ctx context.Context, id pgtype.UUID) (GetArenaModerationTargetRow, error)
	GetArenaPassConsumptionByArena(ctx context.Context, arenaID pgtype.UUID) (AppArenaPassConsumption, error)
	GetArenaPassLot(ctx context.Context, id pgtype.UUID) (AppArenaPassLot, error)
	GetArenaPassLotByGrant(ctx context.Context, arg GetArenaPassLotByGrantParams) (AppArenaPassLot, error)
	GetArenaStateByID(ctx context.Context, id pgtype.UUID) (GetArenaStateByIDRow, error)
	// GetArenaStateForCreator diagnoses why a scoped draft write affected no
	// row: missing or foreign arena, non-draft status, or stale version.
	GetArenaStateForCreator(ctx context.Context, arg GetArenaStateForCreatorParams) (GetArenaStateForCreatorRow, error)
	// GetArenaStatusBySlug reports the stored status of the Arena holding the
	// slug, including removed, so the SEO document endpoint can answer 410 for
	// removed Arenas instead of 404 (P08-T08). Drafts never hold a slug.
	GetArenaStatusBySlug(ctx context.Context, slug pgtype.Text) (string, error)
	// GetArgumentAttributionMetrics derives the public count facts of one
	// argument (P11-T06; BR §5.1, §6, §7): the valid attribution events it
	// received and the eligible people who credited it, each person counted
	// once per argument. Rules encoded here:
	//   1. Only valid attributions count, exactly as the reputation projection
	//      (BR §6): an invalidated attribution never integrates a valid total.
	//   2. Eligible attributor means an active account with a verified email
	//      (BR §7), the same predicate the professional aggregates use.
	//   3. The LEFT JOIN keeps an argument with no eligible attribution
	//      representable (zeros) while a missing argument still returns no row,
	//      so the adapter can distinguish "no counts" from "no argument".
	//   4. Counts are facts, not state: withdrawing or removing the argument
	//      does not rewrite them (BR §10).
	// The result carries counts only — attributor identities never leave the
	// database.
	GetArgumentAttributionMetrics(ctx context.Context, argumentID pgtype.UUID) (GetArgumentAttributionMetricsRow, error)
	// GetArgumentByAuthorAndKey resolves the argument recorded under one
	// attempt key (P10-T04).
	GetArgumentByAuthorAndKey(ctx context.Context, arg GetArgumentByAuthorAndKeyParams) (GetArgumentByAuthorAndKeyRow, error)
	// GetArgumentForAuthor returns one argument scoped to its author. A foreign
	// argument is deliberately indistinguishable from a missing one (P10-T06).
	GetArgumentForAuthor(ctx context.Context, arg GetArgumentForAuthorParams) (GetArgumentForAuthorRow, error)
	GetArgumentModerationTarget(ctx context.Context, id pgtype.UUID) (GetArgumentModerationTargetRow, error)
	// GetAttributionForModeration loads one attribution with its current
	// validity and its latest moderation decision and locks it FOR UPDATE, so
	// concurrent decisions on the same row serialize instead of overwriting
	// each other (P11-T04). It is the moderation read projection: a consumer
	// reads validity from the retained row that the schema keeps coherent with
	// the decision record, so no projection can observe an unrecorded
	// invalidation.
	GetAttributionForModeration(ctx context.Context, attributionID pgtype.UUID) (GetAttributionForModerationRow, error)
	GetBillingRefundByProviderID(ctx context.Context, providerRefundID string) (AppBillingRefund, error)
	// GetCheckoutIntentBySession resolves the intent a provider session already
	// stands for. The session identifier is unique by constraint, which is what
	// makes a replay resolve the original intent instead of creating a second one.
	GetCheckoutIntentBySession(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (GetCheckoutIntentBySessionRow, error)
	// GetCommunicationPreferencesByAccountID joins the interface locale owned by
	// app.profiles with the explicit opt-ins. A missing preferences row resolves
	// to the conservative default (marketing opt-in false), never to an implicit
	// opt-in.
	GetCommunicationPreferencesByAccountID(ctx context.Context, accountID pgtype.UUID) (GetCommunicationPreferencesByAccountIDRow, error)
	// GetDebatePosition returns the private projection of one account in one
	// Arena.
	GetDebatePosition(ctx context.Context, arg GetDebatePositionParams) (AppDebatePosition, error)
	// GetDerivedWalletBalance recomputes both bucket balances exclusively from
	// the append-only ledger: the source of truth for the cached projection
	// (P06-T05, REQ-WAL-01).
	GetDerivedWalletBalance(ctx context.Context, accountID pgtype.UUID) (GetDerivedWalletBalanceRow, error)
	GetDuplicateModerationReport(ctx context.Context, arg GetDuplicateModerationReportParams) (AppModerationReport, error)
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash []byte) (AppEmailVerificationToken, error)
	// Health metadata and connectivity queries for the PostgreSQL platform adapter.
	// GetHealthMetadata retrieves the latest applied migration metadata from app.schema_metadata.
	GetHealthMetadata(ctx context.Context) (GetHealthMetadataRow, error)
	// GetLastUsernameChangeAt returns the most recent username audit instant for
	// the account, or NULL when the account has no history yet.
	GetLastUsernameChangeAt(ctx context.Context, accountID pgtype.UUID) (pgtype.Timestamptz, error)
	// Review claim and decision queries (P13-T04). Claims serialize on the
	// row: one conditional update moves open (or expired-lease) cases under
	// the claimant with a fresh lease. Decisions record one immutable action
	// and move the case to decided while clearing the claim, atomically in
	// the adapter transaction.
	GetModerationCaseByID(ctx context.Context, id pgtype.UUID) (GetModerationCaseByIDRow, error)
	// GetParentArgument returns one argument together with its derived depth
	// (0 for a top-level argument). Replies walk the chain through the
	// recursive CTE, so depth is never denormalized; the depth guard bounds a
	// corrupted chain defensively (P10-T05).
	GetParentArgument(ctx context.Context, argumentID pgtype.UUID) (GetParentArgumentRow, error)
	GetPasswordCredentialByAccountID(ctx context.Context, accountID pgtype.UUID) (AppPasswordCredential, error)
	GetPasswordResetTokenByHash(ctx context.Context, tokenHash []byte) (AppPasswordResetToken, error)
	// GetPositionChangeForAttributor loads one position change scoped to its
	// account and locks it FOR UPDATE: attribution recording serializes per
	// change, so the cumulative three-argument limit cannot be bypassed by
	// concurrent requests (P11-T03). Reading the change row is the approved
	// read-only projection over the positions schema.
	GetPositionChangeForAttributor(ctx context.Context, arg GetPositionChangeForAttributorParams) (GetPositionChangeForAttributorRow, error)
	GetProfileByAccountID(ctx context.Context, accountID pgtype.UUID) (AppProfile, error)
	// GetPublicArenaBySlug resolves a public Arena address. Drafts are never
	// addressable and removed Arenas are not found for the public (P08-T07).
	GetPublicArenaBySlug(ctx context.Context, slug pgtype.Text) (AppArena, error)
	// GetPublicArgument resolves one argument for the public surface: published
	// and withdrawn (retracted) arguments resolve; moderation-removed arguments
	// are not found (P10-T07).
	GetPublicArgument(ctx context.Context, argumentID pgtype.UUID) (GetPublicArgumentRow, error)
	// GetPublicProfileByUsername returns only the publicly allowed profile fields.
	// It never selects email, credentials, internal financial identifiers or
	// administrative flags, and deliberately omits account_id.
	GetPublicProfileByUsername(ctx context.Context, usernameNormalized string) (GetPublicProfileByUsernameRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (AppSession, error)
	GetStripeCustomer(ctx context.Context, accountID pgtype.UUID) (GetStripeCustomerRow, error)
	// Subscription lifecycle queries (P12-T08).
	// The subscription mirror persists the provider state and anchors per-period
	// Member entitlement grants (30,000 INK and 1 expiring Arena Pass).
	GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID string) (AppSubscription, error)
	GetWalletAccount(ctx context.Context, accountID pgtype.UUID) (AppWalletAccount, error)
	// GetWalletAccountForUpdate locks the balance projection row of an account
	// for the duration of the transaction, serializing concurrent debits so no
	// double spend can pass the balance check (THR-WAL-01).
	GetWalletAccountForUpdate(ctx context.Context, accountID pgtype.UUID) (AppWalletAccount, error)
	GetWalletFreeCycleAnchor(ctx context.Context, accountID pgtype.UUID) (pgtype.Timestamptz, error)
	GetWalletOperationByIdempotencyKey(ctx context.Context, idempotencyKey string) (AppWalletOperation, error)
	// GetWebhookEventByEventID resolves an existing event by its provider
	// identifier. The event must exist: a conflict without a stored event is an
	// integrity problem.
	GetWebhookEventByEventID(ctx context.Context, stripeEventID string) (AppStripeEvent, error)
	// Refund records (P12-T09). One row per provider refund/dispute object; the
	// provider identifier is the idempotency anchor and the commercial facts are
	// immutable once written. Only the human resolution may be appended later.
	InsertBillingRefundIfAbsent(ctx context.Context, arg InsertBillingRefundIfAbsentParams) (AppBillingRefund, error)
	InsertReconciliationFinding(ctx context.Context, arg InsertReconciliationFindingParams) (AppBillingReconciliationFinding, error)
	// Webhook event queries (P12-T05). The provider's unique event ID is the
	// idempotency anchor: a replay resolves the existing row and never creates a
	// second one. The processing lifecycle is enforced by CHECK constraints and
	// the transition table in the stripe_events_protect_processing trigger.
	// InsertWebhookEventIfAbsent persists the verified inbound event exactly once
	// per provider event ID. On conflict (the unique stripe_event_id), it returns
	// no row, which tells the adapter to resolve the existing event.
	InsertWebhookEventIfAbsent(ctx context.Context, arg InsertWebhookEventIfAbsentParams) (AppStripeEvent, error)
	InvalidateActiveEmailVerificationTokens(ctx context.Context, accountID pgtype.UUID) error
	InvalidateActivePasswordResetTokens(ctx context.Context, accountID pgtype.UUID) error
	// InvalidateAttribution moves a valid attribution to invalid, recording the
	// actor, the mandatory reason and the instant on the retained row; nothing
	// is deleted. The status guard loses the race instead of overwriting a
	// concurrent decision.
	InvalidateAttribution(ctx context.Context, arg InvalidateAttributionParams) (InvalidateAttributionRow, error)
	// IsAccountEligibleForProfile projects the single bit the profiles module
	// needs for negative authorization: the account exists, is active and has a
	// verified email. It never reads email, credentials or payment identifiers.
	IsAccountEligibleForProfile(ctx context.Context, id pgtype.UUID) (pgtype.Bool, error)
	// Checkout queries (P12-T04). The commercial decision of an intent is
	// resolved by the server from the versioned catalog and is immutable once
	// written; these queries insert it and resolve replays, never recompute it.
	// IsAccountEligibleForPurchase projects the single bit the checkout needs
	// before it decides to charge anyone: the account exists, is active and has a
	// verified email (docs/BUSINESS_RULES.md §7, REQ-AUTH-02). It reads no email,
	// no credential and no payment identifier, so an ineligible or forged
	// identifier can never be mistaken for a legitimate buyer. A missing row means
	// the account does not exist at all.
	IsAccountEligibleForPurchase(ctx context.Context, id pgtype.UUID) (pgtype.Bool, error)
	// ListArenaArgumentsPage returns one keyset page of published top-level
	// arguments of one relation in one Arena, newest first, with the derived
	// published-reply count computed in the same statement (no N+1). Withdrawn
	// and removed arguments never appear in public lists (P10-T07).
	ListArenaArgumentsPage(ctx context.Context, arg ListArenaArgumentsPageParams) ([]ListArenaArgumentsPageRow, error)
	ListArenaDraftsForCreator(ctx context.Context, creatorID pgtype.UUID) ([]AppArena, error)
	ListArenaPassConsumptionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]ListArenaPassConsumptionsByAccountRow, error)
	// ListArenaPassConsumptionsPage returns one keyset-paginated page of the
	// owner's consumption history, newest first. NULL after_* parameters select
	// the first page; the (consumed_at, id) tuple comparison never duplicates or
	// skips rows (P07-T06).
	ListArenaPassConsumptionsPage(ctx context.Context, arg ListArenaPassConsumptionsPageParams) ([]ListArenaPassConsumptionsPageRow, error)
	ListArenaPassLotsByAccount(ctx context.Context, accountID pgtype.UUID) ([]AppArenaPassLot, error)
	// ListAttributionAlternation loads, for one subject and window, the position
	// changes of every account that credited the subject, with how many of those
	// changes were reversals (P11-T07; METRICS §4 "reversões repetidas pela mesma
	// conta"): a change back to the position held before the previous change.
	//
	// The chain window function deliberately reads every change of the account,
	// not only the ones inside the window, so the predecessor of an in-window
	// change is its real predecessor; the counters then keep only the in-window
	// events.
	ListAttributionAlternation(ctx context.Context, arg ListAttributionAlternationParams) ([]ListAttributionAlternationRow, error)
	// ListAttributionArgumentIDs returns the argument identifiers already
	// credited by one change (P11-T03).
	ListAttributionArgumentIDs(ctx context.Context, changeID pgtype.UUID) ([]pgtype.UUID, error)
	// ListAttributionCandidates loads the eligibility inputs of the proposed
	// arguments: arena, author, creation instant and status. Relation is
	// deliberately not read: it never restricts eligibility (P11-T02).
	ListAttributionCandidates(ctx context.Context, argumentIds []pgtype.UUID) ([]ListAttributionCandidatesRow, error)
	// ListAttributionConcentration loads, for one subject and window, how many
	// valid attributions each account made to the subject's arguments (P11-T07;
	// METRICS §4). The share and the threshold are computed by the domain, so the
	// same aggregation serves every policy revision. The eligibility filter is
	// deliberately absent, for the reason documented above.
	ListAttributionConcentration(ctx context.Context, arg ListAttributionConcentrationParams) ([]ListAttributionConcentrationRow, error)
	// ListAttributionReciprocity loads, for one subject and window, the accounts
	// that credited the subject's arguments while the subject credited theirs
	// (P11-T07; THR-PERS-01): the raw material of the reciprocity signal. Rules
	// encoded here:
	//   1. Only valid attributions count, exactly as the public metrics: an
	//      invalidated attribution is already a closed case.
	//   2. Both directions must exist for the pair to appear; whether the pair
	//      crosses the policy threshold is the domain's judgment, not SQL's.
	//   3. No eligibility filter on purpose: abuse review must not be blind to
	//      suspended or unverified accounts, which are precisely the population
	//      coordinated manipulation uses. Eligibility still excludes them from
	//      the official results (BR §7); these facts never reach a public
	//      projection (CONSTITUTION §Dados pessoais).
	ListAttributionReciprocity(ctx context.Context, arg ListAttributionReciprocityParams) ([]ListAttributionReciprocityRow, error)
	// ListAuthorArenaReputation derives the reputation projection of one
	// author (P11-T05; BR §5.1, §6, §7): one row per Arena where the author
	// received at least one valid attribution, with the eligible people the
	// author influenced there and the valid attribution events received there.
	//
	// Rules encoded here:
	//   1. Only valid attributions count: invalidated ones never integrate the
	//      valid totals (BR §6) and the row is retained for the administrative
	//      trail (P11-T04).
	//   2. DistinctPeople counts eligible attributors once per author and
	//      Arena (BR §6), so repeated attributions by the same person never
	//      inflate the headline.
	//   3. Eligible attributor means an active account with a verified email
	//      (BR §7), the same predicate the professional aggregates use.
	//   4. Attribution events are facts: withdrawing or removing an argument
	//      does not rewrite historical counts (BR §10); the attribution itself
	//      is the exclusion unit.
	// The result carries counts only — attributor identifiers never leave the
	// database.
	ListAuthorArenaReputation(ctx context.Context, authorID pgtype.UUID) ([]ListAuthorArenaReputationRow, error)
	// ListAvailablePassLotsForUpdate locks the consumable lots of an account in
	// consumption order: nearest expiration first, then lots that never expire.
	// Expired lots are never candidates, so they can never be consumed (P07-T03).
	ListAvailablePassLotsForUpdate(ctx context.Context, arg ListAvailablePassLotsForUpdateParams) ([]AppArenaPassLot, error)
	ListBillingRefundsByIntent(ctx context.Context, checkoutIntentID pgtype.UUID) ([]AppBillingRefund, error)
	// Reconciliation window reads (P12-T10). The job compares the local mirrors
	// created in the window against the provider and records findings without
	// correcting anything: these selects are the only local input, ordered
	// deterministically so runs are reproducible.
	ListCheckoutIntentsForReconciliation(ctx context.Context, arg ListCheckoutIntentsForReconciliationParams) ([]ListCheckoutIntentsForReconciliationRow, error)
	ListCommunicationPreferenceHistoryByAccountID(ctx context.Context, accountID pgtype.UUID) ([]AppCommunicationPreferenceHistory, error)
	// ListExpiredArenaPassLots derives the expired lots that still hold passes.
	// Expiration is never written back: the predicate is evaluated at read time,
	// so the sweep is a pure derivation and repeated runs are identical (P07-T04).
	ListExpiredArenaPassLots(ctx context.Context, arg ListExpiredArenaPassLotsParams) ([]AppArenaPassLot, error)
	// ListPositionChanges returns the private change history of one account in
	// one Arena, newest first; the chain order is the version (P09-T06).
	ListPositionChanges(ctx context.Context, arg ListPositionChangesParams) ([]AppPositionChange, error)
	// ListPublicArenasPage returns one keyset page of the public feed, newest
	// first, with optional language, category and status filters. Only publicly
	// visible statuses are ever candidates: drafts and removed Arenas can never
	// appear, and the (published_at, id) tuple comparison never duplicates or
	// skips rows (P08-T06).
	ListPublicArenasPage(ctx context.Context, arg ListPublicArenasPageParams) ([]AppArena, error)
	ListReconciliationFindingsByRun(ctx context.Context, runID pgtype.UUID) ([]AppBillingReconciliationFinding, error)
	// ListRepliesPage returns one keyset page of published replies of one
	// parent, newest first. Replies carry no derived reply count: the depth
	// policy forbids grandchildren (P10-T05), so the count is always zero and
	// the statement stays cheaper.
	ListRepliesPage(ctx context.Context, arg ListRepliesPageParams) ([]ListRepliesPageRow, error)
	ListSubscriptionsForReconciliation(ctx context.Context, arg ListSubscriptionsForReconciliationParams) ([]AppSubscription, error)
	ListUnprocessedStripeEvents(ctx context.Context, arg ListUnprocessedStripeEventsParams) ([]AppStripeEvent, error)
	ListUsernameHistoryByAccountID(ctx context.Context, accountID pgtype.UUID) ([]AppUsernameHistory, error)
	// ListWalletStatementPage returns one keyset-paginated page of the account
	// statement, newest first. NULL after_* parameters select the first page;
	// the (created_at, id) tuple comparison never duplicates or skips rows.
	ListWalletStatementPage(ctx context.Context, arg ListWalletStatementPageParams) ([]ListWalletStatementPageRow, error)
	ListWalletTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]ListWalletTransactionsByAccountRow, error)
	ListWalletTransactionsByOperationID(ctx context.Context, operationID pgtype.UUID) ([]AppWalletTransaction, error)
	// MarkCheckoutIntentPaid transitions the intent to the paid terminal state
	// and records the settlement instant. The CHECK constraint ensures that
	// paid_at is non-null exactly when status is paid. The trigger allows
	// open → paid only once.
	MarkCheckoutIntentPaid(ctx context.Context, stripeCheckoutSessionID pgtype.Text) error
	MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) (int64, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id pgtype.UUID) (int64, error)
	// PingHealth executes a trivial query (SELECT 1) to verify connection readiness.
	PingHealth(ctx context.Context) (int32, error)
	// PublishArenaDraft performs the draft→published transition under the
	// optimistic version check inside the publication transaction, so the Arena
	// row and the consumed Arena Pass commit together (P08-T04).
	PublishArenaDraft(ctx context.Context, arg PublishArenaDraftParams) (AppArena, error)
	// RecordCheckoutIntentIfAbsent inserts the commercial decision exactly once per
	// provider session, so a replay of the same operation resolves the stored
	// intent. The lifecycle CHECK is what keeps the recorded state honest: an open
	// intent has a session, an expired one is closed at a known instant.
	RecordCheckoutIntentIfAbsent(ctx context.Context, arg RecordCheckoutIntentIfAbsentParams) (RecordCheckoutIntentIfAbsentRow, error)
	// RecordStripeCustomerIfAbsent stores the account→customer correlation exactly
	// once per account: a concurrent or retried insertion writes nothing and
	// resolves the stored mapping, so the account is never charged through two
	// different provider customers.
	RecordStripeCustomerIfAbsent(ctx context.Context, arg RecordStripeCustomerIfAbsentParams) (RecordStripeCustomerIfAbsentRow, error)
	// RemoveArena applies the moderation removal to a published, closed or
	// restricted Arena under the optimistic version check; removed is terminal.
	RemoveArena(ctx context.Context, arg RemoveArenaParams) (AppArena, error)
	// ResolveAuthorByUsername resolves a public username to the author identity
	// used by the reputation projection (P11-T06). Resolution is read-only over
	// the profiles projection and matches the canonical normalized username,
	// the only authority key of profile lookups (P05-T01): no profile field
	// crosses the port, only the resolved identity does. A username that owns no
	// profile returns no rows, which the adapter reports as ErrProfileNotFound.
	ResolveAuthorByUsername(ctx context.Context, username string) (ResolveAuthorByUsernameRow, error)
	// RestoreAttribution reverses one invalidation on the same retained row,
	// recording the restore decision: the row moves back to valid and the
	// decision record is replaced by the newest one, never erased.
	RestoreAttribution(ctx context.Context, arg RestoreAttributionParams) (RestoreAttributionRow, error)
	// RestrictArena applies the moderation restriction to a published or closed
	// Arena under the optimistic version check (P08-T05).
	RestrictArena(ctx context.Context, arg RestrictArenaParams) (AppArena, error)
	RevokeAllAccountSessions(ctx context.Context, accountID pgtype.UUID) error
	RevokeSession(ctx context.Context, tokenHash []byte) error
	SetEmailVerified(ctx context.Context, id pgtype.UUID) (AppAccount, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (AppAccount, error)
	// UpdateArenaDraft replaces the mutable draft fields under an optimistic
	// version check: a stale expected version affects no row (P08-T03).
	UpdateArenaDraft(ctx context.Context, arg UpdateArenaDraftParams) (AppArena, error)
	// UpdateCurrentPosition moves the projection to the change target under the
	// optimistic version check: zero rows mean the chain moved since it was read
	// and the whole change transaction must roll back (P09-T04).
	UpdateCurrentPosition(ctx context.Context, arg UpdateCurrentPositionParams) (int64, error)
	UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) error
	UpdateProfileLocale(ctx context.Context, arg UpdateProfileLocaleParams) (AppProfile, error)
	UpdateProfileTimezone(ctx context.Context, arg UpdateProfileTimezoneParams) (AppProfile, error)
	UpdateProfileUsername(ctx context.Context, arg UpdateProfileUsernameParams) (AppProfile, error)
	UpdateSessionLastSeen(ctx context.Context, id pgtype.UUID) error
	// UpdateWebhookEventStatus transitions the event to the requested status. The
	// CHECK constraint stripe_events_status_transition enforces legal transitions,
	// so an illegal transition is a database error.
	UpdateWebhookEventStatus(ctx context.Context, arg UpdateWebhookEventStatusParams) (AppStripeEvent, error)
	// UpdateWebhookEventStatusFailed transitions the event to the failed state
	// with a bounded error reason. The event may be retried later.
	UpdateWebhookEventStatusFailed(ctx context.Context, arg UpdateWebhookEventStatusFailedParams) (AppStripeEvent, error)
	// UpdateWebhookEventStatusIgnored transitions the event to the ignored
	// terminal state for event types that are acknowledged but not handled.
	UpdateWebhookEventStatusIgnored(ctx context.Context, arg UpdateWebhookEventStatusIgnoredParams) (AppStripeEvent, error)
	// UpdateWebhookEventStatusProcessed transitions the event to the processed
	// terminal state and records the processing completion time.
	UpdateWebhookEventStatusProcessed(ctx context.Context, arg UpdateWebhookEventStatusProcessedParams) (AppStripeEvent, error)
	UpsertCommunicationPreferences(ctx context.Context, arg UpsertCommunicationPreferencesParams) (AppCommunicationPreference, error)
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (AppSubscription, error)
	// WithdrawArgument moves a published argument out of the display under the
	// author scope, recording the withdrawal instant once. Zero rows mean the
	// status moved concurrently: the caller re-reads and resolves (P10-T06).
	WithdrawArgument(ctx context.Context, arg WithdrawArgumentParams) (WithdrawArgumentRow, error)
	// ZeroPassLotRemaining revokes every remaining pass of one lot without
	// deleting history: consumption rows stay, only the remaining projection is
	// zeroed. It reports how many rows were actually revoked.
	ZeroPassLotRemaining(ctx context.Context, id pgtype.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
