// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: retention.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeTerminalSessionReferentials = `-- name: AnonymizeTerminalSessionReferentials :one
WITH scope AS (
    SELECT session.id, session.account_id
    FROM app.sessions session
    WHERE (
            (session.revoked_at IS NOT NULL AND session.revoked_at <= $1::timestamptz)
            OR session.expires_at <= $1::timestamptz
        )
      AND (session.ip_address IS NOT NULL OR session.user_agent IS NOT NULL)
),
anonymized AS (
    UPDATE app.sessions target
    SET ip_address = NULL,
        user_agent = NULL
    FROM scope
    WHERE target.id = scope.id
      AND NOT $2::boolean
      AND NOT (scope.account_id = ANY (COALESCE($3::uuid[], '{}'::uuid[])))
    RETURNING 1 AS row_count
),
preserved AS (
    SELECT 1
    FROM scope
    WHERE $2::boolean
       OR scope.account_id = ANY (COALESCE($3::uuid[], '{}'::uuid[]))
)
SELECT
    (SELECT count(*) FROM anonymized)::integer AS anonymized,
    (SELECT count(*) FROM preserved)::integer AS held
`

type AnonymizeTerminalSessionReferentialsParams struct {
	Cutoff       pgtype.Timestamptz
	ClassHeld    bool
	HeldAccounts []pgtype.UUID
}

type AnonymizeTerminalSessionReferentialsRow struct {
	Anonymized int32
	Held       int32
}

// AnonymizeTerminalSessionReferentials strips the client IP and user agent
// of terminal sessions past the prevention window. The session row itself
// survives until its own, longer retention window elapses.
func (q *Queries) AnonymizeTerminalSessionReferentials(ctx context.Context, arg AnonymizeTerminalSessionReferentialsParams) (AnonymizeTerminalSessionReferentialsRow, error) {
	row := q.db.QueryRow(ctx, anonymizeTerminalSessionReferentials, arg.Cutoff, arg.ClassHeld, arg.HeldAccounts)
	var i AnonymizeTerminalSessionReferentialsRow
	err := row.Scan(&i.Anonymized, &i.Held)
	return i, err
}

const countRetainedAuditEvents = `-- name: CountRetainedAuditEvents :one
SELECT count(*)::integer AS retained
FROM app.audit_events
`

// CountRetainedAuditEvents counts the administrative trail kept as
// evidence. The trail is append-only for every role, so the retention
// policy never schedules a purge for this class.
func (q *Queries) CountRetainedAuditEvents(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countRetainedAuditEvents)
	var retained int32
	err := row.Scan(&retained)
	return retained, err
}

const countRetainedBillingRows = `-- name: CountRetainedBillingRows :one
SELECT (
    (SELECT count(*) FROM app.stripe_customers)
    + (SELECT count(*) FROM app.stripe_events)
    + (SELECT count(*) FROM app.checkout_intents)
    + (SELECT count(*) FROM app.subscriptions)
    + (SELECT count(*) FROM app.billing_refunds)
    + (SELECT count(*) FROM app.billing_reconciliation_runs)
    + (SELECT count(*) FROM app.billing_reconciliation_findings)
)::integer AS retained
`

// CountRetainedBillingRows counts the payment, subscription, refund and
// reconciliation records kept as evidence of money and of the
// reconciliation duty. No row of the billing module is ever deleted.
func (q *Queries) CountRetainedBillingRows(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countRetainedBillingRows)
	var retained int32
	err := row.Scan(&retained)
	return retained, err
}

const createRetentionRun = `-- name: CreateRetentionRun :one
INSERT INTO app.retention_runs (
    data_class, executed_at, cutoff_at, purged_count, anonymized_count, retained_count, held_count
)
VALUES (
    $1::text,
    $2::timestamptz,
    $3::timestamptz,
    $4::integer,
    $5::integer,
    $6::integer,
    $7::integer
)
ON CONFLICT (data_class, executed_at) DO NOTHING
RETURNING id, data_class, executed_at, cutoff_at, purged_count, anonymized_count, retained_count, held_count
`

type CreateRetentionRunParams struct {
	DataClass       string
	ExecutedAt      pgtype.Timestamptz
	CutoffAt        pgtype.Timestamptz
	PurgedCount     int32
	AnonymizedCount int32
	RetainedCount   int32
	HeldCount       int32
}

// CreateRetentionRun appends one ledger row per class and execution
// instant. A replayed run resolves the original record instead of
// duplicating or rewriting it.
func (q *Queries) CreateRetentionRun(ctx context.Context, arg CreateRetentionRunParams) (AppRetentionRun, error) {
	row := q.db.QueryRow(ctx, createRetentionRun,
		arg.DataClass,
		arg.ExecutedAt,
		arg.CutoffAt,
		arg.PurgedCount,
		arg.AnonymizedCount,
		arg.RetainedCount,
		arg.HeldCount,
	)
	var i AppRetentionRun
	err := row.Scan(
		&i.ID,
		&i.DataClass,
		&i.ExecutedAt,
		&i.CutoffAt,
		&i.PurgedCount,
		&i.AnonymizedCount,
		&i.RetainedCount,
		&i.HeldCount,
	)
	return i, err
}

const getRetentionRunForClassAt = `-- name: GetRetentionRunForClassAt :one
SELECT id, data_class, executed_at, cutoff_at, purged_count, anonymized_count, retained_count, held_count
FROM app.retention_runs
WHERE data_class = $1::text
  AND executed_at = $2::timestamptz
`

type GetRetentionRunForClassAtParams struct {
	DataClass  string
	ExecutedAt pgtype.Timestamptz
}

// GetRetentionRunForClassAt resolves the recorded run of one class and
// instant, so a replay reports what the ledger holds instead of inventing a
// second outcome.
func (q *Queries) GetRetentionRunForClassAt(ctx context.Context, arg GetRetentionRunForClassAtParams) (AppRetentionRun, error) {
	row := q.db.QueryRow(ctx, getRetentionRunForClassAt, arg.DataClass, arg.ExecutedAt)
	var i AppRetentionRun
	err := row.Scan(
		&i.ID,
		&i.DataClass,
		&i.ExecutedAt,
		&i.CutoffAt,
		&i.PurgedCount,
		&i.AnonymizedCount,
		&i.RetainedCount,
		&i.HeldCount,
	)
	return i, err
}

const listActiveRetentionHolds = `-- name: ListActiveRetentionHolds :many

SELECT id, data_class, account_id, reason_code, placed_at
FROM app.retention_holds
WHERE released_at IS NULL
ORDER BY placed_at, id
`

type ListActiveRetentionHoldsRow struct {
	ID         pgtype.UUID
	DataClass  string
	AccountID  pgtype.UUID
	ReasonCode string
	PlacedAt   pgtype.Timestamptz
}

// Data retention statements (P14-T07, docs/PRIVACY.md §1/§5,
// REQ-PRIV-01). One schedule per governed class decides the action; these
// statements execute it and count what happened.
//
// Every purge and anonymize statement:
//   - is scoped by the class cutoff (now minus the class window) applied to
//     the terminal instant of the record (used, revoked or expired), so a
//     record inside the window is never touched;
//   - excludes the accounts covered by an active hold of that class, and
//     the whole class when a class-wide hold is in force;
//   - returns the affected count and the count preserved by holds in one
//     statement, so the ledger cannot disagree with what happened.
//
// Retained classes purge nothing by design: their statements only count the
// records kept under obligation.
// ListActiveRetentionHolds resolves the holds in force for the job.
func (q *Queries) ListActiveRetentionHolds(ctx context.Context) ([]ListActiveRetentionHoldsRow, error) {
	rows, err := q.db.Query(ctx, listActiveRetentionHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRetentionHoldsRow{}
	for rows.Next() {
		var i ListActiveRetentionHoldsRow
		if err := rows.Scan(
			&i.ID,
			&i.DataClass,
			&i.AccountID,
			&i.ReasonCode,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredExportDocuments = `-- name: PurgeExpiredExportDocuments :one
WITH scope AS (
    SELECT export.id, export.account_id
    FROM app.data_exports export
    WHERE (export.status = 'ready' AND export.expires_at <= $1::timestamptz)
       OR (export.status = 'requested' AND export.requested_at <= $1::timestamptz)
),
purged AS (
    UPDATE app.data_exports target
    SET status = 'expired',
        document = NULL,
        document_sha256 = NULL,
        updated_at = $2::timestamptz
    FROM scope
    WHERE target.id = scope.id
      AND NOT $3::boolean
      AND NOT (scope.account_id = ANY (COALESCE($4::uuid[], '{}'::uuid[])))
    RETURNING 1 AS row_count
),
preserved AS (
    SELECT 1
    FROM scope
    WHERE $3::boolean
       OR scope.account_id = ANY (COALESCE($4::uuid[], '{}'::uuid[]))
)
SELECT
    (SELECT count(*) FROM purged)::integer AS purged,
    (SELECT count(*) FROM preserved)::integer AS held
`

type PurgeExpiredExportDocumentsParams struct {
	Cutoff       pgtype.Timestamptz
	ExecutedAt   pgtype.Timestamptz
	ClassHeld    bool
	HeldAccounts []pgtype.UUID
}

type PurgeExpiredExportDocumentsRow struct {
	Purged int32
	Held   int32
}

// PurgeExpiredExportDocuments purges the document bytes of exports whose
// link expired at or before the cutoff and expires requests that were never
// generated by the cutoff. The record itself is retained: migration 00026
// forbids deleting export rows, and the download capability is already
// worthless once the record is expired.
func (q *Queries) PurgeExpiredExportDocuments(ctx context.Context, arg PurgeExpiredExportDocumentsParams) (PurgeExpiredExportDocumentsRow, error) {
	row := q.db.QueryRow(ctx, purgeExpiredExportDocuments,
		arg.Cutoff,
		arg.ExecutedAt,
		arg.ClassHeld,
		arg.HeldAccounts,
	)
	var i PurgeExpiredExportDocumentsRow
	err := row.Scan(&i.Purged, &i.Held)
	return i, err
}

const purgeTerminalRecoveryTokens = `-- name: PurgeTerminalRecoveryTokens :one
WITH scope AS (
    SELECT token.id, token.account_id
    FROM app.password_reset_tokens token
    WHERE (token.used_at IS NOT NULL AND token.used_at <= $1::timestamptz)
       OR token.expires_at <= $1::timestamptz
),
purged AS (
    DELETE FROM app.password_reset_tokens target
    USING scope
    WHERE target.id = scope.id
      AND NOT $2::boolean
      AND NOT (scope.account_id = ANY (COALESCE($3::uuid[], '{}'::uuid[])))
    RETURNING 1 AS row_count
),
preserved AS (
    SELECT 1
    FROM scope
    WHERE $2::boolean
       OR scope.account_id = ANY (COALESCE($3::uuid[], '{}'::uuid[]))
)
SELECT
    (SELECT count(*) FROM purged)::integer AS purged,
    (SELECT count(*) FROM preserved)::integer AS held
`

type PurgeTerminalRecoveryTokensParams struct {
	Cutoff       pgtype.Timestamptz
	ClassHeld    bool
	HeldAccounts []pgtype.UUID
}

type PurgeTerminalRecoveryTokensRow struct {
	Purged int32
	Held   int32
}

// PurgeTerminalRecoveryTokens removes password recovery tokens that were
// used or expired at or before the cutoff.
func (q *Queries) PurgeTerminalRecoveryTokens(ctx context.Context, arg PurgeTerminalRecoveryTokensParams) (PurgeTerminalRecoveryTokensRow, error) {
	row := q.db.QueryRow(ctx, purgeTerminalRecoveryTokens, arg.Cutoff, arg.ClassHeld, arg.HeldAccounts)
	var i PurgeTerminalRecoveryTokensRow
	err := row.Scan(&i.Purged, &i.Held)
	return i, err
}

const purgeTerminalSessions = `-- name: PurgeTerminalSessions :one
WITH scope AS (
    SELECT session.id, session.account_id
    FROM app.sessions session
    WHERE (session.revoked_at IS NOT NULL AND session.revoked_at <= $1::timestamptz)
       OR session.expires_at <= $1::timestamptz
),
purged AS (
    DELETE FROM app.sessions target
    USING scope
    WHERE target.id = scope.id
      AND NOT $2::boolean
      AND NOT (scope.account_id = ANY (COALESCE($3::uuid[], '{}'::uuid[])))
    RETURNING 1 AS row_count
),
preserved AS (
    SELECT 1
    FROM scope
    WHERE $2::boolean
       OR scope.account_id = ANY (COALESCE($3::uuid[], '{}'::uuid[]))
)
SELECT
    (SELECT count(*) FROM purged)::integer AS purged,
    (SELECT count(*) FROM preserved)::integer AS held
`

type PurgeTerminalSessionsParams struct {
	Cutoff       pgtype.Timestamptz
	ClassHeld    bool
	HeldAccounts []pgtype.UUID
}

type PurgeTerminalSessionsRow struct {
	Purged int32
	Held   int32
}

// PurgeTerminalSessions removes sessions revoked or expired at or before
// the cutoff; the restricted client references travel with the row.
func (q *Queries) PurgeTerminalSessions(ctx context.Context, arg PurgeTerminalSessionsParams) (PurgeTerminalSessionsRow, error) {
	row := q.db.QueryRow(ctx, purgeTerminalSessions, arg.Cutoff, arg.ClassHeld, arg.HeldAccounts)
	var i PurgeTerminalSessionsRow
	err := row.Scan(&i.Purged, &i.Held)
	return i, err
}

const purgeTerminalVerificationTokens = `-- name: PurgeTerminalVerificationTokens :one
WITH scope AS (
    SELECT token.id, token.account_id
    FROM app.email_verification_tokens token
    WHERE (token.used_at IS NOT NULL AND token.used_at <= $1::timestamptz)
       OR token.expires_at <= $1::timestamptz
),
purged AS (
    DELETE FROM app.email_verification_tokens target
    USING scope
    WHERE target.id = scope.id
      AND NOT $2::boolean
      AND NOT (scope.account_id = ANY (COALESCE($3::uuid[], '{}'::uuid[])))
    RETURNING 1 AS row_count
),
preserved AS (
    SELECT 1
    FROM scope
    WHERE $2::boolean
       OR scope.account_id = ANY (COALESCE($3::uuid[], '{}'::uuid[]))
)
SELECT
    (SELECT count(*) FROM purged)::integer AS purged,
    (SELECT count(*) FROM preserved)::integer AS held
`

type PurgeTerminalVerificationTokensParams struct {
	Cutoff       pgtype.Timestamptz
	ClassHeld    bool
	HeldAccounts []pgtype.UUID
}

type PurgeTerminalVerificationTokensRow struct {
	Purged int32
	Held   int32
}

// PurgeTerminalVerificationTokens removes verification tokens that were
// used or expired at or before the cutoff.
func (q *Queries) PurgeTerminalVerificationTokens(ctx context.Context, arg PurgeTerminalVerificationTokensParams) (PurgeTerminalVerificationTokensRow, error) {
	row := q.db.QueryRow(ctx, purgeTerminalVerificationTokens, arg.Cutoff, arg.ClassHeld, arg.HeldAccounts)
	var i PurgeTerminalVerificationTokensRow
	err := row.Scan(&i.Purged, &i.Held)
	return i, err
}
