// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallet.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletAccount = `-- name: CreateWalletAccount :one

INSERT INTO app.wallet_accounts (account_id)
VALUES ($1)
RETURNING account_id, balance_free, balance_purchased, created_at, updated_at
`

// Wallet ledger queries for the PostgreSQL platform adapter.
//
// The ledger is append-only: these queries only create wallet rows, insert
// operations/transactions and read them back. No query updates or deletes a
// transaction, and the runtime grants enforce the same boundary in the
// database (THR-WAL-02).
func (q *Queries) CreateWalletAccount(ctx context.Context, accountID pgtype.UUID) (AppWalletAccount, error) {
	row := q.db.QueryRow(ctx, createWalletAccount, accountID)
	var i AppWalletAccount
	err := row.Scan(
		&i.AccountID,
		&i.BalanceFree,
		&i.BalancePurchased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletOperation = `-- name: CreateWalletOperation :one
INSERT INTO app.wallet_operations (account_id, operation_type, idempotency_key, reference)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, operation_type, idempotency_key, reference, created_at
`

type CreateWalletOperationParams struct {
	AccountID      pgtype.UUID
	OperationType  string
	IdempotencyKey string
	Reference      string
}

func (q *Queries) CreateWalletOperation(ctx context.Context, arg CreateWalletOperationParams) (AppWalletOperation, error) {
	row := q.db.QueryRow(ctx, createWalletOperation,
		arg.AccountID,
		arg.OperationType,
		arg.IdempotencyKey,
		arg.Reference,
	)
	var i AppWalletOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperationType,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO app.wallet_transactions (operation_id, bucket, amount)
VALUES ($1, $2, $3)
RETURNING id, operation_id, bucket, amount, created_at
`

type CreateWalletTransactionParams struct {
	OperationID pgtype.UUID
	Bucket      string
	Amount      int64
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (AppWalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction, arg.OperationID, arg.Bucket, arg.Amount)
	var i AppWalletTransaction
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Bucket,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletAccount = `-- name: GetWalletAccount :one
SELECT account_id, balance_free, balance_purchased, created_at, updated_at
FROM app.wallet_accounts
WHERE account_id = $1
`

func (q *Queries) GetWalletAccount(ctx context.Context, accountID pgtype.UUID) (AppWalletAccount, error) {
	row := q.db.QueryRow(ctx, getWalletAccount, accountID)
	var i AppWalletAccount
	err := row.Scan(
		&i.AccountID,
		&i.BalanceFree,
		&i.BalancePurchased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletOperationByIdempotencyKey = `-- name: GetWalletOperationByIdempotencyKey :one
SELECT id, account_id, operation_type, idempotency_key, reference, created_at
FROM app.wallet_operations
WHERE idempotency_key = $1
`

func (q *Queries) GetWalletOperationByIdempotencyKey(ctx context.Context, idempotencyKey string) (AppWalletOperation, error) {
	row := q.db.QueryRow(ctx, getWalletOperationByIdempotencyKey, idempotencyKey)
	var i AppWalletOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperationType,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const listWalletTransactionsByAccount = `-- name: ListWalletTransactionsByAccount :many
SELECT t.id, t.operation_id, t.bucket, t.amount, t.created_at,
       o.operation_type, o.reference
FROM app.wallet_transactions t
JOIN app.wallet_operations o ON o.id = t.operation_id
WHERE o.account_id = $1
ORDER BY t.created_at DESC, t.id DESC
`

type ListWalletTransactionsByAccountRow struct {
	ID            pgtype.UUID
	OperationID   pgtype.UUID
	Bucket        string
	Amount        int64
	CreatedAt     pgtype.Timestamptz
	OperationType string
	Reference     string
}

func (q *Queries) ListWalletTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]ListWalletTransactionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listWalletTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTransactionsByAccountRow{}
	for rows.Next() {
		var i ListWalletTransactionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Bucket,
			&i.Amount,
			&i.CreatedAt,
			&i.OperationType,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
