// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: wallet.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyWalletDebit = `-- name: ApplyWalletDebit :one
UPDATE app.wallet_accounts
SET balance_free = balance_free - $2,
    balance_purchased = balance_purchased - $3,
    updated_at = now()
WHERE account_id = $1
RETURNING account_id, balance_free, balance_purchased, created_at, updated_at
`

type ApplyWalletDebitParams struct {
	AccountID        pgtype.UUID
	BalanceFree      int64
	BalancePurchased int64
}

// ApplyWalletDebit subtracts the planned bucket consumptions in a single
// statement; the CHECK (balance >= 0) guards the invariant even if a caller
// gets the plan wrong.
func (q *Queries) ApplyWalletDebit(ctx context.Context, arg ApplyWalletDebitParams) (AppWalletAccount, error) {
	row := q.db.QueryRow(ctx, applyWalletDebit, arg.AccountID, arg.BalanceFree, arg.BalancePurchased)
	var i AppWalletAccount
	err := row.Scan(
		&i.AccountID,
		&i.BalanceFree,
		&i.BalancePurchased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletAccount = `-- name: CreateWalletAccount :one

INSERT INTO app.wallet_accounts (account_id)
VALUES ($1)
RETURNING account_id, balance_free, balance_purchased, created_at, updated_at
`

// Wallet ledger queries for the PostgreSQL platform adapter.
//
// The ledger is append-only: these queries only create wallet rows, insert
// operations/transactions and read them back. No query updates or deletes a
// transaction, and the runtime grants enforce the same boundary in the
// database (THR-WAL-02).
func (q *Queries) CreateWalletAccount(ctx context.Context, accountID pgtype.UUID) (AppWalletAccount, error) {
	row := q.db.QueryRow(ctx, createWalletAccount, accountID)
	var i AppWalletAccount
	err := row.Scan(
		&i.AccountID,
		&i.BalanceFree,
		&i.BalancePurchased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletOperation = `-- name: CreateWalletOperation :one
INSERT INTO app.wallet_operations (account_id, operation_type, idempotency_key, reference)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, operation_type, idempotency_key, reference, created_at
`

type CreateWalletOperationParams struct {
	AccountID      pgtype.UUID
	OperationType  string
	IdempotencyKey string
	Reference      string
}

func (q *Queries) CreateWalletOperation(ctx context.Context, arg CreateWalletOperationParams) (AppWalletOperation, error) {
	row := q.db.QueryRow(ctx, createWalletOperation,
		arg.AccountID,
		arg.OperationType,
		arg.IdempotencyKey,
		arg.Reference,
	)
	var i AppWalletOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperationType,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const createWalletOperationIfAbsent = `-- name: CreateWalletOperationIfAbsent :one
INSERT INTO app.wallet_operations (account_id, operation_type, idempotency_key, reference)
VALUES ($1, $2, $3, $4)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, account_id, operation_type, idempotency_key, reference, created_at
`

type CreateWalletOperationIfAbsentParams struct {
	AccountID      pgtype.UUID
	OperationType  string
	IdempotencyKey string
	Reference      string
}

// CreateWalletOperationIfAbsent inserts the operation exactly once per
// idempotency key. On a conflict it returns no row, which tells the adapter
// to replay the original operation (P06-T03).
func (q *Queries) CreateWalletOperationIfAbsent(ctx context.Context, arg CreateWalletOperationIfAbsentParams) (AppWalletOperation, error) {
	row := q.db.QueryRow(ctx, createWalletOperationIfAbsent,
		arg.AccountID,
		arg.OperationType,
		arg.IdempotencyKey,
		arg.Reference,
	)
	var i AppWalletOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperationType,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO app.wallet_transactions (operation_id, bucket, amount)
VALUES ($1, $2, $3)
RETURNING id, operation_id, bucket, amount, created_at
`

type CreateWalletTransactionParams struct {
	OperationID pgtype.UUID
	Bucket      string
	Amount      int64
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (AppWalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction, arg.OperationID, arg.Bucket, arg.Amount)
	var i AppWalletTransaction
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Bucket,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const creditFreeBalance = `-- name: CreditFreeBalance :one
UPDATE app.wallet_accounts
SET balance_free = balance_free + $2,
    updated_at = now()
WHERE account_id = $1
RETURNING account_id, balance_free, balance_purchased, created_at, updated_at
`

type CreditFreeBalanceParams struct {
	AccountID   pgtype.UUID
	BalanceFree int64
}

// CreditFreeBalance adds the delta to the FREE_INK balance projection. The
// CHECK (balance_free >= 0) guards the invariant even here.
func (q *Queries) CreditFreeBalance(ctx context.Context, arg CreditFreeBalanceParams) (AppWalletAccount, error) {
	row := q.db.QueryRow(ctx, creditFreeBalance, arg.AccountID, arg.BalanceFree)
	var i AppWalletAccount
	err := row.Scan(
		&i.AccountID,
		&i.BalanceFree,
		&i.BalancePurchased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditPurchasedBalance = `-- name: CreditPurchasedBalance :one
UPDATE app.wallet_accounts
SET balance_purchased = balance_purchased + $2,
    updated_at = now()
WHERE account_id = $1
RETURNING account_id, balance_free, balance_purchased, created_at, updated_at
`

type CreditPurchasedBalanceParams struct {
	AccountID        pgtype.UUID
	BalancePurchased int64
}

func (q *Queries) CreditPurchasedBalance(ctx context.Context, arg CreditPurchasedBalanceParams) (AppWalletAccount, error) {
	row := q.db.QueryRow(ctx, creditPurchasedBalance, arg.AccountID, arg.BalancePurchased)
	var i AppWalletAccount
	err := row.Scan(
		&i.AccountID,
		&i.BalanceFree,
		&i.BalancePurchased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureWalletAccount = `-- name: EnsureWalletAccount :exec
INSERT INTO app.wallet_accounts (account_id)
VALUES ($1)
ON CONFLICT (account_id) DO NOTHING
`

// EnsureWalletAccount materializes the balance projection row for an
// account; a pre-existing row is left untouched, including its balances.
func (q *Queries) EnsureWalletAccount(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureWalletAccount, accountID)
	return err
}

const getDerivedWalletBalance = `-- name: GetDerivedWalletBalance :one
SELECT
    COALESCE(sum(t.amount) FILTER (WHERE t.bucket = 'FREE_INK'), 0)::bigint AS balance_free,
    COALESCE(sum(t.amount) FILTER (WHERE t.bucket = 'PURCHASED_INK'), 0)::bigint AS balance_purchased
FROM app.wallet_transactions t
JOIN app.wallet_operations o ON o.id = t.operation_id
WHERE o.account_id = $1
`

type GetDerivedWalletBalanceRow struct {
	BalanceFree      int64
	BalancePurchased int64
}

// GetDerivedWalletBalance recomputes both bucket balances exclusively from
// the append-only ledger: the source of truth for the cached projection
// (P06-T05, REQ-WAL-01).
func (q *Queries) GetDerivedWalletBalance(ctx context.Context, accountID pgtype.UUID) (GetDerivedWalletBalanceRow, error) {
	row := q.db.QueryRow(ctx, getDerivedWalletBalance, accountID)
	var i GetDerivedWalletBalanceRow
	err := row.Scan(&i.BalanceFree, &i.BalancePurchased)
	return i, err
}

const getWalletAccount = `-- name: GetWalletAccount :one
SELECT account_id, balance_free, balance_purchased, created_at, updated_at
FROM app.wallet_accounts
WHERE account_id = $1
`

func (q *Queries) GetWalletAccount(ctx context.Context, accountID pgtype.UUID) (AppWalletAccount, error) {
	row := q.db.QueryRow(ctx, getWalletAccount, accountID)
	var i AppWalletAccount
	err := row.Scan(
		&i.AccountID,
		&i.BalanceFree,
		&i.BalancePurchased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletAccountForUpdate = `-- name: GetWalletAccountForUpdate :one
SELECT account_id, balance_free, balance_purchased, created_at, updated_at
FROM app.wallet_accounts
WHERE account_id = $1
FOR UPDATE
`

// GetWalletAccountForUpdate locks the balance projection row of an account
// for the duration of the transaction, serializing concurrent debits so no
// double spend can pass the balance check (THR-WAL-01).
func (q *Queries) GetWalletAccountForUpdate(ctx context.Context, accountID pgtype.UUID) (AppWalletAccount, error) {
	row := q.db.QueryRow(ctx, getWalletAccountForUpdate, accountID)
	var i AppWalletAccount
	err := row.Scan(
		&i.AccountID,
		&i.BalanceFree,
		&i.BalancePurchased,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletOperationByIdempotencyKey = `-- name: GetWalletOperationByIdempotencyKey :one
SELECT id, account_id, operation_type, idempotency_key, reference, created_at
FROM app.wallet_operations
WHERE idempotency_key = $1
`

func (q *Queries) GetWalletOperationByIdempotencyKey(ctx context.Context, idempotencyKey string) (AppWalletOperation, error) {
	row := q.db.QueryRow(ctx, getWalletOperationByIdempotencyKey, idempotencyKey)
	var i AppWalletOperation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OperationType,
		&i.IdempotencyKey,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const listWalletStatementPage = `-- name: ListWalletStatementPage :many
SELECT t.id, t.operation_id, t.bucket, t.amount, t.created_at,
       o.operation_type, o.reference
FROM app.wallet_transactions t
JOIN app.wallet_operations o ON o.id = t.operation_id
WHERE o.account_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (t.created_at, t.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY t.created_at DESC, t.id DESC
LIMIT $4
`

type ListWalletStatementPageParams struct {
	AccountID      pgtype.UUID
	AfterCreatedAt pgtype.Timestamptz
	AfterID        pgtype.UUID
	PageLimit      int32
}

type ListWalletStatementPageRow struct {
	ID            pgtype.UUID
	OperationID   pgtype.UUID
	Bucket        string
	Amount        int64
	CreatedAt     pgtype.Timestamptz
	OperationType string
	Reference     string
}

// ListWalletStatementPage returns one keyset-paginated page of the account
// statement, newest first. NULL after_* parameters select the first page;
// the (created_at, id) tuple comparison never duplicates or skips rows.
func (q *Queries) ListWalletStatementPage(ctx context.Context, arg ListWalletStatementPageParams) ([]ListWalletStatementPageRow, error) {
	rows, err := q.db.Query(ctx, listWalletStatementPage,
		arg.AccountID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletStatementPageRow{}
	for rows.Next() {
		var i ListWalletStatementPageRow
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Bucket,
			&i.Amount,
			&i.CreatedAt,
			&i.OperationType,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactionsByAccount = `-- name: ListWalletTransactionsByAccount :many
SELECT t.id, t.operation_id, t.bucket, t.amount, t.created_at,
       o.operation_type, o.reference
FROM app.wallet_transactions t
JOIN app.wallet_operations o ON o.id = t.operation_id
WHERE o.account_id = $1
ORDER BY t.created_at DESC, t.id DESC
`

type ListWalletTransactionsByAccountRow struct {
	ID            pgtype.UUID
	OperationID   pgtype.UUID
	Bucket        string
	Amount        int64
	CreatedAt     pgtype.Timestamptz
	OperationType string
	Reference     string
}

func (q *Queries) ListWalletTransactionsByAccount(ctx context.Context, accountID pgtype.UUID) ([]ListWalletTransactionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listWalletTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTransactionsByAccountRow{}
	for rows.Next() {
		var i ListWalletTransactionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Bucket,
			&i.Amount,
			&i.CreatedAt,
			&i.OperationType,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactionsByOperationID = `-- name: ListWalletTransactionsByOperationID :many
SELECT id, operation_id, bucket, amount, created_at
FROM app.wallet_transactions
WHERE operation_id = $1
ORDER BY bucket
`

func (q *Queries) ListWalletTransactionsByOperationID(ctx context.Context, operationID pgtype.UUID) ([]AppWalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactionsByOperationID, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppWalletTransaction{}
	for rows.Next() {
		var i AppWalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Bucket,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
