-- +goose Up
-- 00001 establishes the application schema and its metadata table.
--
-- The plan's app.schema_metadata doubles as the goose version table: the
-- runner passes the schema-qualified name to goose, which creates the
-- table (with exactly this shape) on first use and tracks every applied
-- migration in it. This file keeps the creation in the migration history
-- itself, idempotently, so a database provisioned outside goose still
-- matches what goose would create.
--
-- Extensions: none are strictly necessary at this point. PostgreSQL 18
-- provides gen_random_uuid() and uuidv7() in core, so the pgcrypto and
-- pg_uuidv7 extensions stay out of the database. If a later, explicitly
-- approved task needs one, it must be added in its own forward migration.
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.schema_metadata (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS app.schema_metadata;
DROP SCHEMA IF EXISTS app;
